// DragonBreak Online: dungeons as leases. Loaded by gamemode.js (re-required on every hot reload).
//
// One world, so a dungeon cannot be cloned per party. Instead the first party to use an entrance
// claims the dungeon: the leader picks a difficulty, the party is moved inside, everyone else is
// refused at the door until the hour ends, the party leaves, or the dungeon is cleared (every
// enemy dead, every chest opened). Enemies are Bethesda's placements (dungeons.json, each leveled
// actor resolved to concrete NPCs by level), written into NPC-Spawns.json only while the lease
// runs, one zone per placement so they stand where the Creation Kit put them; Alduinak's
// NpcSpawnSystem places them on claim, before the party is moved in. Loot in every container is
// generated by the server from loot.json per difficulty (big chests get the real roll, urns and
// sacks a little), some big chests are locked for the Lockpicking skill, and every lootable
// container glows until opened. Humanoid bodies are looted with E for a small roll; other spawned
// corpses are trimmed on death so a body yields loot, not a full kit. When the lease ends
// everyone inside is put back at the entrance and each member waits an hour before claiming that
// dungeon again.
//
// gamemode-config.json "dungeons": { enabled, leaseMinutes, cooldownMinutes, warnMinutes,
//   graceMinutes, partyMax, lockedShare: {story, normal, hard, nightmare} }
'use strict';
const fs = require('fs');
const path = require('path');

module.exports = (api) => {
  const { mp, log, personal, system, registerChatCommand, onUi, openWidget, closeWidget, sendPacket, findByName, display, who, audit, profileOf, nameOf, onlineActors, isAdmin, giveItem, cfg, every } = api;
  const C = Object.assign({ enabled: true, leaseMinutes: 60, cooldownMinutes: 60, warnMinutes: 5, graceMinutes: 3, partyMax: 6, entranceReach: 2500, lockedShare: { story: 0, normal: 0.2, hard: 0.35, nightmare: 0.5 } }, cfg.dungeons || {});
  const GATE_WIDGET_ID = 31;
  const LOCKPICK_BASE = 0x0000000a;
  const GOLD_BASE = 0x0000000f;
  const SPAWNS_FILE = path.resolve('NPC-Spawns.json');
  const SPAWNED_IDS_FILE = path.resolve('zone-spawns.json');
  const ZONE_PREFIX = 'dungeon:';
  const DIFFICULTIES = [
    { id: 'story',     label: 'Novice',    blurb: 'Ordinary foes, fewer of them. Modest loot, no locked chests.',                                              pick: 'mid',  mult: 0.6,  gear: 150,  potionTier: 0, gold: [3,  12], soulgem: 0,    soulTier: 0, ench: 0,    bossEnch: 0.05 },
    { id: 'normal',    label: 'Adept',     blurb: 'As Bethesda placed them. Fair loot, a few locked chests.',                                                  pick: 'mid',  mult: 1,    gear: 400,  potionTier: 1, gold: [5,  25], soulgem: 0.03, soulTier: 1, ench: 0.02, bossEnch: 0.12 },
    { id: 'hard',      label: 'Expert',    blurb: 'The strongest of each kind, more of them. Better loot.',                                                     pick: 'high', mult: 1.25, gear: 900,  potionTier: 2, gold: [10, 45], soulgem: 0.06, soulTier: 2, ench: 0.05, bossEnch: 0.25 },
    { id: 'nightmare', label: 'Master',    blurb: 'The strongest, half again as many, most chests locked. The best loot.',                                      pick: 'high', mult: 1.6,  gear: 3000, potionTier: 3, gold: [20, 80], soulgem: 0.1,  soulTier: 3, ench: 0.08, bossEnch: 0.4  },
  ];
  const LOCK_LEVELS = ['Novice', 'Apprentice', 'Adept', 'Expert', 'Master'];
  const LOCK_BY_DIFF = { normal: [0, 1], hard: [1, 2, 3], nightmare: [2, 3, 4] };
  const TYPE_NAMES = { nordic: 'Nordic ruin', dwemer: 'Dwemer ruin', cave: 'Cave', ice: 'Ice cave', fort: 'Fort', camp: 'Camp' };

  const normDesc = (d) => { const s = String(d || ''); const i = s.indexOf(':'); if (i < 0) return s.toLowerCase(); const n = parseInt(s.slice(0, i), 16); return (Number.isFinite(n) ? n.toString(16) : s.slice(0, i).toLowerCase()) + ':' + s.slice(i + 1).toLowerCase(); };
  const idOf = (desc) => { try { return mp.getIdFromDesc(desc) >>> 0; } catch (e) { return 0; } };
  const rnd = (a, b) => a + Math.floor(Math.random() * (b - a + 1));
  const pickFrom = (list) => list.length ? list[Math.floor(Math.random() * list.length)] : null;

  // ---- data ------------------------------------------------------------------------------------
  const readJson = (file, fallback) => { try { return JSON.parse(fs.readFileSync(path.resolve(file), 'utf8')); } catch (e) { log(`${file} unreadable`, e.message); return fallback; } };
  const DATA = readJson('dungeons.json', { dungeons: [] });
  const LOOT = (readJson('loot.json', { pools: {} }).pools) || {};
  const byId = new Map();            // dungeon id -> dungeon
  const outsideDoors = new Map();    // outside door refId -> { d, entrance }
  const insideDoors = new Map();     // inside door refId -> { d, entrance }
  const cellToDungeon = new Map();   // normalized cell desc -> dungeon
  const chestRefs = new Map();       // dungeon container refId -> { d, chest }
  for (const d of DATA.dungeons || []) {
    byId.set(d.id, d);
    d.bigChestIds = []; d.chestIds = [];
    for (const e of d.entrances || []) {
      const o = idOf(e.outsideDesc), i = idOf(e.insideDesc);
      if (o) outsideDoors.set(o, { d, entrance: e });
      if (i) insideDoors.set(i, { d, entrance: e });
    }
    for (const c of d.cells || []) cellToDungeon.set(normDesc(c.desc), d);
    for (const ch of d.chests || []) { const id = idOf(ch.ref); if (!id) continue; chestRefs.set(id, { d, chest: ch }); d.chestIds.push(id); if (ch.big) d.bigChestIds.push(id); }
  }

  // gamemode.js leaves containers in these cells alone (dungeons.js fills them per lease).
  globalThis.__dboDungeonCells = new Set(cellToDungeon.keys());

  // ---- state (survives hot reloads) -------------------------------------------------------------
  const ST = globalThis.__dboDungeons = globalThis.__dboDungeons || { leases: new Map(), parties: new Map(), memberOf: new Map(), invites: new Map(), pending: new Map() };
  const partyOf = (pid) => { const leader = ST.memberOf.get(pid); return leader !== undefined ? ST.parties.get(leader) : null; };
  const partyMembers = (pid) => { const p = partyOf(pid); return p ? [...p.members] : [pid]; };
  const actorByProfile = (pid) => onlineActors().find((a) => profileOf(a) === pid) || 0;
  const cooldownsOf = (a) => { try { const r = mp.get(a, 'private.dungeonCooldowns'); return r && typeof r === 'object' ? r : {}; } catch (e) { return {}; } };
  const setCooldown = (a, dungeonId, until) => { const c = cooldownsOf(a); for (const k of Object.keys(c)) if (Number(c[k]) < Date.now()) delete c[k]; c[dungeonId] = until; try { mp.set(a, 'private.dungeonCooldowns', c); } catch (e) { log('cooldown save failed', e.message); } };
  const whereIs = (a) => { try { return normDesc(mp.get(a, 'worldOrCellDesc')); } catch (e) { return ''; } };
  const dungeonAround = (a) => cellToDungeon.get(whereIs(a)) || null;
  const distance = (a, pos, world) => { try { if (world && normDesc(mp.get(a, 'worldOrCellDesc')) !== normDesc(world)) return Infinity; const p = mp.get(a, 'pos'); return Math.hypot(p[0] - pos[0], p[1] - pos[1], p[2] - pos[2]); } catch (e) { return Infinity; } };
  const teleport = (a, where, pos, rot) => { try { mp.set(a, 'locationalData', { cellOrWorldDesc: where, pos, rot: rot || [0, 0, 0] }); return true; } catch (e) { log('teleport failed', e.message); return false; } };
  const glow = (a, refs, on, kind) => { for (let i = 0; i < refs.length; i += 150) sendPacket(a, { customPacketType: 'dboGlow', refs: refs.slice(i, i + 150), on: !!on, kind: kind || 'loot' }); };
  // A ref can be glowing as either kind, and "off" only matches the kind it is sent with
  const glowOff = (a, refs) => { glow(a, refs, false, 'loot'); glow(a, refs, false, 'locked'); };
  const glowClear = (a) => { try { sendPacket(a, { customPacketType: 'dboGlow', clear: true }); } catch (e) { /* offline */ } };
  // Login and re-entry wipe first, so a glow left by an expired lease cannot outlive it
  globalThis.__dboGlowClear = glowClear;
  const glowLease = (a, lease, d) => {
    glowClear(a);
    const locked = d.bigChestIds.filter((id) => lease.locked.has(id) && !lease.unlocked.has(id) && !lease.looted.has(id));
    const open = d.chestIds.filter((id) => !lease.looted.has(id) && locked.indexOf(id) === -1);
    glow(a, locked, true, 'locked'); glow(a, open, true, 'loot');
  };
  const leaseOfActor = (a) => { const pid = profileOf(a); for (const l of ST.leases.values()) if (l.members.has(pid)) return l; return null; };

  // Enemy families from ck-mcp\dungeon_pools.py, built from the leveled lists: a generic placement may become any
  // archetype of its own faction in its own province (bosses only boss archetypes). Quest, named and
  // dungeon-specific placements are not listed and stay as Bethesda placed them.
  const POOLS = readJson('dungeon-pools.json', { families: {}, placements: {} });
  const POOLS_KEEP = new Set(POOLS.keep || []);   // curation, Starts Dead, quest alias and set-piece refs, never swapped
  // DragonBreak's own placements stay as placed even if dungeons.json gained them after the pools were built
  const CURATED_REF = /:DragonBreak( Online Edits)?\.esp$/i;
  {
    let kept = 0, dropped = 0;
    for (const f of Object.values(POOLS.families || {})) {
      for (const a of [...(f.archetypes || []), ...(f.boss || [])]) {
        // this server must know every option as an NPC_, or the slot would fail to spawn
        a.options = (a.options || []).filter((o) => {
          let rec = null; try { rec = mp.lookupEspmRecordById(idOf(o[1])); } catch (e) { rec = null; }
          const ok = !!(rec && rec.record && String(rec.record.type) === 'NPC_');
          if (ok) kept++; else { dropped++; log(`dungeon pools: ${o[1]} ${o[2] || ''} is not an NPC_ on this server, dropped`); }
          return ok;
        });
      }
    }
    log(`dungeon pools: ${Object.keys(POOLS.families || {}).length} families, ${Object.keys(POOLS.placements || {}).length} placement types, ${kept} options${dropped ? `, ${dropped} dropped` : ''}`);
    const built = ((POOLS.source || {})['dungeons.json']) || '';
    let current = ''; try { current = require('crypto').createHash('sha1').update(fs.readFileSync(path.resolve('dungeons.json'))).digest('hex'); } catch (e) { /* unreadable, reported above */ }
    if (built && current && built !== current) log('dungeon pools: built from a different dungeons.json; run py ck-mcp\\dungeon_pools.py and reload');
  }

  // ---- spawn zones: one per placement, on Bethesda's spot, spawning the moment the cell is entered --
  const pickOption = (options, mode) => {
    if (!options || !options.length) return null;
    const sorted = options.slice().sort((x, y) => x[0] - y[0]);
    const len = sorted.length;
    if (len === 1) return sorted[0][1];
    let pool;
    if (mode === 'low') {
      const cut = Math.max(1, Math.ceil(len * 0.4));
      pool = sorted.slice(0, cut);
    } else if (mode === 'high') {
      const start = Math.floor(len * 0.55);
      pool = sorted.slice(start);
    } else {
      const start = Math.floor(len * 0.2);
      const end = Math.max(start + 1, Math.ceil(len * 0.8));
      pool = sorted.slice(start, end);
    }
    if (!pool || !pool.length) pool = sorted;
    return pool[Math.floor(Math.random() * pool.length)][1];
  };

  const zonesFor = (d, diff) => {
    const out = [];
    let n = 0;
    const province = (POOLS.provinces || {})[d.id] || provinceOfDungeon(d);
    const next = {};   // family (and boss) -> next archetype index, from a random start so each claim differs

    for (const z of d.zones || []) {
      for (const npc of z.npcs || []) {
        const edid = String(npc.edid || '');
        let opts = npc.options || [];
        let kind = edid;
        // A generic placement cycles through its own faction's archetypes; anything unlisted stays vanilla
        const ref = String(npc.ref || '');
        const entry = POOLS_KEEP.has(ref) || CURATED_REF.test(ref) ? null : (POOLS.placements || {})[`${province}|${edid}`];
        const family = entry ? (POOLS.families || {})[entry.family] : null;
        const archetypes = family ? ((entry.boss ? family.boss : family.archetypes) || []).filter((a) => a.options.length) : [];
        if (archetypes.length) {
          const key = entry.family + (entry.boss ? '#boss' : '');
          if (next[key] === undefined) next[key] = Math.floor(Math.random() * archetypes.length);
          const arch = archetypes[next[key]++ % archetypes.length];
          opts = arch.options;
          kind = arch.kind;
        }

        const id = pickOption(opts, diff.pick);
        if (!id || !Array.isArray(npc.pos)) continue;
        if (diff.mult < 1 && Math.random() > diff.mult) continue;          // fewer of them
        const count = 1 + (diff.mult > 1 && Math.random() < diff.mult - 1 ? 1 : 0); // sometimes a second one
        // Anchor = Bethesda's own (disabled) actor ref on that spot: the spawn appears there, not at a player.
        const zone = { Name: `${ZONE_PREFIX}${d.id}:${n++}`, ID: z.cell, POS: npc.pos, Size: 100000, NPC: [{ id, count }], Despawn: 0, Respawn: 0, Kind: kind, Prespawn: true };
        // Anchor ref is optional — if it resolves, the spawn appears exactly on that ref; if not, it falls
        // back to the baked POS which is still Bethesda's placement coordinate.
        if (npc.ref) {
          try {
            const anchorId = mp.getIdFromDesc(npc.ref.includes(':') ? npc.ref : undefined);
            if (anchorId && anchorId > 0) zone.Anchor = npc.ref;
          } catch (e) { /* ref not loaded in this server's ESM set; spawn at POS instead */ }
        }
        out.push(zone);
      }
    }
    return out;
  };
  const writeSpawnZones = () => {
    let root = null, list = [], key = 'zones';
    try {
      const parsed = JSON.parse(fs.readFileSync(SPAWNS_FILE, 'utf8'));
      if (Array.isArray(parsed)) list = parsed; else if (parsed && typeof parsed === 'object') { root = parsed; key = Object.keys(parsed).find((k) => k.toLowerCase() === 'zones') || 'zones'; list = Array.isArray(parsed[key]) ? parsed[key] : []; }
    } catch (e) { /* no file yet */ }
    const kept = list.filter((z) => !String((z && (z.Name || z.name)) || '').startsWith(ZONE_PREFIX));
    for (const lease of ST.leases.values()) kept.push(...lease.zones);
    const payload = root ? Object.assign({}, root, { [key]: kept }) : { _comment: 'NPC spawn zones. Entries named dungeon:* are written by server/dungeons.js for active dungeon leases and replaced on every change; other entries are kept.', zones: kept };
    try { fs.writeFileSync(SPAWNS_FILE + '.dungeons.tmp', JSON.stringify(payload, null, 1)); fs.renameSync(SPAWNS_FILE + '.dungeons.tmp', SPAWNS_FILE); }
    catch (e) { log('NPC-Spawns.json write failed', e.message); }
  };

  // ---- chest loot -------------------------------------------------------------------------------
  // An item with no p is Tamriel-wide, so a loot.json generated before the province tag still works.
  const hasProv = (it, prov) => !prov || !it.p || it.p.indexOf(prov) >= 0;
  // Additive: gear a context admits although the province tag excludes it. Beyond Skyrim puts the whole
  // draugr kit in CYRNorthfringeSanctum and nowhere else in its Cyrodiil.
  const NORDIC_GEAR = /^(?:Ench)?(?:Armor)?(?:Draugr|AncientNord|NordHero)|^(?:Draugr|Falmer)Arrow$/;
  // Restrictive: Cyrodiil gear that belongs to one kind of site only. Ayleid and Ancient Imperial arms are
  // grave goods; goblin gear belongs on goblins. Ayleid jewellery is deliberately not here - it circulates
  // as treasure, so CYREnchRing*Ayleid and CYREnchAmulet*Ayleid stay generally lootable.
  const AYLEID_GEAR = /^(?:CYR(?:Ench)?Ayleid|BSKAyleidStaff|CYR(?:Ench)?AncientImperial)/;
  const GOBLIN_GEAR = /^BSKGoblin|^CYRArmorGoblinShield/;
  // dungeons.json already carries Beyond Skyrim's own location keywords, so no generator re-run is needed.
  // Vilverin is an Ayleid ruin BS keyworded only as a cave, hence the id list.
  const lootOk = (lease) => {
    const prov = lease && lease.province;
    const d = lease ? byId.get(lease.id) : null;
    const kw = (d && d.keywords) || [];
    const has = (re) => kw.some((k) => re.test(k));
    const nordic = prov === 'cyrodiil' && ((d && d.type === 'nordic') || has(/NordicRuin|DraugrCrypt/i));
    const ayleid = has(/Ayleid/i) || /^CYR(Anga|Rielle|Sedor|Vilverin)/i.test((d && d.id) || '');
    const goblin = has(/GoblinDen/i);
    return (it) => {
      if (AYLEID_GEAR.test(it.name)) return ayleid;
      if (GOBLIN_GEAR.test(it.name)) return goblin;
      if (nordic && NORDIC_GEAR.test(it.name)) return true;
      return hasProv(it, prov);
    };
  };
  const ALL_OK = () => true;
  const pool = (name, maxValue, ok) => (LOOT[name] || []).filter((it) => (!maxValue || Number(it.value) <= maxValue) && (!ok || ok(it)));
  // Vanilla names potions by numeric strength, not by word: RestoreHealth01 is Minor, 03 Plentiful, 05
  // Extreme, 06 Ultimate; Resist* uses 25/50/75/100. The old word-matching tiers returned an empty array at
  // all four tiers against the live pool, so no potion dropped at any difficulty.
  const POTION_RANK = /^(?:DLC1|DLC2)?(Restore(?:Health|Magicka|Stamina|All)|Fortify[A-Za-z]+|Resist(?:Fire|Frost|Shock|Magic|Poison|Disease)|Cure(?:Disease|Poison)|Invisibility|Waterbreathing)(\d*)$/i;
  const rankOf = (name) => {
    const m = POTION_RANK.exec(name); if (!m) return 0;
    const n = Number(m[2] || 0);
    if (n === 25) return 1; if (n === 50) return 2; if (n === 75) return 3; if (n === 100) return 4;
    return n ? Math.min(n, 6) : 1;
  };
  const POTION_CAP = [1, 2, 4, 6];
  const potionPool = (tier, ok) => (LOOT.potions || []).filter((it) => {
    if (ok && !ok(it)) return false;
    const r = rankOf(it.name); if (!r) return false;
    if (tier <= 1 && !/^(?:DLC\d)?(Restore|Cure)/i.test(it.name)) return false;   // novice and adept: restoratives only
    return r <= POTION_CAP[Math.min(tier, 3)];
  });
  const SOUL_TIERS = [/petty/i, /petty|lesser/i, /petty|lesser|common/i, /./];
  const soulPool = (tier, ok) => (LOOT.soulgems || []).filter((it) => (SOUL_TIERS[Math.min(tier, 3)]).test(it.name) && (tier >= 3 || !/black|grand|greater/i.test(it.name)) && (!ok || ok(it)));
  const addEntry = (entries, item, count) => { if (!item) return; const id = idOf(item.id); if (!id) return; const hit = entries.find((e) => e.baseId === id); if (hit) hit.count += count; else entries.push({ baseId: id, count }); };
  const chestLoot = (diff, boss, ok = ALL_OK) => {
    const entries = [];
    addEntry(entries, { id: 'f:Skyrim.esm' }, Math.max(1, rnd(diff.gold[0], diff.gold[1]) * (boss ? 3 : 1)));
    if (boss || Math.random() < 0.45) addEntry(entries, pickFrom(potionPool(diff.potionTier, ok)), rnd(1, 2));
    if (boss && Math.random() < 0.7) addEntry(entries, pickFrom(potionPool(diff.potionTier, ok)), 1);
    if (Math.random() < 0.4) addEntry(entries, pickFrom(pool('ingredients', 0, ok)), rnd(1, 3));
    if (Math.random() < 0.25) addEntry(entries, pickFrom(pool('materials', 0, ok)), rnd(1, 2));
    if (diff.id !== 'story' && Math.random() < (boss ? 0.6 : 0.15)) addEntry(entries, pickFrom(pool('gems', diff.gear, ok)), 1);
    if (Math.random() < 0.3) addEntry(entries, pickFrom(pool('arrows', 0, ok)), rnd(5, 15));
    if (Math.random() < 0.2) addEntry(entries, pickFrom(pool('lockpicks', 0, ok)), rnd(1, 3));
    if (diff.soulgem > 0 && Math.random() < diff.soulgem * (boss ? 2 : 1)) addEntry(entries, pickFrom(soulPool(diff.soulTier, ok)), 1);
    const gearChance = boss ? 1 : 0.2;
    if (Math.random() < gearChance) addEntry(entries, pickFrom(pool(Math.random() < 0.5 ? 'weapons' : 'armor', diff.gear, ok)), 1);
    const enchChance = boss ? diff.bossEnch : diff.ench;
    if (enchChance > 0 && Math.random() < enchChance) addEntry(entries, pickFrom(pool(Math.random() < 0.5 ? 'ench_weapons' : 'ench_armor', diff.gear * 3, ok)), 1);
    return entries;
  };
  // Urns, sacks, barrels and the like: a little coin or food, now and then a potion or arrows
  const smallLoot = (diff, edid, ok = ALL_OK) => {
    const entries = [];
    const foodish = /food|barrel|basket|sack|cupboard|pantry|crate/i.test(edid || '');
    if (Math.random() < (foodish ? 0.25 : 0.5)) addEntry(entries, { id: 'f:Skyrim.esm' }, rnd(1, Math.max(2, diff.gold[0] * 2)));
    if (Math.random() < (foodish ? 0.8 : 0.35)) addEntry(entries, pickFrom(pool('food', 0, ok)), rnd(1, 2));
    if (Math.random() < 0.3) addEntry(entries, pickFrom(pool('ingredients', 0, ok)), rnd(1, 2));
    if (Math.random() < 0.15) addEntry(entries, pickFrom(potionPool(Math.max(0, diff.potionTier - 1), ok)), 1);
    if (Math.random() < 0.12) addEntry(entries, pickFrom(pool('arrows', 0, ok)), rnd(3, 8));
    if (!entries.length) addEntry(entries, { id: 'f:Skyrim.esm' }, rnd(1, 3));
    return entries;
  };
  const fillChests = (d, diff, lease) => {
    let filled = 0;
    const ok = lootOk(lease);
    for (const ch of d.chests || []) {
      const id = idOf(ch.ref); if (!id) continue;
      const boss = /boss/i.test(ch.edid);
      try { mp.set(id, 'inventory', { entries: ch.big ? chestLoot(diff, boss, ok) : smallLoot(diff, ch.edid, ok) }); filled++; } catch (e) { log('chest fill failed', ch.ref, e.message); }
    }
    return filled;
  };

  // ---- leases --------------------------------------------------------------------------------
  const minutesLeft = (until) => Math.max(1, Math.ceil((until - Date.now()) / 60000));
  const provinceOfDungeon = (d) => {
    if (!d) return 'skyrim';
    const s = JSON.stringify(d);
    if (/BSHeartland|BSAssets/i.test(s)) return 'cyrodiil';
    if (/Dragonborn|DLC2Solstheim/i.test(s)) return 'solstheim';
    return 'skyrim';
  };
  const startLease = (leaderActor, d, entrance, diff) => {
    const leaderPid = profileOf(leaderActor);
    const members = new Set(partyMembers(leaderPid));
    const zones = zonesFor(d, diff);
    const lease = { id: d.id, name: d.name, difficulty: diff.id, leader: leaderPid, members, startedAt: Date.now(), endsAt: Date.now() + C.leaseMinutes * 60000, warned: false, lastInsideAt: Date.now(), locked: new Map(), unlocked: new Set(), looted: new Set(), zones, totalNpcs: zones.reduce((n, z) => n + z.NPC[0].count, 0), seenNpcs: new Set(), deadNpcs: new Set(), entrance, province: (POOLS.provinces || {})[d.id] || provinceOfDungeon(d) };
    const share = Number((C.lockedShare || {})[diff.id]) || 0;
    const levels = LOCK_BY_DIFF[diff.id] || [];
    if (share > 0 && levels.length) {
      for (const id of d.bigChestIds) if (Math.random() < share) lease.locked.set(id, levels[Math.floor(Math.random() * levels.length)]);
    }
    lease.kinds = {}; for (const z of zones) lease.kinds[z.Name] = z.Kind || '';
    lease.armed = new Set();
    ST.leases.set(d.id, lease);
    writeSpawnZones();
    const filled = fillChests(d, diff, lease);
    const moveIn = (placed) => {
      if (ST.leases.get(d.id) !== lease) return;
      let moved = 0;
      for (const pid of members) {
        const a = actorByProfile(pid); if (!a) continue;
        if (a !== leaderActor && distance(a, entrance.doorPos || entrance.pos, entrance.world || entrance.cell) > C.entranceReach) { system(a, `${display(leaderActor)} has claimed ${d.name}. Use the entrance to join them.`); continue; }
        if (teleport(a, entrance.insideCell, entrance.insidePos, entrance.insideRot || [0, 0, 0])) { moved++; system(a, `${d.name} is yours for ${C.leaseMinutes} minutes (${diff.label}). Clear every enemy and open every big chest to finish early. ${lease.locked.size ? lease.locked.size + ' chest' + (lease.locked.size === 1 ? ' is' : 's are') + ' locked.' : ''}`); glowLease(a, lease, d); }
      }
      audit(`DUNGEON ${who(leaderActor)} claimed ${d.name} on ${diff.label} with ${members.size} member(s), ${zones.length} enemies (${placed >= 0 ? placed + ' placed before entry' : 'placed on entry'}), ${filled} containers filled, ${lease.locked.size} locked`);
      log(`dungeon ${d.id} claimed by ${display(leaderActor)}: ${diff.id}, ${moved} moved in, ${zones.length} enemies, ${placed} prespawned, ${filled} containers`);
    };
    // Enemies stand on their spots before anyone arrives; the party waits for that, at most a few seconds
    const spawnNow = globalThis.__alduinakNpcSpawnNow;
    if (typeof spawnNow !== 'function') return moveIn(-1);
    let done = false;
    // Arm and set placement factions before anyone arrives, so no client meets a spawn without them
    const finish = (placed) => { if (done) return; done = true; try { armLease(lease); factionCheck(lease); } catch (e) { log('dungeon prespawn setup failed', e.message); } moveIn(placed); };
    setTimeout(() => finish(-1), 6000);
    Promise.resolve().then(() => spawnNow(`${ZONE_PREFIX}${d.id}:`)).then((n) => finish(Number(n) || 0), (e) => { log('dungeon prespawn failed', e && e.message); finish(-1); });
  };
  const endLease = (lease, why) => {
    const d = byId.get(lease.id);
    ST.leases.delete(lease.id);
    for (const pid of lease.members) {
      const a = actorByProfile(pid);
      if (!a) continue;
      setCooldown(a, lease.id, Date.now() + C.cooldownMinutes * 60000);
      glowOff(a, d ? d.chestIds : []);
      const inside = dungeonAround(a);
      if (inside && inside.id === lease.id && d && why !== 'cleared') {
        const e = lease.entrance || (d.entrances || [])[0];
        if (e && e.pos) teleport(a, e.world || e.cell, e.pos, e.rot);
        system(a, why === 'time' ? `Your hour in ${lease.name} is up. You find yourself back at the entrance.` : `Your claim on ${lease.name} has ended.`);
      } else if (why === 'cleared') {
        system(a, `${lease.name} is cleared. Take your time leaving; it rests ${C.cooldownMinutes} minutes for you afterwards.`);
      } else {
        system(a, `Your claim on ${lease.name} has ended. It rests ${C.cooldownMinutes} minutes for you.`);
      }
    }
    // Emptied chests stay empty (CONT reloot is forbidden in server-settings); enemies go with the zones.
    writeSpawnZones();
    audit(`DUNGEON ${lease.name} released (${why})`);
  };
  // mp.getAllForms answers from a cache filled on its first call and never lists later spawns, so an id that throws once is skipped instead
  const spawnerTag = (lease, id) => {
    if (!lease.gone) lease.gone = new Set();
    if (lease.gone.has(id)) return '';
    try { return String(mp.get(id, 'private.npcSpawner') || ''); } catch (e) { lease.gone.add(id); return ''; }
  };
  // The spawn system's sidecar of live ids; each timer tick reads it once for every lease
  const readSpawnedIds = () => { try { const ids = JSON.parse(fs.readFileSync(SPAWNED_IDS_FILE, 'utf8')); return Array.isArray(ids) ? ids : null; } catch (e) { return null; } };
  // Enemies the spawn system has placed for this lease, from its sidecar of live ids.
  const trackNpcs = (lease, ids = readSpawnedIds()) => {
    if (!ids) return;
    const prefix = `${ZONE_PREFIX}${lease.id}:`;
    for (const id of ids) {
      if (lease.seenNpcs.has(id) && lease.deadNpcs.has(id)) continue;
      const tag = spawnerTag(lease, id);
      if (!tag.startsWith(prefix)) continue;
      lease.seenNpcs.add(id);
      try { if (mp.get(id, 'isDead') === true) lease.deadNpcs.add(id); } catch (e) { lease.deadNpcs.add(id); }
    }
    for (const id of lease.seenNpcs) { if (!ids.includes(id)) lease.deadNpcs.add(id); } // swept corpse
  };
  const isCleared = (lease) => {
    const d = byId.get(lease.id); if (!d) return false;
    if (lease.seenNpcs.size < lease.totalNpcs) return false;
    for (const id of lease.seenNpcs) if (!lease.deadNpcs.has(id)) return false;
    for (const id of d.bigChestIds) if (!lease.looted.has(id)) return false;
    return true;
  };
  const tick = () => {
    const now = Date.now();
    const ids = ST.leases.size ? readSpawnedIds() : null;
    for (const lease of [...ST.leases.values()]) {
      const insideNow = [...lease.members].some((pid) => { const a = actorByProfile(pid); const dd = a ? dungeonAround(a) : null; return dd && dd.id === lease.id; });
      if (insideNow) lease.lastInsideAt = now;
      trackNpcs(lease, ids);
      if (isCleared(lease)) { endLease(lease, 'cleared'); continue; }
      if (now >= lease.endsAt) { endLease(lease, 'time'); continue; }
      if (!lease.warned && lease.endsAt - now <= C.warnMinutes * 60000) {
        lease.warned = true;
        for (const pid of lease.members) { const a = actorByProfile(pid); if (a) system(a, `${C.warnMinutes} minutes left in ${lease.name}.`); }
      }
      if (now - lease.lastInsideAt > C.graceMinutes * 60000) endLease(lease, 'left');
    }
  };
  every('dungeons.tick', 15000, () => { try { tick(); } catch (e) { log('dungeon tick failed', e.message); } });

  // ---- arm unarmed enemies ---------------------------------------------------------------------
  // Spawned NPCs sometimes come out of their leveled lists with no weapon, and an unarmed NPC flees.
  // Every 2 s each new humanoid of a lease without a weapon gets one that fits its placement
  // (archer -> bow + arrows, two-hander -> greatsword/battleaxe/warhammer, caster -> dagger, else
  // sword/war axe/mace; draugr, falmer and forsworn keep their own kind) within the difficulty's band.
  const HUMANOID = /bandit|highwayman|marauder|outlaw|thug|forsworn|draugr|falmer|orc|soldier|guard|thalmor|vampire|hunter|warlock|necromancer|conjurer|mage|cultist|silverhand|reaver|smuggler|pirate|warrior|dremora|boss/i;
  const ANIMAL = /wolf|bear|skeever|spider|chaurus|troll|sabre|mudcrab|horker|slaughterfish|deer|elk|goat|fox|hare|dog|mammoth|giant|atronach|wisp|spriggan|hagraven|sphere|centurion|ballista|ghost|dragon|frostbite|netch|riekling|ashhopper|ogre|minotaur|dreugh|gargoyle|werewolf|werebear|ashspawn|lurker|seeker|scamp|clannfear|daedroth|dragonpriest|horse|cow|chicken/i;
  const CASTER = /mage|wizard|sorcerer|warlock|necromancer|conjurer|witch|priest|cultist|shaman/i;
  const BAD_WEAPON = /dun|Favor|^FF|LD_|NPC$|Trap|^FX|Unarmed|POI|Freeform|DragonPriest|Giant|Lurker|Riekling|Nightingale|^MG|^T0|^C0|SSD|weapBasic|BYOH|Skyforge|Bound|Projectile|dlc2DB|Wrathman|Keeper|Ysgramor|Horksbane|Longhammer|Relic|Illusion|Pickaxe|Catapult|Ballista|Sphere|Knife|Fork|Scimitar|Executioner|Katana|Akaviri|Prelate|Aetherium|Dawnguard|^Axe01|Cross[Bb]ow|Stalhrim|Dragonbone|Daedric|Wooden|Follower|Imperial|Silver|NordHero|Honed|Supple|Enhanced|^MFD/;
  const GEAR_BY_DIFF = { story: 60, normal: 110, hard: 300, nightmare: 1000 };   // 60: IronGreatsword is 50, so story 45 left Novice two-handers empty
  const weaponFor = (edid, diffId, lease) => {
    const e = String(edid || '');
    // A draugr carries draugr steel and a goblin carries goblin iron wherever they stand, so a faction's OWN
    // gear bypasses the province test - but nothing else does. Filtering `all` here rather than inside the
    // else-branch is what stops DLC2Nordic* reaching a Bruma NPC when the faction filter comes back empty.
    const faction = /draugr/i.test(e) ? /^(?:Ench)?Draugr/ : /falmer/i.test(e) ? /^Falmer/
      : /forsworn/i.test(e) ? /^Forsworn/ : /goblin/i.test(e) ? /^BSKGoblin/ : null;
    const base = lootOk(lease);
    const ok = (w) => base(w) || (faction && faction.test(w.name));
    let all = (LOOT.weapons || []).filter((w) => !BAD_WEAPON.test(w.name) && ok(w));
    const shape = /missile|archer|bow|ranger|hunter/i.test(e) ? /Bow$/
      : /2h|twohand|greatsword|battleaxe|warhammer/i.test(e) ? /(Greatsword|Battleaxe|Warhammer)$/
      : CASTER.test(e) ? /Dagger$/ : /(Sword|WarAxe|Mace)$/;
    let pool = all.filter((w) => shape.test(w.name));
    if (faction) { const f = pool.filter((w) => faction.test(w.name)); if (f.length) pool = f; }
    else pool = pool.filter((w) => !/^(Draugr|Falmer|Forsworn|BSKGoblin)/.test(w.name) && Number(w.value) <= (GEAR_BY_DIFF[diffId] || 110));
    if (!pool.length) pool = all.filter((w) => /^(IronSword|IronWarAxe|IronMace)$/.test(w.name));
    return pickFrom(pool);
  };
  const arrowFor = (bowName, lease) => {
    const ok = lootOk(lease);
    const arrows = (LOOT.arrows || []).filter((a) => /Arrow/.test(a.name) && ok(a) && !/Trap|Dummy|Bound|Fire|Ice|Shock|dun|MQ|DLC|Nightingale|Projectile/.test(a.name));
    const mat = String(bowName || '').replace(/^(?:CYR|BSK)/, '').match(/^(Draugr|Falmer|Forsworn|Orcish|Dwarven|Elven|Glass|Ebony|Ayleid|AncientImperial)/);
    return (mat && arrows.find((a) => a.name.replace(/^(?:CYR|BSK)/, '').startsWith(mat[1]))) || arrows.find((a) => a.name === 'IronArrow') || arrows[0] || null;
  };
  const armLease = (lease, ids = readSpawnedIds()) => {
    if (!lease.armed) lease.armed = new Set();
    if (!ids) return;
    const prefix = `${ZONE_PREFIX}${lease.id}:`;
    for (const id of ids) {
      if (lease.armed.has(id)) continue;
      const tag = spawnerTag(lease, id);
      if (!tag.startsWith(prefix)) continue;
      lease.armed.add(id);
      const edid = (lease.kinds || {})[tag] || '';
      if (!HUMANOID.test(edid) || ANIMAL.test(edid)) continue;
      let recEdid = '';
      try {
        const baseDesc = String(mp.get(id, 'baseDesc') || '');
        if (baseDesc) {
          const rec = mp.lookupEspmRecordById(mp.getIdFromDesc(baseDesc));
          if (rec && rec.record && rec.record.editorId) recEdid = String(rec.record.editorId);
        }
      } catch (e) { }
      if (recEdid && (ANIMAL.test(recEdid) || !HUMANOID.test(recEdid))) continue;
      let entries = []; try { const inv = mp.get(id, 'inventory'); entries = inv && Array.isArray(inv.entries) ? inv.entries.slice() : []; } catch (e) { continue; }
      if (entries.some((en) => { const r = recordOf(Number(en.baseId) >>> 0); return r && String(r.type) === 'WEAP'; })) continue;
      // the spawned record's own editor id names its weapon shape (EncBandit03Boss2HNordM); a pool kind like bandit_boss does not
      const w = weaponFor(recEdid ? `${recEdid} ${edid}` : edid, lease.difficulty, lease); if (!w) continue;
      const wid = idOf(w.id); if (!wid) continue;
      entries.push({ baseId: wid, count: 1 });
      let arrowId = 0;
      if (/Bow$/.test(w.name)) { const ar = arrowFor(w.name, lease); arrowId = ar ? idOf(ar.id) : 0; if (arrowId) entries.push({ baseId: arrowId, count: 30 }); }
      try {
        // The weapon goes into the inventory and stops there. Papyrus EquipItem used to follow, and it
        // reached nobody: SpSnippet::Execute returns without sending for any actor that is not
        // "created as player" (formId >= 0xff000000 AND baseId <= 7, MpActor.cpp), which a spawned
        // NPC never is. Measured 2026-09-19 on the isolated probe server: the call changed neither the
        // server's equipment change form nor anything on the wire, while the same call on a player
        // produced an SpSnippet. The one server function that turns inventory into worn equipment and
        // tells every client (MpActor::EquipBestWeapon -> UpdateEquipmentMessage) runs at actor Init,
        // before this, and on each host (re)grant, so the weapon shows up when a client takes over -
        // and that same path currently segfaults the server (see CHECKLIST, C++ task).
        mp.set(id, 'inventory', { entries });
        log(`dungeon ${lease.id}: armed ${edid} ${id.toString(16)} with ${w.name} (inventory; worn on the next host grant)`);
      } catch (e) { log('arm failed', id.toString(16), e.message); }
    }
  };
  // ---- placement factions ----------------------------------------------------------------------
  // A placement is spawned as the concrete NPC_ its leveled list resolves to, so factions its own Lvl*
  // template supplies (Use Factions unset) never reach the actor. The boot audit counts them, factionCheck hands them to the client.
  const TEMPLATE_USE_FACTIONS = 0x04;
  const espmOf = (id) => { try { const r = id ? mp.lookupEspmRecordById(id >>> 0) : null; return r && r.record ? r : null; } catch (e) { return null; } };
  const fieldsOf = (res, type) => (res.record.fields || []).filter((f) => f && f.type === type && f.data instanceof Uint8Array);
  const viewOf = (data) => new DataView(data.buffer, data.byteOffset, data.byteLength);
  const globalIdAt = (res, data) => { try { return res.toGlobalRecordId(viewOf(data).getUint32(0, true)) >>> 0; } catch (e) { return 0; } };
  const edidOf = (id) => { const r = espmOf(id); return (r && String(r.record.editorId || '')) || (id >>> 0).toString(16); };
  const sourceCache = new Map();
  // The NPC_ whose own faction list an actor of this base gets; null when a leveled pick supplies it
  const factionSource = (baseId) => {
    if (sourceCache.has(baseId)) return sourceCache.get(baseId);
    let found = null;
    for (let id = baseId >>> 0, depth = 0; id && depth < 8; depth++) {
      const res = espmOf(id);
      if (!res || String(res.record.type) !== 'NPC_') break;
      const acbs = fieldsOf(res, 'ACBS')[0];
      const tflags = acbs && acbs.data.byteLength >= 20 ? viewOf(acbs.data).getUint16(18, true) : 0;
      const tplt = fieldsOf(res, 'TPLT')[0];
      const next = tplt ? globalIdAt(res, tplt.data) : 0;
      if (!next || !(tflags & TEMPLATE_USE_FACTIONS)) {
        const crif = fieldsOf(res, 'CRIF')[0];
        const factions = fieldsOf(res, 'SNAM').filter((f) => f.data.byteLength >= 5).map((f) => ({ id: globalIdAt(res, f.data), rank: viewOf(f.data).getInt8(4) }));
        found = { id, factions, crime: crif ? globalIdAt(res, crif.data) : 0 };
        break;
      }
      id = next;
    }
    sourceCache.set(baseId, found);
    return found;
  };
  const placedBase = (refDesc) => { const res = espmOf(idOf(refDesc)); const name = res && String(res.record.type) === 'ACHR' ? fieldsOf(res, 'NAME')[0] : null; return name ? globalIdAt(res, name.data) : 0; };
  const factionKey = (src) => src ? src.factions.map((f) => `${f.id}:${f.rank}`).sort().join(',') + `|${src.crime}` : '';
  const factionNames = (src) => src ? src.factions.map((f) => edidOf(f.id)).sort().concat(src.crime ? [`crime ${edidOf(src.crime)}`] : []).join(', ') || 'none' : 'from leveled pick';
  // Factions the placement's own template gives that the spawned base does not, or null when they agree
  const factionLoss = (placementBase, spawnedBase) => {
    const want = factionSource(placementBase);
    if (!want) return null;
    const got = factionSource(spawnedBase);
    return got && got.id === want.id ? null : factionKey(want) === factionKey(got) ? null : { want, got };
  };
  if (!globalThis.__dboFactionAudited) {
    globalThis.__dboFactionAudited = true;
    const t0 = Date.now();
    let slots = 0, lost = 0;
    const byPlacement = new Map();
    for (const d of DATA.dungeons || []) for (const z of d.zones || []) for (const npc of z.npcs || []) {
      const opt = (npc.options || [])[0];
      if (!npc.ref || !opt) continue;
      slots++;
      const loss = factionLoss(placedBase(npc.ref), idOf(opt[1]));
      if (!loss) continue;
      lost++;
      const k = `${npc.edid} [${factionNames(loss.want)}] spawned as ${edidOf(idOf(opt[1]))} [${factionNames(loss.got)}]`;
      byPlacement.set(k, (byPlacement.get(k) || 0) + 1);
    }
    const top = [...byPlacement.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([k, n]) => `${n}x ${k}`);
    log(`dungeon faction audit: ${lost} of ${slots} placements spawn without their template's factions (${byPlacement.size} kinds, ${Date.now() - t0} ms); top: ${top.join(' | ')}`);
  }
  // A spawned actor whose placement template gives other factions carries them in ff_factions; the client applies them (formView.applyFactions)
  const factionCheck = (lease) => {
    if (!lease.factionChecked) { lease.factionChecked = new Set(); lease.factionPairs = new Set(); }
    for (const id of lease.armed || []) {
      if (lease.factionChecked.has(id)) continue;
      lease.factionChecked.add(id);
      const tag = spawnerTag(lease, id);
      let baseDesc = ''; try { baseDesc = String(mp.get(id, 'baseDesc') || ''); } catch (e) { continue; }
      const zone = (lease.zones || []).find((z) => z.Name === tag);
      const pBase = zone && zone.Anchor ? placedBase(zone.Anchor) : 0;
      const sBase = idOf(baseDesc);
      const loss = pBase ? factionLoss(pBase, sBase) : null;
      if (!loss) continue;
      try { mp.set(id, 'ff_factions', { f: loss.want.factions.map((x) => [x.id, x.rank]), c: loss.want.crime }); } catch (e) { log('ff_factions set failed', id.toString(16), e.message); continue; }
      const pair = `${pBase}>${sBase}`;
      if (lease.factionPairs.has(pair)) continue;
      lease.factionPairs.add(pair);
      log(`dungeon ${lease.id} factions: ${edidOf(pBase)} (${zone.Kind}) spawned as ${edidOf(sBase)} [${factionNames(loss.got)}], given [${factionNames(loss.want)}]`);
    }
  };
  every('dungeons.arm', 2000, () => {
    const ids = ST.leases.size ? readSpawnedIds() : null;
    for (const lease of ST.leases.values()) { try { armLease(lease, ids); factionCheck(lease); } catch (e) { log('arm tick failed', e.message); } }
  });

  // ---- doors and chests -------------------------------------------------------------------------
  const denyAt = new Map();
  const deny = (a, text) => { if (Date.now() - (denyAt.get(a) || 0) > 1500) { denyAt.set(a, Date.now()); personal(a, text); } return false; };
  const lockpickingTier = (a) => { try { const r = mp.get(a, 'private.mastery'); if (!r || !Array.isArray(r.order) || !r.order.includes('lockpicking')) return -1; return Math.max(0, Number((r.skills && r.skills.lockpicking || {}).rank) || 0); } catch (e) { return -1; } };
  const takeLockpick = (a) => {
    try {
      const inv = mp.get(a, 'inventory') || { entries: [] };
      const entries = Array.isArray(inv.entries) ? inv.entries.map((e) => Object.assign({}, e)) : [];
      const hit = entries.find((e) => e && (Number(e.baseId) >>> 0) === LOCKPICK_BASE && Number(e.count) > 0);
      if (!hit) return false;
      hit.count -= 1;
      mp.set(a, 'inventory', { entries: entries.filter((e) => Number(e.count) > 0) });
      return true;
    } catch (e) { return false; }
  };
  // ---- logging out inside a dungeon ------------------------------------------------------------
  // A character left standing in an interior logs back in inside it, which means inside somebody
  // else's claim or inside one that has since reset with its enemies gone. On disconnect they are
  // put back outside the entrance; on login anyone found inside without a live claim of their own
  // is put out as well, which also covers a lease that ended or a restart while they were away.
  const leaseHolding = (a) => { const pid = profileOf(a); for (const l of ST.leases.values()) if (l.members.has(pid)) return l; return null; };
  const outsideSpot = (d, entrance) => {
    const e = entrance && Array.isArray(entrance.pos) ? entrance : (d.entrances || []).find((x) => Array.isArray(x.pos));
    return e || null;
  };
  globalThis.__dboDungeonLeave = (a) => {
    if (!C.enabled) return false;
    try {
      const d = dungeonAround(a); if (!d) return false;
      const lease = leaseHolding(a);
      const e = outsideSpot(d, lease && lease.id === d.id ? lease.entrance : null);
      if (!e) { log(`${display(a)} logged out inside ${d.name}, which has no entrance spot to put them out of`); return false; }
      if (!teleport(a, e.world || e.cell, e.pos, e.rot)) return false;
      log(`${display(a)} logged out inside ${d.name}; moved out to the entrance`);
      return true;
    } catch (err) { log('dungeon logout move failed', err.message); return false; }
  };
  globalThis.__dboDungeonLoginCheck = (a) => {
    if (!C.enabled) return false;
    try {
      const d = dungeonAround(a); if (!d) return false;
      const lease = leaseHolding(a);
      if (lease && lease.id === d.id) return false;    // their own claim still runs; they may stay
      const e = outsideSpot(d, null); if (!e) return false;
      if (!teleport(a, e.world || e.cell, e.pos, e.rot)) return false;
      system(a, `${d.name} is claimed anew or rested since you left. You wake at its entrance.`);
      log(`${display(a)} logged in inside ${d.name} without a claim; moved out to the entrance`);
      return true;
    } catch (err) { log('dungeon login check failed', err.message); return false; }
  };
  // Returns false to block the activation, true to let it through, null when it is not ours.
  globalThis.__dboDungeonActivate = (targetId, casterId) => {
    if (!C.enabled) return null;
    const inside = insideDoors.get(targetId);
    if (inside) return true; // leaving is always allowed
    const out = outsideDoors.get(targetId);
    if (out) {
      const { d, entrance } = out;
      const pid = profileOf(casterId);
      const lease = ST.leases.get(d.id);
      if (lease) {
        if (lease.members.has(pid)) { glowLease(casterId, lease, d); return true; }
        return deny(casterId, `Someone is inside ${d.name}. It frees up in ${minutesLeft(lease.endsAt)} minutes at most.`);
      }
      const cd = Number(cooldownsOf(casterId)[d.id]) || 0;
      if (cd > Date.now()) return deny(casterId, `${d.name} still rests for you. Come back in ${minutesLeft(cd)} minutes.`);
      const party = partyOf(pid);
      if (party && party.leader !== pid) return deny(casterId, `Only your party leader, ${party.leaderName}, can claim ${d.name}.`);
      const nonce = `${casterId.toString(16)}-${Date.now().toString(36)}`;
      ST.pending.set(casterId, { nonce, dungeonId: d.id, entrance });
      const partyNames = partyMembers(pid).filter((x) => x !== pid).map((x) => { const a = actorByProfile(x); return a ? nameOf(a) : `#${x}`; });
      openWidget(casterId, { type: 'dungeonGate', id: GATE_WIDGET_ID, nonce, name: d.name, kind: TYPE_NAMES[d.type] || 'Dungeon', party: partyNames, difficulties: DIFFICULTIES.map((x) => ({ id: x.id, label: x.label, blurb: x.blurb })), minutes: C.leaseMinutes, cooldownMinutes: C.cooldownMinutes, canClaim: true }, true);
      return false;
    }
    const chest = chestRefs.get(targetId);
    if (chest) {
      const lease = ST.leases.get(chest.d.id);
      // No lease left: the glow is a leftover, so stop it on this ref rather than leaving it lit
      if (!lease) { glowOff(casterId, [targetId]); return null; }
      const opened = () => { if (!lease.looted.has(targetId)) { lease.looted.add(targetId); for (const pid of lease.members) { const a = actorByProfile(pid); if (a) glow(a, [targetId], false); } } };
      if (!lease.locked.has(targetId) || lease.unlocked.has(targetId)) { opened(); return null; }
      const level = lease.locked.get(targetId);
      const tier = lockpickingTier(casterId);
      if (tier < 0) return deny(casterId, `The chest is locked (${LOCK_LEVELS[level]}). Only a Lockpicker can open it.`);
      if (tier < level) return deny(casterId, `The chest is locked (${LOCK_LEVELS[level]}). Your Lockpicking is not yet up to it (tier ${level + 1} needed).`);
      const chance = Math.min(0.95, 0.55 + 0.15 * (tier - level));
      if (Math.random() < chance) {
        lease.unlocked.add(targetId);
        for (const pid of lease.members) { const m = actorByProfile(pid); if (m) { glow(m, [targetId], false, 'locked'); glow(m, [targetId], true, 'loot'); } }
        system(casterId, `The ${LOCK_LEVELS[level]} lock gives way.`);
        try { if (typeof globalThis.__alduinakMasteryEvent === 'function') globalThis.__alduinakMasteryEvent('lock', casterId, { refrId: targetId, level }); } catch (e) { /* no skill system */ }
        opened();
        return true;
      }
      if (takeLockpick(casterId)) return deny(casterId, `The pick snaps in the ${LOCK_LEVELS[level]} lock.`);
      return deny(casterId, `You have no lockpicks left for this ${LOCK_LEVELS[level]} lock.`);
    }
    return null;
  };
  onUi('dungeonClaim', (a, args) => {
    const p = ST.pending.get(a); if (!p || String(args[0]) !== p.nonce) return;
    ST.pending.delete(a); closeWidget(a, GATE_WIDGET_ID);
    const d = byId.get(p.dungeonId); const diff = DIFFICULTIES.find((x) => x.id === String(args[1]));
    if (!d || !diff) return;
    if (ST.leases.has(d.id)) return personal(a, `Someone claimed ${d.name} first.`);
    if (distance(a, p.entrance.doorPos || p.entrance.pos, p.entrance.world || p.entrance.cell) > C.entranceReach) return personal(a, 'You have wandered from the entrance.');
    startLease(a, d, p.entrance, diff);
  });
  onUi('dungeonCancel', (a) => { ST.pending.delete(a); closeWidget(a, GATE_WIDGET_ID); });
  onUi('close', (a, args, widgetId) => { if (widgetId === GATE_WIDGET_ID) ST.pending.delete(a); });

  // ---- corpses: a body yields loot, not a full kit ------------------------------------------------
  const recordOf = (baseId) => { try { const r = mp.lookupEspmRecordById(baseId >>> 0); return r && r.record ? r.record : null; } catch (e) { return null; } };
  const isEnchanted = (rec) => !!(rec && Array.isArray(rec.fields) && rec.fields.some((f) => f.type === 'EITM'));
  globalThis.__dboTrimCorpse = (actorId) => {
    if (actorId < 0xff000000) return;
    let tag = ''; try { tag = String(mp.get(actorId, 'private.npcSpawner') || ''); } catch (e) { return; }
    if (!tag.startsWith(ZONE_PREFIX)) return;
    const diffId = (() => { const l = [...ST.leases.values()].find((x) => tag.startsWith(`${ZONE_PREFIX}${x.id}:`)); return l ? l.difficulty : 'normal'; })();
    const diff = DIFFICULTIES.find((x) => x.id === diffId) || DIFFICULTIES[1];
    // Humanoids are looted with E (__dboCorpseLoot), so their body keeps nothing
    if (isHumanoidTag(tag)) { try { mp.set(actorId, 'inventory', { entries: [] }); } catch (e) { log('corpse clear failed', e.message); } return; }
    let inv = null; try { inv = mp.get(actorId, 'inventory'); } catch (e) { return; }
    const entries = inv && Array.isArray(inv.entries) ? inv.entries : [];
    const kept = [];
    let weaponKept = false;
    for (const e of entries) {
      const baseId = Number(e.baseId) >>> 0; const rec = recordOf(baseId); const type = rec ? String(rec.type) : '';
      const count = Number(e.count) || 0;
      if (baseId === GOLD_BASE) { kept.push({ baseId, count: Math.min(count, diff.gold[1]) }); continue; }
      if (type === 'AMMO') { kept.push({ baseId, count: Math.min(count, 15) }); continue; }
      if (type === 'ALCH' || type === 'INGR' || type === 'MISC' || type === 'SLGM' || type === 'KEYM' || type === 'BOOK' || type === 'SCRL') { kept.push({ baseId, count }); continue; }
      if (type === 'WEAP') { if (!weaponKept && Math.random() < (isEnchanted(rec) ? diff.ench * 3 : 0.25)) { weaponKept = true; kept.push({ baseId, count: 1 }); } continue; }
      if (type === 'ARMO') { if (Math.random() < (isEnchanted(rec) ? diff.ench * 2 : 0.1)) kept.push({ baseId, count: 1 }); continue; }
      // anything else (spells, leveled leftovers): drop
    }
    try { mp.set(actorId, 'inventory', { entries: kept }); } catch (e) { log('corpse trim failed', e.message); }
  };

  // ---- shared gold: coin found in a lease is split across the party inside ------------------------
  // Hands the other members inside their shares and returns what the finder keeps.
  const splitGold = (finder, lease, count) => {
    if (!lease) return count;
    const inside = [...lease.members].map((pid) => actorByProfile(pid)).filter((m) => m && (m === finder || (dungeonAround(m) || {}).id === lease.id));
    if (inside.length < 2) return count;
    const share = Math.floor(count / inside.length); if (share < 1) return count;
    let handed = 0;
    for (const m of inside) { if (m === finder) continue; if (giveItem(m, GOLD_BASE, share)) { handed += share; personal(m, `${nameOf(finder)} found ${count} gold; your share is ${share}.`); } }
    return count - handed;
  };
  globalThis.__dboTakeItem = (sourceId, actorId, baseId, count) => {
    if ((baseId >>> 0) !== GOLD_BASE || count <= 0) return;
    const lease = leaseOfActor(actorId); if (!lease) return;
    const here = dungeonAround(actorId); if (!here || here.id !== lease.id) return;
    const d = byId.get(lease.id); if (!d) return;
    if (!chestRefs.has(sourceId >>> 0)) return;
    const handed = count - splitGold(actorId, lease, count);
    if (!handed) return;
    // Take the shares back from the finder (they already hold the whole pile).
    try {
      const inv = mp.get(actorId, 'inventory') || { entries: [] };
      const entries = Array.isArray(inv.entries) ? inv.entries.map((e) => Object.assign({}, e)) : [];
      let left = handed;
      for (const e of entries) { if ((Number(e.baseId) >>> 0) !== GOLD_BASE || left <= 0) continue; const take = Math.min(Number(e.count) || 0, left); e.count -= take; left -= take; }
      mp.set(actorId, 'inventory', { entries: entries.filter((e) => Number(e.count) > 0) });
      personal(actorId, `${count} gold, shared with your party: you keep ${count - handed}.`);
    } catch (e) { log('gold split failed', e.message); }
  };

  // ---- humanoid bodies: E hands over a small roll, once per body -----------------------------------
  const leaseOfTag = (tag) => [...ST.leases.values()].find((x) => tag.startsWith(`${ZONE_PREFIX}${x.id}:`)) || null;
  function isHumanoidTag(tag) { const l = leaseOfTag(tag); const kind = l && l.kinds ? l.kinds[tag] || '' : ''; return HUMANOID.test(kind) && !ANIMAL.test(kind); }
  const itemName = (baseId) => { const r = recordOf(baseId); return String((r && r.editorId) || 'something').replace(/^(Food|Potion)/, '').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/\d+$/, '').trim() || 'something'; };
  const corpseLoot = (diff, ok = ALL_OK) => {
    const entries = [];
    addEntry(entries, { id: 'f:Skyrim.esm' }, Math.max(1, rnd(diff.gold[0], diff.gold[1])));
    if (Math.random() < 0.6) addEntry(entries, pickFrom(pool('food', 0, ok)), 1);
    if (Math.random() < 0.25) addEntry(entries, pickFrom(potionPool(diff.potionTier, ok)), 1);
    if (Math.random() < 0.2) addEntry(entries, pickFrom(pool('ingredients', 0, ok)), rnd(1, 2));
    return entries;
  };
  // false = handled (nothing opens), null = not a lease humanoid
  globalThis.__dboCorpseLoot = (targetId, casterId) => {
    if (targetId < 0xff000000) return null;
    let tag = ''; try { tag = String(mp.get(targetId, 'private.npcSpawner') || ''); } catch (e) { return null; }
    if (!tag.startsWith(ZONE_PREFIX) || !isHumanoidTag(tag)) return null;
    try { if (mp.get(targetId, 'isDead') !== true) return null; } catch (e) { return null; }
    let looted = false; try { looted = mp.get(targetId, 'private.dboLooted') === true; } catch (e) { /* fresh */ }
    if (looted) return deny(casterId, 'Nothing more to find on this one.');
    try { mp.set(targetId, 'private.dboLooted', true); } catch (e) { return false; }
    const lease = leaseOfTag(tag);
    const diff = DIFFICULTIES.find((x) => x.id === (lease ? lease.difficulty : 'normal')) || DIFFICULTIES[1];
    const got = [];
    for (const en of corpseLoot(diff, lootOk(lease))) {
      if (en.baseId === GOLD_BASE) { const kept = splitGold(casterId, lease, en.count); if (kept > 0 && giveItem(casterId, GOLD_BASE, kept)) got.push(`${en.count} gold${kept < en.count ? ' (shared)' : ''}`); continue; }
      if (giveItem(casterId, en.baseId, en.count)) got.push(`${en.count > 1 ? en.count + ' ' : ''}${itemName(en.baseId)}`);
    }
    personal(casterId, got.length ? `You find ${got.join(', ')}.` : 'You find nothing of use.');
    return false;
  };

  // ---- party -----------------------------------------------------------------------------------
  const pushParty = (p) => {
    const members = p ? [...p.members].map((m) => { const x = actorByProfile(m); return x ? { id: x, name: nameOf(x), leader: m === p.leader } : null; }).filter(Boolean) : [];
    if (p) for (const m of p.members) { const x = actorByProfile(m); if (x && globalThis.__dboSetParty) globalThis.__dboSetParty(x, members); }
  };
  const clearPartyPanel = (pid) => { const x = actorByProfile(pid); if (x && globalThis.__dboSetParty) globalThis.__dboSetParty(x, []); };
  const leaveParty = (pid, quiet) => {
    const leader = ST.memberOf.get(pid); if (leader === undefined) return;
    const p = ST.parties.get(leader);
    ST.memberOf.delete(pid);
    if (!p) return;
    p.members.delete(pid);
    clearPartyPanel(pid);
    if (leader === pid || p.members.size <= 1) {
      for (const m of p.members) { ST.memberOf.delete(m); clearPartyPanel(m); const a = actorByProfile(m); if (a && !quiet) system(a, 'The party has broken up.'); }
      ST.parties.delete(leader);
    } else if (!quiet) {
      pushParty(p);
      const name = (() => { const a = actorByProfile(pid); return a ? display(a) : `#${pid}`; })();
      for (const m of p.members) { const a = actorByProfile(m); if (a) system(a, `${name} left the party.`); }
    }
  };
  registerChatCommand('party', (a, args) => {
    const [sub, ...rest] = args.trim().split(/\s+/); const arg = rest.join(' ');
    const pid = profileOf(a);
    const p = partyOf(pid);
    switch ((sub || '').toLowerCase()) {
      case 'invite': {
        const t = findByName(arg); if (!t) return personal(a, 'No such player. /party invite <name|#TAG>');
        if (t === a) return personal(a, 'You are already with yourself.');
        if (p && p.leader !== pid) return personal(a, 'Only the party leader invites.');
        if (p && p.members.size >= C.partyMax) return personal(a, `A party holds ${C.partyMax}.`);
        if (partyOf(profileOf(t))) return personal(a, `${display(t)} is already in a party.`);
        ST.invites.set(profileOf(t), { from: pid, at: Date.now() });
        personal(a, `Invited ${display(t)}. They have two minutes to /party accept.`);
        system(t, `${display(a)} invites you to their party. /party accept to join, /party decline to refuse.`);
        return;
      }
      case 'accept': {
        const inv = ST.invites.get(pid); if (!inv || Date.now() - inv.at > 120000) return personal(a, 'No open invitation.');
        ST.invites.delete(pid);
        if (partyOf(pid)) return personal(a, 'Leave your party first.');
        let lp = ST.parties.get(inv.from);
        const leaderActor = actorByProfile(inv.from); if (!leaderActor) return personal(a, 'They are gone.');
        if (!lp) { lp = { leader: inv.from, leaderName: display(leaderActor), members: new Set([inv.from]) }; ST.parties.set(inv.from, lp); ST.memberOf.set(inv.from, inv.from); }
        if (lp.members.size >= C.partyMax) return personal(a, 'That party is full.');
        lp.members.add(pid); ST.memberOf.set(pid, inv.from);
        for (const m of lp.members) { const x = actorByProfile(m); if (x) system(x, `${display(a)} joined the party (${lp.members.size}/${C.partyMax}).`); }
        pushParty(lp);
        return;
      }
      case 'decline': ST.invites.delete(pid); return personal(a, 'Declined.');
      case 'leave': if (!p) return personal(a, 'You are not in a party.'); leaveParty(pid); return personal(a, 'You left the party.');
      case 'kick': {
        if (!p || p.leader !== pid) return personal(a, 'Only the leader kicks.');
        const t = findByName(arg); if (!t || !p.members.has(profileOf(t))) return personal(a, 'They are not in your party.');
        leaveParty(profileOf(t)); system(t, 'You were removed from the party.'); return personal(a, `${display(t)} removed.`);
      }
      default: {
        if (!p) return personal(a, 'Not in a party. /party invite <name|#TAG>, /party accept, /party leave, /party kick <name>.');
        const names = [...p.members].map((m) => { const x = actorByProfile(m); return (x ? display(x) : `#${m}`) + (m === p.leader ? ' (leader)' : ''); });
        return personal(a, `Party (${p.members.size}/${C.partyMax}): ${names.join(', ')}`);
      }
    }
  }, { help: 'invite|accept|decline|leave|kick: group up for dungeons' });
  registerChatCommand('dungeon', (a, args) => {
    const sub = args.trim().toLowerCase();
    if (sub.startsWith('end ') && isAdmin(a)) {
      const q = sub.slice(4).trim(); const lease = [...ST.leases.values()].find((l) => l.id.toLowerCase() === q || l.name.toLowerCase() === q);
      if (!lease) return personal(a, 'No such lease.');
      endLease(lease, 'admin'); audit(`GM ${who(a)} ended the lease on ${lease.name}`); return personal(a, `Ended ${lease.name}.`);
    }
    const here = dungeonAround(a);
    const lines = [];
    if (here) {
      const l = ST.leases.get(here.id);
      if (l) { trackNpcs(l); lines.push(`${here.name}: claimed by ${l.leader === profileOf(a) ? 'you' : 'someone'} on ${l.difficulty}, ${minutesLeft(l.endsAt)} min left. Enemies ${l.deadNpcs.size}/${l.totalNpcs} down, big chests ${here.bigChestIds.filter((id) => l.looted.has(id)).length}/${here.bigChestIds.length} opened (${l.looted.size}/${here.chestIds.length} containers), ${l.locked.size - l.unlocked.size} still locked.`); }
      else lines.push(`${here.name}: not claimed. Enter through the door to claim it.`);
    }
    const active = [...ST.leases.values()]; if (active.length) lines.push('Claimed now: ' + active.map((l) => `${l.name} (${minutesLeft(l.endsAt)} min)`).join(', '));
    const cd = cooldownsOf(a); const resting = Object.keys(cd).filter((k) => Number(cd[k]) > Date.now()).map((k) => `${(byId.get(k) || { name: k }).name} ${minutesLeft(cd[k])} min`);
    if (resting.length) lines.push('Resting for you: ' + resting.join(', '));
    personal(a, lines.length ? lines.join('  |  ') : `${byId.size} dungeons run as one-hour claims. Walk up to an entrance to claim one.${isAdmin(a) ? ' Admin: /dungeon end <name>.' : ''}`);
  }, { help: 'dungeon claims: what is taken, what rests for you' });

  // After a reload every party gets its panel again.
  for (const p of ST.parties.values()) pushParty(p);

  // Boot: no lease survives a restart, so nothing of ours should be in the spawn file.
  if (!globalThis.__dboDungeonsBooted) { globalThis.__dboDungeonsBooted = true; ST.leases.clear(); writeSpawnZones(); }
  log(`dungeons ${C.enabled ? 'on' : 'off'}: ${byId.size} dungeons, ${outsideDoors.size} entrances, ${chestRefs.size} lootable chests, loot pools ${Object.keys(LOOT).map((k) => `${k} ${LOOT[k].length}`).join(', ')}, ${C.leaseMinutes} min lease, ${C.cooldownMinutes} min rest, ${ST.leases.size} active`);
};
