// Shrines, deities and prayer, loaded by gamemode.js like labour.js and dungeons.js.
// A shrine belongs to a deity; a character belongs to one deity at a time and may only pray at
// their own. Praying is a mini-game: the server issues three verses and the worshipper holds the
// prayer key through all three. A completed prayer credits the Priest skill and rolls, rarely, for
// the shrine's blessing.
//
// The round is the server's, exactly as in labour.js and the reading game (SERVER_AUTHORITY.md
// migration 7). The server rolls the verses and their windows and sends them; the widget renders
// them and reports WHEN the key was down, never whether the prayer held. The server replays the
// windows against those spans and decides for itself, so editing the widget changes what the
// worshipper sees and not what the gods give.
//
//   Browser -> client -> server: sendMessage('dbo:prayer', nonce, JSON.stringify(spans), atMs[, verdict])
//   First press (startOnPress):  sendMessage('dbo:prayerStart', nonce[, waitMs])
//   Escape / stand up:           sendMessage('dbo:prayerCancel', nonce)
//
// Client-judged (Jake, 2026-09-30: lag refused 7 of 31 perfect holds as "late"; minigames.js, DESIGN.md section 4.4):
// the round tells a new widget `judge: 'client'`, the widget decides held or not on its own clock and adds its verdict,
// '{"v":1,"win":true,"why":"","worst":0,"durMs":18000,"waitMs":900,"blurs":0}'. The server replays the spans for the
// audit and never measures how late a packet came: no "future", no "late", no 60 s wait on its clock. It keeps the
// nonce, one report, the shape of the spans, the worshipper still at the shrine (12 m), a round no shorter than its
// verses (by the widget's clock, and by the server's counted from when it SENT the round), the rests and the gods' gifts.
// An old widget (no verdict) is judged from its spans as before, without the two lag checks. prayer.clientJudged false
// in gamemode-config.json puts back today's judging.
//
// Data: skills.json `deities` (the choices, their shrine BASE ids and blessing spells) and `praying`
// (odds, durations, cooldown, the verse count). Shrine ids are base objects, never references: one
// deity has many statues. Which of them a player can actually reach is measured, not assumed -
// server\shrine-placements.json, regenerated by `py ck-mcp\shrines.py`.
'use strict';

module.exports = (api) => {
  const { mp, log, personal, audit, display, who, cfg, openWidget, closeWidget, onUi, registerChatCommand, skills, every, takeGold, treasuryHere,
    isLeadStaff, findAnyByName, sendPacket, distanceMeters } = api;
  // The shared rules for client-judged mini-games, beside this file (reloaded with it)
  const path = require('path');
  const MINIGAMES_JS = path.join(__dirname, 'minigames.js');
  delete require.cache[MINIGAMES_JS];
  const MG = require(MINIGAMES_JS);

  const WIDGET_ID = 35;
  const CFG = Object.assign({
    enabled: true,
    // How long the whole prayer runs, and how far the report's clock may drift from the server's.
    // Same reasoning as labour.js: the packet out, the browser mount, the report back.
    lagGraceMs: 2500,
    clockSlackMs: 50,
    // Uncovered milliseconds a single verse forgives. A prayer is a hold, not a rhythm test, so
    // this is generous - it exists to forgive the gap between two key repeats, not a lapse.
    holdSlackMs: 500,
    // A hand must be on the key from the start; dawdling past this is not a prayer. The lead-in before the first press
    // (at most this) is not counted as a gap in the first verse: a reaction, not a lapse.
    startGraceMs: 1500,
    // The round starts at the worshipper's first press (dbo:prayerStart), so the panel's load time and a reaction are
    // never judged (2026-09-29: 31 of 33 prayers had failed, most of them held from first to last). How long the
    // panel waits for that press before the round lapses.
    waitSeconds: 60,
    // A panel that never says when it started (a client from before 2026-09-29) is judged from when the round was
    // sent, and its load time is on the clock: it gets this much lag instead of lagGraceMs.
    legacyLagGraceMs: 6000,
    failRestMinutes: 5,
    // The widget judges the hold on its own clock and the server accepts its verdict (minigames.js). lagGraceMs,
    // clockSlackMs, waitSeconds and legacyLagGraceMs then only flag or tell the widget; false: today's judging exactly.
    clientJudged: true,
    // A round nobody reports is cleaned up this long after its verses could have ended: minutes, never a latency budget
    roundTimeoutMs: 180000,
    // The worshipper must still be this close to the shrine when the report lands (not for a faith prayed anywhere)
    nearMeters: 12,
    // Logged, never refused: a report this far behind the server's clock
    slowFlagMs: 5000,
    // A claimed hold its own spans do not bear out: 'log' lets it stand with a PRAYER-MISMATCH audit line, 'refuse'
    // refuses it (DESIGN.md section 12, item 1)
    replayCheck: 'log',
  }, cfg.prayer || {});
  const clientJudged = () => MG.clientJudged(CFG);

  const PRAY = Object.assign({}, skills.praying || {});
  const DEITIES = (skills.deities || {}).choices || [];
  const CONVERSION_DAYS = Math.max(0, Number((skills.deities || {}).conversionCooldownDays) || 7);
  const VERSES = Math.max(1, Math.round(Number(PRAY.verses) || 3));
  const VERSE_MS = Math.max(1000, Math.round((Number(PRAY.verseSeconds) || 6) * 1000));
  const SLACK_MS = Math.max(0, Math.round(Number(PRAY.holdSlackMs ?? CFG.holdSlackMs)));
  const SHRINE_COOLDOWN_MS = Math.max(0, Math.round((Number(PRAY.cooldownMinutesPerShrine) || 60) * 60000));

  // Rounds outlive a gamemode reload, or every save would strand a prayer in flight
  const sessions = globalThis.__dboPrayerRounds || (globalThis.__dboPrayerRounds = new Map()); // actorId -> round
  const spent = globalThis.__dboPrayerSpent || (globalThis.__dboPrayerSpent = new Map());      // nonce -> when judged
  const lastShrine = globalThis.__dboPrayerLastShrine || (globalThis.__dboPrayerLastShrine = new Map()); // actorId -> { deityId, at }
  const denied = new Map();

  const nowMs = () => performance.now();   // the round clock is monotonic; Date.now() can be stepped
  const idOf = (desc) => { try { return mp.getIdFromDesc(String(desc)) >>> 0; } catch (e) { return 0; } };
  const baseIdOf = (targetId) => { try { return idOf(mp.get(targetId, 'baseDesc')); } catch (e) { return 0; } };
  const baseRecord = (baseId) => { try { return mp.lookupEspmRecordById(baseId); } catch (e) { return null; } };
  const deny = (a, text) => {
    if (Date.now() - (denied.get(a) || 0) > 1500) { denied.set(a, Date.now()); personal(a, text); }
    return true;
  };

  const masteryOf = (a) => { try { const r = mp.get(a, 'private.mastery'); return r && typeof r === 'object' ? r : null; } catch (e) { return null; } };
  // -1 when the character does not hold the skill at all, otherwise the rank as a 0 based tier
  const tierOf = (a, skillId) => {
    const r = masteryOf(a);
    if (!r || !Array.isArray(r.order) || !r.order.includes(skillId)) return -1;
    const p = r.skills && r.skills[skillId];
    return p ? Math.max(0, Number(p.rank) || 0) : 0;
  };

  // ── the shrine index ────────────────────────────────────────────────────────────────────────
  // A shrine in skills.json may be named either way round, and both are deliberate: most deities
  // name the base ACTI, so every statue of that god counts, while the Daedric activators placed on
  // 2026-09-14 name single REFRs on purpose (CHECKLIST: "Meridia uses the vanilla Kilkreath
  // activator 4e4d6"), so one statue counts and its neighbours do not. A form id is one or the
  // other, never both, so indexing every id under both keys costs nothing and cannot collide: a
  // base id will never equal a reference the player touched, and a reference id will never equal
  // the base behind one.
  let SHRINES = null;
  const shrineIndex = () => {
    if (SHRINES) return SHRINES;
    SHRINES = new Map();
    let bad = 0;
    for (const d of DEITIES) {
      for (const s of d.shrines || []) {
        const id = idOf(s);
        if (!id) { bad++; log(`prayer: ${d.name} shrine ${s} does not resolve`); continue; }
        if (SHRINES.has(id)) { log(`prayer: shrine ${s} is claimed by both ${SHRINES.get(id).name} and ${d.name}; ${SHRINES.get(id).name} keeps it`); continue; }
        SHRINES.set(id, d);
      }
    }
    log(`prayer: ${SHRINES.size} shrine id(s) across ${DEITIES.length} deities${bad ? `, ${bad} unresolved` : ''}`);
    return SHRINES;
  };
  // The reference the player touched wins over the base behind it, so a deity that claims one
  // statue is not overruled by a deity that claims every statue of that model.
  const shrineAt = (targetId, baseId) => shrineIndex().get(targetId) || (baseId ? shrineIndex().get(baseId) : null);

  const deityByName = (s) => {
    const q = String(s || '').trim().toLowerCase().replace(/[^a-z]/g, '');
    if (!q) return null;
    return DEITIES.find((d) => d.id === q || d.name.toLowerCase().replace(/[^a-z]/g, '') === q) || null;
  };
  const deityById = (id) => DEITIES.find((d) => d.id === id) || null;
  // Auri-El is not a second god, he is Akatosh under the Aldmeri name, and skills.json says so with
  // `aspectOf`. Two ids are the same faith if either is an aspect of the other, so a worshipper of
  // one may kneel at the other's shrine - which is the only way a Snow-Elf-faithed character gets to
  // pray at all, Auri-El's one shrine being in the Forgotten Vale.
  const sameFaith = (a, b) => {
    if (!a || !b) return false;
    if (a.id === b.id) return true;
    return a.aspectOf === b.id || b.aspectOf === a.id || (!!a.aspectOf && a.aspectOf === b.aspectOf);
  };

  // ── what a character worships ───────────────────────────────────────────────────────────────
  const faithOf = (a) => { try { const r = mp.get(a, 'private.dboDeity'); return r && typeof r === 'object' && r.id ? r : null; } catch (e) { return null; } };
  const setFaith = (a, v) => { try { mp.set(a, 'private.dboDeity', v); } catch (e) { log('prayer: faith save failed', e.message); } };
  const restsOf = (a) => { try { const r = mp.get(a, 'private.prayedShrines'); return r && typeof r === 'object' ? r : {}; } catch (e) { return {}; } };
  const saveRests = (a, rests) => {
    for (const k of Object.keys(rests)) if (Number(rests[k]) < Date.now()) delete rests[k];
    try { mp.set(a, 'private.prayedShrines', rests); } catch (e) { log('prayer: rest save failed', e.message); }
  };

  // ── blessings ───────────────────────────────────────────────────────────────────────────────
  // How a blessing reaches the worshipper depends on its spell record (SPEL SPIT: type u32 at 8, cast type at 16,
  // delivery at 20; libespm SPEL.h SPITData, as combat.js and gamemode.js read it):
  //  - a Spell cast Fire-and-Forget on Self, which is every Divine and Prince blessing: the worshipper's own client
  //    casts it on them (dboCastSelf, castSelfService; the Ayleid well in gamemode.js does the same). That is how the
  //    vanilla shrine gives it too (TempleBlessingScript: TempleBlessing.Cast(akActionRef, akActionRef)). The server's
  //    AddSpell only puts a spell in the learned list, so until 2026-10-01 these worshippers were taught a castable
  //    "Blessing of X" and no effect ever ran.
  //  - an Ability (Trinimac, the Worm Cult): AddSpell, which runs a constant effect for as long as the spell is known,
  //    and RemoveSpell when the blessing ends. The learned list survives a relog and the client re-applies it at login.
  //  - a Power or Lesser Power (the Hist, the Ancestors, the Yokudan gods, Riddle'Thar), or a record the server cannot
  //    read: AddSpell as before, a power to use while the blessing lasts.
  // A cast does not survive a relog (client active effects are not saved here), so it is made again at every login
  // while the blessing runs, and again when the spell's own duration (8 h for the altar spells) ends before the
  // blessing's 8 to 24 h. A cast of the same spell replaces the running one; it does not stack.
  const SWEEP_MS = 60000;
  const SPIT_SPELL = 0, CAST_FIRE_AND_FORGET = 1, DELIVERY_SELF = 0;
  const spellInfoCache = new Map();
  // { type, castType, delivery, cast, ms } for a SPEL (cast: the client casts it on the worshipper; ms: its longest
  // effect, EFIT duration u32 at 8), or null when the record cannot be read
  const spellInfo = (spellId) => {
    spellId >>>= 0;
    if (spellInfoCache.has(spellId)) return spellInfoCache.get(spellId);
    let out = null;
    const r = spellId ? baseRecord(spellId) : null;
    const fields = (r && r.record && String(r.record.type) === 'SPEL' && r.record.fields) || [];
    const spit = fields.find((f) => f && f.type === 'SPIT' && f.data instanceof Uint8Array && f.data.byteLength >= 24);
    if (spit) {
      const u32 = (f, at) => new DataView(f.data.buffer, f.data.byteOffset, f.data.byteLength).getUint32(at, true);
      const type = u32(spit, 8), castType = u32(spit, 16), delivery = u32(spit, 20);
      let secs = 0;
      for (const f of fields) if (f && f.type === 'EFIT' && f.data instanceof Uint8Array && f.data.byteLength >= 12) secs = Math.max(secs, u32(f, 8));
      out = { type, castType, delivery, cast: type === SPIT_SPELL && castType === CAST_FIRE_AND_FORGET && delivery === DELIVERY_SELF, ms: secs * 1000 };
    }
    spellInfoCache.set(spellId, out);
    return out;
  };
  // When each worshipper's client last cast their blessing this session (actorId -> ms). Kept across a reload, emptied by
  // a logout, since the client's effect goes with the session.
  const blessCasts = globalThis.__dboBlessingCasts || (globalThis.__dboBlessingCasts = new Map());
  // What the regeneration tick (below) still owes each blessed worshipper, under one step, and when it last ran for them
  // (actorId -> { at, health, magicka, stamina }). Kept across a reload like blessCasts.
  const regenOwed = globalThis.__dboBlessingRegenOwed || (globalThis.__dboBlessingRegenOwed = new Map());
  const castOnSelf = (a, spellId) => {
    if (typeof sendPacket !== 'function') return false;
    try { sendPacket(a, { customPacketType: 'dboCastSelf', spell: spellId >>> 0 }); blessCasts.set(a, Date.now()); return true; }
    catch (e) { log(`prayer: could not cast ${spellId.toString(16)} on ${display(a)}: ${e.message}`); return false; }
  };
  // A cast blessing that ends before its spell does (the faiths' 4 to 12 h over an 8 h spell, Auri-El's 12 h spell, a
  // turn, a staff reset, a late relog's fresh 8 h) is ended on the worshipper by their own client: dboDispelSelf, the
  // castSelfService handler beside dboCastSelf (Actor.DispelSpell, as beastFormService already uses it). A client without
  // that handler (0.3.74 and older) ignores the packet, as every one of its custom packet listeners returns on a type it
  // does not know, so there the effect runs its own duration as it did before.
  const dispelOnSelf = (a, spellId, why) => {
    if (typeof sendPacket !== 'function' || !spellId) return false;
    try { sendPacket(a, { customPacketType: 'dboDispelSelf', spell: spellId >>> 0 }); }
    catch (e) { log(`prayer: could not end ${spellId.toString(16)} on ${display(a)}: ${e.message}`); return false; }
    log(`prayer: the blessing's effect ${spellId.toString(16)} ended on ${display(a)}'s client (${why})`);
    return true;
  };
  // AddSpell/RemoveSpell are Actor methods and the worshipper is a player, so the call lands
  // (the memory note `papyrus-calls-only-reach-player-actors`: unregistered methods on a
  // server-spawned NPC log and return None, but a player actor is fine).
  const castSpell = (a, spellId, add) => {
    if (!spellId) return false;
    try {
      const self = { type: 'form', desc: mp.getDescFromId(a) };
      const spell = { type: 'espm', desc: mp.getDescFromId(spellId) };
      mp.callPapyrusFunction('method', 'Actor', add ? 'AddSpell' : 'RemoveSpell', self, add ? [spell, false] : [spell]);
      return true;
    } catch (e) { log(`prayer: could not ${add ? 'grant' : 'revoke'} ${spellId.toString(16)}: ${e.message}`); return false; }
  };
  const blessingIdOf = (d) => {
    const s = String(d && d.blessing || '');
    return /^[0-9a-f]+:/i.test(s) ? idOf(s) : 0;     // "<author: ...>" placeholders resolve to 0
  };
  const blessingOf = (a) => { try { const b = mp.get(a, 'private.dboBlessing'); return b && typeof b === 'object' && b.until ? b : null; } catch (e) { return null; } };
  // A cast blessing (via 'cast') was never in the learned list, so there is nothing to take back; its effect is ended on
  // the client instead (dboDispelSelf). A record without `via` was granted before 2026-10-01 by AddSpell, whatever its
  // spell, and is taken back as it always was. `reason` names the end in the log (expired, replaced, turned).
  const clearBlessing = (a, why, reason) => {
    const b = blessingOf(a);
    if (!b) return;
    if (b.spell && b.via !== 'cast') castSpell(a, Number(b.spell) >>> 0, false);
    if (b.spell && b.via === 'cast') dispelOnSelf(a, Number(b.spell) >>> 0, reason || 'ended');
    blessCasts.delete(a);
    regenOwed.delete(a);
    try { mp.set(a, 'private.dboBlessing', null); } catch (e) { /* gone with the character */ }
    if (why) personal(a, why);
  };
  // A boon the server keeps with no spell at all: Sanguine's appetite, Hermaeus Mora's reading, and since 2026-10-01 the
  // regeneration of the Hist and the Yokudan gods (blessingRegen, held by the regeneration tick below) and the Ancestors'
  // ward against fire (combatBoon: gamemode.js blessingCombat, target.ancestors)
  const serverBoonOf = (d) => !!(d && (d.hungerHalf || d.scholarBoon || d.blessingRegen || d.combatBoon));
  // Sheogorath has no blessing of his own and should not have one. The Madgod gives what he feels
  // like, so his worshipper is handed another god's blessing at random - a different one each time.
  // This is the only boon in the list that is more lore-accurate as code than as a record, and it is
  // the only one that needed no Creation Kit work at all. skills.json marks him `capricious: true`.
  const capriceOf = (d) => {
    const pool = DEITIES.filter((x) => x.id !== d.id && (blessingIdOf(x) || serverBoonOf(x)));
    return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
  };

  const grantBlessing = (a, d, hours) => {
    if (d.capricious) {
      const other = capriceOf(d);
      if (!other) { personal(a, `${d.name} laughs, and gives you nothing. He may have meant to.`); return false; }
      const got = grantBlessing(a, other, hours);
      if (got) personal(a, `${d.name} rummages, and hands you the blessing of ${other.name}. He seems delighted.`);
      return got;
    }
    const spell = blessingIdOf(d);
    // A boon does not have to be a spell. Sanguine's is a change to the appetite meter and Hermaeus Mora's lives in
    // the reading round and the dungeon loot; neither has a record, so "no spell" is only a failure when the deity has
    // nothing server-side either (serverBoonOf).
    const serverSide = serverBoonOf(d);
    clearBlessing(a, null, 'replaced');
    if (!spell && !serverSide) {
      // Every Prince still waiting on its SPEL lands here. The prayer succeeded and counted; there
      // is simply nothing to hand over yet.
      personal(a, `${d.name} hears you, and gives no sign. (No blessing exists for ${d.name} yet.)`);
      log(`prayer: ${display(a)} earned a blessing from ${d.name}, which has no spell record`);
      return false;
    }
    const info = spell ? spellInfo(spell) : null;
    const cast = !!(info && info.cast);
    if (cast) {
      // A worshipper blessed before 2026-10-01 may still hold this spell, taught and never cast: it goes first. The
      // server's RemoveSpell does nothing (and tells the client nothing) for a spell it never taught, and it runs on the
      // client before the cast, which arrives after it.
      castSpell(a, spell, false);
      if (!castOnSelf(a, spell)) return false;
    } else if (spell && !castSpell(a, spell, true)) return false;
    const until = Date.now() + Math.max(1, hours) * 3600000;
    // `via` says how the spell was given, so the expiry knows whether there is anything to take back
    try { mp.set(a, 'private.dboBlessing', spell ? { deity: d.id, spell, until, via: cast ? 'cast' : 'spell' } : { deity: d.id, spell, until }); } catch (e) { /* not fatal */ }
    if (spell) log(`prayer: the blessing of ${d.name} ${cast ? 'cast on' : 'given as a spell to'} ${display(a)} for ${Math.max(1, hours)} h${info ? '' : ' (spell record unreadable)'}`);
    else log(`prayer: the blessing of ${d.name} (the server's own) given to ${display(a)} for ${Math.max(1, hours)} h`);
    return true;
  };

  // The four racial powers the faiths gave until 2026-10-01 (Histskin, Ancestor's Wrath, Adrenaline Rush, Night Eye) are
  // dispelled by the client the moment they are used (magicSyncService BLOCKED_POWER_IDS: "Racial powers are disabled on
  // this server"). Their deities now give a passive boon instead (skills.json). A blessing still running from before is
  // moved over at login or at the next sweep: the dead power leaves the learned list and the record takes the deity's
  // blessing of today. Riddle'Thar's Night Eye is then cast like any other; the Hist, the Ancestors and the Yokudan gods
  // are the server's own and need nothing on the client.
  const SPIT_POWER = 2, SPIT_LESSER_POWER = 3;
  const movePower = (a, b) => {
    if (!b || !b.spell || b.via === 'cast' || Number(b.until) <= Date.now()) return b;
    const old = Number(b.spell) >>> 0;
    const info = spellInfo(old);
    if (!info || (info.type !== SPIT_POWER && info.type !== SPIT_LESSER_POWER)) return b;
    const d = deityById(b.deity);
    const now = d ? blessingIdOf(d) : 0;
    if (!d || now === old) return b;                   // a deity that still gives this power keeps it
    const nowInfo = now ? spellInfo(now) : null;
    castSpell(a, old, false);
    let next;
    if (now && nowInfo && nowInfo.cast) next = { deity: b.deity, spell: now, until: b.until, via: 'cast' };     // cast by the next login or sweep
    else if (now) next = castSpell(a, now, true) ? { deity: b.deity, spell: now, until: b.until, via: 'spell' } : { deity: b.deity, spell: 0, until: b.until };
    else next = { deity: b.deity, spell: 0, until: b.until };
    try { mp.set(a, 'private.dboBlessing', next); } catch (e) { return b; }
    log(`prayer: ${display(a)}'s blessing of ${d.name} was the racial power ${old.toString(16)}, which the client blocks; taken back, ${next.via === 'cast' ? `${now.toString(16)} is cast instead` : next.spell ? `${now.toString(16)} given instead` : 'the server keeps the boon now'}`);
    return next;
  };

  // Cast a running blessing again: at login, when the spell's own duration ends first, or for a worshipper blessed before
  // 2026-10-01 (taught, not cast), whose spell leaves the learned list here. Nothing for a blessing about to fade: a new
  // cast would outlast it by the spell's whole duration.
  // Not on the dead: castSelfService casts nothing on a dead player, and the cast would be counted as made (Reviewer F,
  // 2026-10-01). The stand-up after the death casts it (the respawn watch below). `fresh` ends the running effect first
  // (dboDispelSelf), for a cast that may land on one still running: the spell's last minute, a death the effect survived.
  const isDeadNow = (a) => { try { return mp.get(a, 'isDead') === true; } catch (e) { return false; } };
  const recastBlessing = (a, why, fresh) => {
    const b = blessingOf(a);
    if (!b || !b.spell || Number(b.until) - Date.now() <= SWEEP_MS) return false;
    const spell = Number(b.spell) >>> 0;
    const info = spellInfo(spell);
    if (!info || !info.cast) return false;            // an Ability or a Power stays in the learned list, which the client re-applies
    if (isDeadNow(a)) return false;
    if (b.via !== 'cast') {
      castSpell(a, spell, false);
      try { mp.set(a, 'private.dboBlessing', Object.assign({}, b, { via: 'cast' })); } catch (e) { return false; }
      log(`prayer: ${display(a)}'s blessing of ${b.deity} was a taught spell (before 2026-10-01); taken back and cast`);
    }
    if (fresh && b.via === 'cast') dispelOnSelf(a, spell, 'cast again');
    if (!castOnSelf(a, spell)) return false;
    log(`prayer: the blessing of ${b.deity} cast again on ${display(a)} (${why})`);
    return true;
  };
  // gamemode.js calls this with the other login hooks, 8 s into the login
  globalThis.__dboPrayerLogin = (a) => { blessCasts.delete(a); regenOwed.delete(a); movePower(a, blessingOf(a)); recastBlessing(a, 'login'); };

  // Sanguine's boon is not a spell and could not be one: the Prince of indulgence belongs on the
  // appetite meter, and appetite is the gamemode's (private.needs), not the engine's. The needs tick
  // multiplies its hunger step by this, so a blessed worshipper feasts and does not pay for it.
  // Persuasion, which he had before, does nothing at all on a server with no NPCs to persuade.
  globalThis.__dboPrayerHungerMult = (a) => {
    try {
      const b = blessingOf(a);
      if (!b || Number(b.until) <= Date.now()) return 1;
      const d = deityById(b.deity);
      return d && d.hungerHalf ? 0.5 : 1;
    } catch (e) { return 1; }
  };

  // Whether a's blessing (still running) is from a deity carrying this skills.json flag, for the boons that live in other
  // modules: Hermaeus Mora's scholarBoon is read by the reading round (gamemode.js) and the dungeon loot (dungeons.js)
  globalThis.__dboBlessedWith = (a, flag) => {
    try {
      const b = blessingOf(a);
      if (!b || Number(b.until) <= Date.now()) return false;
      const d = deityById(b.deity);
      return !!(d && d[flag]);
    } catch (e) { return false; }
  };

  // A blessing is worn, not held: nothing else expires it, so the module does. The same sweep keeps a cast blessing on
  // its worshipper: once more a sweep before the spell's own duration ends, while the blessing runs on past it.
  every('prayerBlessings', SWEEP_MS, () => {
    // Players online at the last sweep; on globalThis so a reload does not count everyone as just arrived (rest.js)
    const seen = globalThis.__dboBlessingSeen instanceof Set ? globalThis.__dboBlessingSeen : new Set();
    const here = globalThis.__dboBlessingSeen = new Set();
    for (const a of (api.onlineActors ? api.onlineActors() : [])) {
      here.add(a);
      let b = blessingOf(a);
      if (!b) continue;
      if (Number(b.until) <= Date.now()) {
        const d = deityById(b.deity);
        clearBlessing(a, `The blessing of ${d ? d.name : 'your god'} fades.`, 'expired');
        continue;
      }
      b = movePower(a, b);
      const info = b.spell ? spellInfo(Number(b.spell) >>> 0) : null;
      if (!info || !info.cast) continue;
      const at = blessCasts.get(a);
      // Not cast this session: the login does it, 8 s in. Someone already here at the last sweep was missed by it, or was
      // blessed before 2026-10-01 and online when this loaded.
      if (at === undefined) { if (seen.has(a)) recastBlessing(a, 'not cast this session'); continue; }
      if (info.ms > 0 && Date.now() >= at + info.ms - SWEEP_MS && Number(b.until) - (at + info.ms) > SWEEP_MS) recastBlessing(a, 'the spell ran out before the blessing', true);
    }
  });

  // A death and a stand-up (the engine's respawn at the temple, /respawn and Give up, a revive where they fell: downed.js)
  // can leave the client without the blessing's effect, and a cast sent while they were dead was skipped by the client
  // though counted here. So a worshipper seen dead with a cast blessing running is cast again once they have stood for
  // respawnCastSeconds (the client's own death state lags the server's, and a temple respawn loads a new cell). The cast
  // ends any effect that survived the death first, so it never stacks or toggles.
  const RESPAWN_CAST_MS = Math.max(0, Math.round((Number(CFG.respawnCastSeconds ?? 3)) * 1000));
  const fallen = globalThis.__dboBlessingFallen || (globalThis.__dboBlessingFallen = new Map()); // actorId -> 0 while dead, then when seen standing
  every('prayerBlessingRespawn', 1000, () => {
    const now = Date.now();
    const here = new Set();
    for (const a of (api.onlineActors ? api.onlineActors() : [])) {
      here.add(a);
      const b = blessingOf(a);
      const info = b && b.via === 'cast' && b.spell && Number(b.until) > now ? spellInfo(Number(b.spell) >>> 0) : null;
      if (!info || !info.cast) { fallen.delete(a); continue; }
      if (isDeadNow(a)) { fallen.set(a, 0); continue; }
      if (!fallen.has(a)) continue;
      const since = fallen.get(a);
      if (!since) { fallen.set(a, now); continue; }
      if (now - since < RESPAWN_CAST_MS) continue;
      fallen.delete(a);
      recastBlessing(a, 'stood up after a death', true);
    }
    for (const a of [...fallen.keys()]) if (!here.has(a)) fallen.delete(a);
  });

  // ── the regeneration blessings, held by the server ─────────────────────────────────────────────────────────────────
  // The server crops every vitals report to its own regeneration (CropRegeneration.cpp: per second, the race's rate x the
  // server's regenerationMultiplier x the rate mult, all percent), and a blessing's rate effects never reach those numbers:
  // a dboCastSelf cast is not relayed, so the self-cast rate path of 2026-09-29 (ActionListener GetRestorativeEffects
  // withRegenRates, 6fa17721) does not run for it, and an Ability's constant effect is never applied server-side. So
  // Akatosh, Hircine, Meridia and the Worm Cult sped up only the player's own bar, which the server pulled back.
  //
  // The extra is restored here instead, as the Ayleid well restores its own (gamemode.js ayleidWellRegen): every
  // tickSeconds the worshipper's health, magicka or stamina percentage is raised by what the blessing adds in that time,
  // and the crop then works from the raised value. The effects are read from the blessing's own record, with the filter
  // 6fa17721 uses (non-hostile, non-detrimental Value or Peak Value modifiers of HealRate, MagickaRate, StaminaRate and
  // their Mult values), and counted the way the game counts them, which is what the player's client shows:
  //   a rate effect adds its magnitude to the rate:            Hircine's StaminaRate +10 is 10% of the bar a second more
  //   a Mult effect adds its magnitude % of the race's rate:  Meridia's HealRateMult +25 is a quarter of 0.7% a second more
  // both times the server's regenerationMultiplier. (6fa17721's own rate path sets a rate to the magnitude and a Mult to
  // base x (1 + m%) x 4; that path never sees a blessing, and the game's own count is the one the bar shows.)
  // A deity with no spell can name its regeneration in skills.json (blessingRegen: { HealRateMult: 50 }, same units).
  // Nothing is added to the dead or the downed, to a bar already full, or past what Death's Chill allows (its rate factor
  // for that bar, 0 at its cap: downed.js). Steps under minStep wait in regenOwed, so a slow boon is not a packet a second.
  const REGEN = Object.assign({ enabled: true, tickSeconds: 1, minStep: 0.002 }, CFG.blessingRegen || {});
  const REGEN_TICK_MS = Math.max(250, Math.round((Number(REGEN.tickSeconds) || 1) * 1000));
  const REGEN_MIN_STEP = Math.max(0, Number(REGEN.minStep) || 0);
  // libespm ActorValue.h: index -> [the bar, a rate or a Mult]
  const REGEN_AV = { 27: ['health', 'rate'], 28: ['magicka', 'rate'], 29: ['stamina', 'rate'], 155: ['health', 'mult'], 156: ['magicka', 'mult'], 157: ['stamina', 'mult'] };
  const REGEN_AV_BY_NAME = { HealRate: 27, MagickaRate: 28, StaminaRate: 29, HealRateMult: 155, MagickaRateMult: 156, StaminaRateMult: 157 };
  const AV_NAME = Object.fromEntries(Object.entries(REGEN_AV_BY_NAME).map(([k, v]) => [v, k]));
  const CHILL_AV = { health: 'HealRateMult', magicka: 'MagickaRateMult', stamina: 'StaminaRateMult' };
  const ARCH_VALUE_MOD = 0, ARCH_PEAK_VALUE_MOD = 34, MGEF_HOSTILE = 0x1, MGEF_DETRIMENTAL = 0x4;
  // The server's regeneration multiplier (server-settings regenerationMultiplier; 1 when unset, as WorldState.h has it)
  const REGEN_MULT = (() => {
    try { const v = Number((mp.getServerSettings() || {}).regenerationMultiplier); return Number.isFinite(v) && v >= 0 ? v : 1; } catch (e) { return 1; }
  })();
  const u32At = (f, at) => new DataView(f.data.buffer, f.data.byteOffset, f.data.byteLength).getUint32(at, true);
  const regenCache = new Map();
  // [{ av, stat, kind, mag }] for a spell's regeneration boosts, read from its EFID/EFIT pairs and each effect's MGEF DATA
  // (flags u32 at 0, archetype u32 at 64, primary actor value i32 at 68; libespm MGEF.h)
  const spellRegen = (spellId) => {
    spellId >>>= 0;
    if (regenCache.has(spellId)) return regenCache.get(spellId);
    const out = [];
    const r = spellId ? baseRecord(spellId) : null;
    const fields = (r && r.record && String(r.record.type) === 'SPEL' && r.record.fields) || [];
    let effect = 0;
    for (const f of fields) {
      if (!f || !(f.data instanceof Uint8Array)) continue;
      if (f.type === 'EFID' && f.data.byteLength >= 4) {
        const local = u32At(f, 0);
        effect = typeof r.toGlobalRecordId === 'function' ? r.toGlobalRecordId(local) >>> 0 : local;
      } else if (f.type === 'EFIT' && f.data.byteLength >= 4 && effect) {
        const mag = new DataView(f.data.buffer, f.data.byteOffset, f.data.byteLength).getFloat32(0, true);
        const m = baseRecord(effect);
        const data = m && m.record && String(m.record.type) === 'MGEF' && (m.record.fields || []).find((x) => x && x.type === 'DATA' && x.data instanceof Uint8Array && x.data.byteLength >= 72);
        if (data) {
          const flags = u32At(data, 0), arch = u32At(data, 64);
          const av = new DataView(data.data.buffer, data.data.byteOffset, data.data.byteLength).getInt32(68, true);
          const kind = REGEN_AV[av];
          if (kind && (arch === ARCH_VALUE_MOD || arch === ARCH_PEAK_VALUE_MOD) && !(flags & (MGEF_HOSTILE | MGEF_DETRIMENTAL)) && mag > 0) {
            out.push({ av: AV_NAME[av], stat: kind[0], kind: kind[1], mag });
          }
        }
        effect = 0;
      }
    }
    regenCache.set(spellId, out);
    return out;
  };
  const deityRegen = (d) => Object.entries((d && d.blessingRegen) || {})
    .filter(([k, v]) => REGEN_AV_BY_NAME[k] !== undefined && Number(v) > 0)
    .map(([k, v]) => { const kind = REGEN_AV[REGEN_AV_BY_NAME[k]]; return { av: k, stat: kind[0], kind: kind[1], mag: Number(v) }; });
  // What a running blessing adds: its spell's boosts (only the deity's blessing of today, so a record from before cannot
  // run a power's effects), and the deity's own blessingRegen
  const regenOfBlessing = (b) => {
    const d = deityById(b && b.deity);
    if (!d) return [];
    const spell = Number(b.spell) >>> 0;
    return (spell && spell === blessingIdOf(d) ? spellRegen(spell) : []).concat(deityRegen(d));
  };
  // The race's own rates (RACE DATA floats at 84, 88, 92: libespm RACE.cpp), which is what the crop starts from
  const RACE_RATE_AT = { health: 84, magicka: 88, stamina: 92 };
  const VANILLA_RATE = { health: 0.7, magicka: 3, stamina: 5 };
  const raceRates = new Map();
  const raceRateOf = (a, stat) => {
    let race = 0;
    try { const app = mp.get(a, 'appearance'); race = app && app.raceId ? Number(app.raceId) >>> 0 : 0; } catch (e) { race = 0; }
    if (!raceRates.has(race)) {
      let rates = null;
      const r = race ? baseRecord(race) : null;
      const data = r && r.record && String(r.record.type) === 'RACE' && (r.record.fields || []).find((x) => x && x.type === 'DATA' && x.data instanceof Uint8Array && x.data.byteLength >= 96);
      if (data) {
        const v = new DataView(data.data.buffer, data.data.byteOffset, data.data.byteLength);
        rates = { health: v.getFloat32(84, true), magicka: v.getFloat32(88, true), stamina: v.getFloat32(92, true) };
      }
      raceRates.set(race, rates);
    }
    const x = Number((raceRates.get(race) || {})[stat]);
    return Number.isFinite(x) && x >= 0 ? x : VANILLA_RATE[stat];
  };
  // The share of a bar a second that one boost adds, before Death's Chill
  const regenPerSecond = (a, e) => (e.kind === 'rate' ? e.mag : raceRateOf(a, e.stat) * e.mag / 100) / 100 * REGEN_MULT;
  globalThis.__dboBlessingRegen = (a) => { const b = blessingOf(a); return b && Number(b.until) > Date.now() ? regenOfBlessing(b).map((e) => Object.assign({ perSecond: regenPerSecond(a, e) }, e)) : []; };
  const chillOf = (a, stat) => {
    try { if (typeof globalThis.__dboChillRateMult === 'function') { const f = Number(globalThis.__dboChillRateMult(a, CHILL_AV[stat])); return f >= 0 ? Math.min(1, f) : 1; } } catch (e) { /* no downed system */ }
    return 1;
  };
  // Registered whatever the config says and off inside, so a reload that turns it off replaces the running timer (every()
  // replaces by name) rather than leaving the previous module's
  every('prayerBlessingRegen', REGEN_TICK_MS, () => {
    if (REGEN.enabled === false) { regenOwed.clear(); return; }
    const now = Date.now();
    const here = new Set();
    for (const a of (api.onlineActors ? api.onlineActors() : [])) {
      here.add(a);
      const b = blessingOf(a);
      const list = b && Number(b.until) > now ? regenOfBlessing(b) : [];
      if (!list.length) { regenOwed.delete(a); continue; }
      let owed = regenOwed.get(a);
      if (!owed) { owed = { at: now - REGEN_TICK_MS, health: 0, magicka: 0, stamina: 0 }; regenOwed.set(a, owed); }
      // The time since this worshipper's last tick, never more than three ticks (a stall or a reload does not pay out)
      const secs = Math.min(Math.max(0, now - owed.at), 3 * REGEN_TICK_MS) / 1000;
      owed.at = now;
      let pc = null;
      try { pc = mp.get(a, 'percentages'); } catch (e) { pc = null; }
      let downed = false; try { downed = typeof globalThis.__dboIsDowned === 'function' && !!globalThis.__dboIsDowned(a); } catch (e) { downed = false; }
      if (!pc || !(Number(pc.health) > 0) || downed || !(secs > 0)) { owed.health = owed.magicka = owed.stamina = 0; continue; }
      const next = { health: Number(pc.health), magicka: Number(pc.magicka), stamina: Number(pc.stamina) };
      let changed = false;
      for (const stat of ['health', 'magicka', 'stamina']) {
        let add = 0;
        for (const e of list) if (e.stat === stat) add += regenPerSecond(a, e) * secs;
        add *= chillOf(a, stat);
        if (!(next[stat] < 1) || !(add > 0)) { owed[stat] = 0; continue; }
        owed[stat] += add;
        if (owed[stat] < REGEN_MIN_STEP) continue;
        next[stat] = Math.min(1, next[stat] + owed[stat]);
        owed[stat] = 0;
        changed = true;
      }
      if (changed) { try { mp.set(a, 'percentages', next); } catch (e) { regenOwed.delete(a); } }
    }
    for (const a of [...regenOwed.keys()]) if (!here.has(a)) regenOwed.delete(a);
  });

  // ── the verses ──────────────────────────────────────────────────────────────────────────────
  // Three lines, the middle one drawn from the deity's own if it has any. Nothing here is judged;
  // the text only gives the worshipper something to hold the key through.
  const COMMON = [
    'Hear me, for I have walked far to stand here',
    'I bring no gold, only the hours of my hands',
    'Let the road ahead be no kinder than I have earned',
    'What was given I have not squandered',
    'I ask nothing that another must go without',
    'Keep my name where you can find it again',
  ];
  const OWN = {
    hist: ['The root remembers what the branch forgets', 'I drink of the sap and am made again'],
    ancestors: ['My fathers stand behind me and I will not shame them', 'The dead of my House watch, and I am not alone'],
    yokudan: ['HoonDing, make the way where there is none', 'Tu\'whacca, keep the Far Shores open for my kin'],
    riddlethar: ['The moons turn and I turn with them', 'Let me walk the Riddle-Thar and not stray from it'],
    trinimac: ['Strength in the service of what is right', 'Let me be the shield and not the blade that turns'],
    dragoncult: ['The dragons are the sons of Time and their word is law', 'Let my Voice be heard as theirs was heard'],
    wormcult: ['Death is a door and I hold the key', 'What the grave takes, the King of Worms returns'],
    akatosh: ['Time turns, and I turn with it', 'The dragon does not hurry and neither shall I'],
    arkay: ['The dead are counted and none are lost', 'I will meet my hour without argument'],
    dibella: ['Let me see the world as it deserves to be seen', 'Beauty is not owed to me, but I will look for it'],
    julianos: ['What I do not know, let me learn honestly', 'Wisdom is slow and I am willing'],
    kynareth: ['The wind is older than the road', 'I take from the land only what grows back'],
    mara: ['Let me be the one who stays', 'Mercy costs nothing and I have little else'],
    stendarr: ['Strength without mercy is only weight', 'Stand between the weak and the world'],
    talos: ['A man became a god and did not forget', 'The Empire forgets, the North remembers'],
    zenithar: ['An honest trade leaves both hands full', 'Work first, and the coin will follow'],
    auriel: ['The snow remembers the ones who kept faith', 'Light bends but does not break'],
    malacath: ['The scorned do not beg', 'Broken and kept, that is the bargain'],
    nocturnal: ['What the dark holds it does not give back', 'Luck is a debt and I will pay it'],
    azura: ['Dusk and dawn are the same door', 'Show me the shape of what comes'],
    boethiah: ['Take by strength what deceit could not hold', 'The teacher is the one still standing'],
    mephala: ['Every thread pulls another', 'What is said in the dark is still said'],
    clavicusvile: ['Name the price and I will hear the rest', 'A bargain is a promise with teeth'],
    hermaeusmora: ['What is known cannot be unknown again', 'I come to be read as much as to read'],
    hircine: ['Let the chase be long and the ending quick', 'There is no hunter who is not also game'],
    mehrunes: ['What stands has stood long enough', 'Tear it down and see what was beneath'],
    meridia: ['The dead should stay where they were put', 'Light does not forgive, it only shines'],
    molagbal: ['Everything that lives belongs to something', 'Kneel early and it is over sooner'],
    namira: ['Praise what the others turn their faces from', 'In the dark nothing is ugly'],
    peryite: ['Everything rots, and in its proper order', 'Even the least thing is given its task'],
    sanguine: ['One more, and then one more after that', 'Nothing was ever regretted before morning'],
    sheogorath: ['I asked a question and the answer was a fish', 'Cheese for everyone, and none for me'],
    vaermina: ['Take the dream and leave me the waking', 'I remember a thing that never happened'],
  };
  const verseFor = (d, i, rand) => {
    const own = OWN[d.id] || [];
    if (i === 1 && own.length) return own[Math.floor(rand() * own.length)];
    return COMMON[Math.floor(rand() * COMMON.length)];
  };

  const rngOf = (seed) => {
    let s = seed >>> 0;
    return () => {
      s = (s + 0x6d2b79f5) >>> 0;
      let t = Math.imul(s ^ (s >>> 15), s | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  };

  const roundFor = (a, d, refId, shrineName) => {
    const seed = (Math.floor(Math.random() * 0xffffffff) >>> 0);
    const rand = rngOf(seed);
    const verses = [];
    for (let i = 0; i < VERSES; i++) {
      verses.push({ text: verseFor(d, i, rand), startMs: i * VERSE_MS, endMs: (i + 1) * VERSE_MS });
    }
    return {
      nonce: `${a.toString(16)}-${Date.now().toString(36)}-${Math.floor(Math.random() * 1e9).toString(36)}`,
      deityId: d.id, deityName: d.name, kind: d.kind, refId, shrineName, seed, verses,
      totalMs: VERSES * VERSE_MS, slackMs: SLACK_MS, startGraceMs: CFG.startGraceMs,
      startedAt: 0,
      // openedAt: when the panel was sent; startedAt: when the round began (the first press, or openedAt for a panel
      // that never says); begun: the panel said when
      openedAt: 0, begun: false,
    };
  };

  // Everything the widget needs to draw the prayer, and nothing it could use to judge it
  const packetFor = (round, result, resultKind) => {
    const w = {
      type: 'prayer', id: WIDGET_ID, nonce: round.nonce,
      deity: round.deityName, kind: round.kind, shrine: round.shrineName,
      verses: round.verses, totalMs: round.totalMs,
      // This server times the round from the first press: the panel waits for it and says when (dbo:prayerStart)
      startOnPress: true,
    };
    // A new widget judges the hold itself with these; an older one ignores them and reports its spans as before
    if (clientJudged()) Object.assign(w, { judge: 'client', slackMs: round.slackMs, startGraceMs: round.startGraceMs, waitMs: Math.round(Number(CFG.waitSeconds) * 1000) });
    if (result) { w.result = result; w.resultKind = resultKind; }
    return w;
  };

  const startRound = (a, round) => {
    // A closed round of this worshipper at the same shrine can no longer be paid once a new one is issued there: one
    // round per shrine at a time (review F1, 2026-10-01). Its fail rest normally stops a new round until it is gone.
    for (const [n, c] of closing) {
      if (c.a !== a || c.round.refId !== round.refId) continue;
      closing.delete(n);
      log(`prayer superseded ${display(a)} ${c.round.deityName}: a closed round (${c.how}) dropped by a new round at the same shrine`);
    }
    sessions.set(a, round);
    round.openedAt = round.startedAt = nowMs();
    // Every round issued is logged, so one that never comes back (cancelled, hidden, lost) can be counted
    log(`prayer issue ${display(a)} ${round.deityName} total=${round.totalMs} judge=${clientJudged() ? 'client' : 'server'} seed=${round.seed.toString(16)}`);
    if (!openWidget(a, packetFor(round), true)) sessions.delete(a);
    return true;
  };

  // How long a round lives on the server's clock. Client-judged: the verses plus minutes, from the first press if it
  // came (a late prayerStart only lengthens it) - cleanup, not a deadline. Rollback: the lag grace, as before.
  const timeoutMs = () => Math.max(60000, Number(CFG.roundTimeoutMs) || 180000);
  const limitOf = (r) => (clientJudged()
    ? (r.begun ? r.startedAt : r.openedAt) + r.totalMs + timeoutMs()
    : r.begun ? r.startedAt + r.totalMs + CFG.lagGraceMs : r.openedAt + CFG.waitSeconds * 1000 + r.totalMs + CFG.legacyLagGraceMs);
  const liveRound = (a) => {
    const r = sessions.get(a);
    if (!r) return null;
    if (nowMs() <= limitOf(r)) return r;
    sessions.delete(a);
    // No rest: an expired round costs no more than walking away (DESIGN.md section 2)
    if (clientJudged()) log(`prayer expired ${display(a)} ${r.deityName} after ${Math.round(nowMs() - r.openedAt)} ms, no report`);
    return null;
  };
  // Touching the shrine again while a round is live: the panel was lost (a reload, F2, a crash), so it is drawn again.
  // Same nonce, so a panel still showing it keeps its state.
  const reshow = (a, round) => { if (clientJudged()) { round.hidden = false; openWidget(a, packetFor(round), true); } return true; };

  // show: 'widget' re-sends the panel with the verdict (the default), 'say' tells it in chat (the panel is gone), 'none'
  // says nothing (a provisional end that a report still on its way replaces)
  const finish = (a, round, win, text, kind, rest, show) => {
    if (rest !== false) {
      const rests = restsOf(a);
      // restUntil: the rest this round wrote itself, so its own report can tell it from one another round wrote since
      round.restUntil = rests[round.refId.toString(16)] = Date.now() + (win ? SHRINE_COOLDOWN_MS : CFG.failRestMinutes * 60000);
      saveRests(a, rests);
    }
    if (show === 'say') personal(a, text);
    else if (show !== 'none') openWidget(a, packetFor(round, text, kind), false);
    if (sessions.get(a) === round) sessions.delete(a);
    spent.set(round.nonce, Date.now());
    for (const [n, t] of spent) if (Date.now() - t > 600000) spent.delete(n);
  };
  // Client -> server packets are reliable but not ordered, so a Stand up, an Escape or an F2 sent just after the report
  // can overtake it. A round ended that way is kept by nonce until its timeout: a report that turns up after it is still
  // judged, and a held prayer replaces the fail rest with the shrine's own. Client-judged only.
  const closing = globalThis.__dboPrayerClosing instanceof Map ? globalThis.__dboPrayerClosing : (globalThis.__dboPrayerClosing = new Map()); // nonce -> { a, round, how }
  const keepClosing = (a, round, how) => {
    if (!clientJudged()) return;
    for (const [n, c] of closing) if (nowMs() > limitOf(c.round)) closing.delete(n);
    // Where the worshipper was when the close arrived: they rise after the verdict, so this is never further than when
    // the report was sent, and it still counts if a load door has since taken them to another cell (review LAT-1)
    try { if (round.refId !== ANYWHERE_REF && typeof distanceMeters === 'function') round.closeNear = distanceMeters(a, round.refId); } catch (e) { /* unknown */ }
    closing.set(round.nonce, { a, round, how });
    while (closing.size > 500) closing.delete(closing.keys().next().value);
  };

  // ── the activate hook ───────────────────────────────────────────────────────────────────────
  // Called from the gamemode's activate chain; true means the activation was ours. A target that is
  // not a shrine returns false and the chain carries on - see the memory note
  // `gamemode-activate-chain-runs-before-systems`: a refusal that returns true stops every gate
  // below it, which is how labour.js once made its own skill impossible to open.
  // Why this character cannot pray at this shrine now, or null. A plain touch and the shrine panel's Pray ask the same.
  const prayRefusal = (a, targetId, d) => {
    const faith = faithOf(a);
    if (!faith) return `This is a shrine of ${d.name}. You hold no god yet - say "/deity ${d.name}" here to take ${d.name} as your own.`;
    const mine = deityById(faith.id);
    if (PRAY.onlyOwnDeity !== false && !sameFaith(mine, d)) {
      return `${d.name} has no ear for a follower of ${mine ? mine.name : 'another god'}. Find your own shrine, or say "/deity ${d.name}" here to turn.`;
    }
    const until = Number(restsOf(a)[targetId.toString(16)]) || 0;
    if (until > Date.now()) {
      const mins = Math.ceil((until - Date.now()) / 60000);
      return `You have prayed here recently. This shrine will hear you again in ${mins} minute${mins === 1 ? '' : 's'}.`;
    }
    return null;
  };
  const shrineNameOf = (baseId, d) => { const rec = baseId ? baseRecord(baseId) : null; return (rec && rec.record && rec.record.name) || `Shrine of ${d.name}`; };
  // Kneel: once prayRefusal has nothing to say
  const prayAt = (casterId, targetId, baseId, d) => {
    const faith = faithOf(casterId);
    // Bruma is Imperial. The White-Gold Concordat outlawed Talos, and most Daedra worship is
    // proscribed - Beyond Skyrim has already renamed the Great Chapel of Talos to the Cathedral of
    // St Martin for exactly this reason. NOT all of it, though: Malacath, Azura and Meridia are
    // openly legal and carry `lawful: true`, so nothing is said at their shrines. The rest differ
    // enormously in how hard the law is pressed - Mehrunes Dagon in Bruma of all cities against
    // Sanguine's drinking - so the reason comes from the deity's own `unlawfulWhere` rather than one
    // line for all of them. Said once per character, and nothing follows from it: no guard reads
    // `lawful`, deliberately. Whether the law has teeth is a faction decision.
    if (d.lawful === false && faith && !faith.warnedUnlawful) {
      faith.warnedUnlawful = true;
      setFaith(casterId, faith);
      const why = String(d.unlawfulWhere || '').trim();
      personal(casterId, d.kind === 'divine'
        ? 'You kneel to Talos in an Imperial county. The Concordat calls that a crime, and the Thalmor keep a Justiciar in Bruma. Nobody stops you.'
        : `You kneel to ${d.name} in an Imperial county.${why ? ' ' + why : ` ${d.name} is proscribed here, and the shrine is hidden for a reason.`} Nobody stops you.`);
    }
    return startRound(casterId, roundFor(casterId, d, targetId, shrineNameOf(baseId, d)));
  };

  // A carrier is told before a prayer that would cure the disease (supernatural.js), and prays on the next try
  const superWarning = (a, d) => {
    try { return d && typeof globalThis.__dboSuperPrayWarning === 'function' ? String(globalThis.__dboSuperPrayWarning(a, d.id) || '') : ''; } catch (e) { return ''; }
  };
  globalThis.__dboPrayerActivate = (targetId, casterId) => {
    if (!CFG.enabled || targetId >= 0xff000000) return false;
    const baseId = baseIdOf(targetId);
    const d = shrineAt(targetId, baseId);
    if (!d) return false;

    // From here on the target IS a shrine: the vanilla blessing must not fire whatever we answer.
    lastShrine.set(casterId, { deityId: d.id, at: Date.now() });
    log(`shrine touch ${display(casterId)} ${d.name}`);
    { const live = liveRound(casterId); if (live) return reshow(casterId, live); }
    // Nate 2026-09-30: a shrine that keeps a rite (Molag Bal, Hircine, Arkay, Stendarr) opens a panel to pray or perform
    // it (supernatural.js). Every other shrine, or no panel to open, prays as a touch always has.
    if (typeof globalThis.__dboShrinePanel === 'function') {
      try { if (globalThis.__dboShrinePanel(casterId, targetId, { id: d.id, name: d.name, shrineName: shrineNameOf(baseId, d) })) return true; } catch (e) { log('shrine panel failed', e.message); }
    }
    const why = prayRefusal(casterId, targetId, d) || superWarning(casterId, d);
    if (why) return deny(casterId, why);
    return prayAt(casterId, targetId, baseId, d);
  };
  // For the shrine panel: why Pray would be refused here ('' when it would not), and Pray itself, which is a touch from
  // the refusal on. The start answers the refusal, or '' once the prayer has begun.
  globalThis.__dboPrayerRefusal = (casterId, targetId) => {
    if (!CFG.enabled) return 'Prayer is closed on this server.';
    const d = shrineAt(targetId, baseIdOf(targetId));
    return d ? prayRefusal(casterId, targetId, d) || '' : 'This is no shrine.';
  };
  globalThis.__dboPrayerStart = (casterId, targetId) => {
    const why = globalThis.__dboPrayerRefusal(casterId, targetId);
    if (why) return why;
    { const live = liveRound(casterId); if (live) { reshow(casterId, live); return ''; } }
    const baseId = baseIdOf(targetId);
    const warn = superWarning(casterId, shrineAt(targetId, baseId));
    if (warn) return warn;
    prayAt(casterId, targetId, baseId, shrineAt(targetId, baseId));
    return '';
  };

  // ── praying anywhere ────────────────────────────────────────────────────────────────────────
  // The faiths with no shrine in Bruma (skills.json prayAnywhere: the Hist, the Ancestors, the Yokudan gods and the rest)
  // are prayed to wherever the worshipper kneels; the same three verses, one rest for all of it, and rarer blessings.
  const ANYWHERE_REF = 1;
  registerChatCommand('pray', (a) => {
    if (!CFG.enabled) return personal(a, 'Prayer is closed on this server.');
    { const live = liveRound(a); if (live) { reshow(a, live); return; } }
    const faith = faithOf(a);
    const d = faith ? deityById(faith.id) : null;
    if (!d) return personal(a, 'You hold no god. Say /deity to choose one.');
    if (!d.prayAnywhere) return personal(a, `${d.name} is prayed to at a shrine. Find one and use it.`);
    const until = Number(restsOf(a)[ANYWHERE_REF.toString(16)]) || 0;
    if (until > Date.now()) {
      const mins = Math.ceil((until - Date.now()) / 60000);
      return personal(a, `You have prayed recently. ${d.name} will hear you again in ${mins} minute${mins === 1 ? '' : 's'}.`);
    }
    startRound(a, roundFor(a, d, ANYWHERE_REF, `A prayer to ${d.name}`));
  }, { help: 'pray to a faith that needs no shrine (the Hist, the Ancestors and others)' });

  // ── offerings ───────────────────────────────────────────────────────────────────────────────
  // /offer <gold> at your god's shrine (or anywhere, for a faith prayed to anywhere). Half is consumed as the offering,
  // half goes to the treasury of the town it is made in for the temple's upkeep, and for an hour the god listens more
  // closely: the next prayer's blessing chance grows by the offering, up to double at offerFullGold.
  const OFFER = Object.assign({ min: 5, max: 1000, fullGold: 100, minutes: 60 }, (cfg.prayer || {}).offering || {});
  const offeringOf = (a) => { try { const o = mp.get(a, 'private.dboOffering'); return o && o.until > Date.now() ? o : null; } catch (e) { return null; } };
  registerChatCommand('offer', (a, argStr) => {
    const gold = Math.floor(Number(String(argStr || '').trim()));
    const faith = faithOf(a);
    const d = faith ? deityById(faith.id) : null;
    if (!d) return personal(a, 'You hold no god to make an offering to.');
    if (!Number.isFinite(gold) || gold < OFFER.min || gold > OFFER.max) return personal(a, `Offer between ${OFFER.min} and ${OFFER.max} gold: /offer <gold>`);
    if (!d.prayAnywhere) {
      const here = lastShrine.get(a);
      if (!here || !sameFaith(deityById(here.deityId), d) || Date.now() - here.at > 120000) return personal(a, `Offerings to ${d.name} are made at their shrine. Touch it first.`);
    }
    if (typeof takeGold !== 'function' || !takeGold(a, gold)) return personal(a, `You do not have ${gold} gold to offer.`);
    const upkeep = Math.floor(gold / 2);
    const kept = typeof treasuryHere === 'function' ? treasuryHere(a, upkeep) : 0;
    const prev = offeringOf(a);
    const total = (prev && prev.deityId === d.id ? prev.gold : 0) + gold;
    try { mp.set(a, 'private.dboOffering', { deityId: d.id, gold: total, until: Date.now() + OFFER.minutes * 60000 }); } catch (e) { /* not an actor */ }
    audit(`OFFERING ${who(a)} offered ${gold} gold to ${d.name}${kept ? ` (${kept} to the town for the temple)` : ''}`);
    personal(a, `You leave ${gold} gold for ${d.name}. For the next hour, ${d.name} listens more closely.`);
  }, { help: 'make an offering of gold to your god before praying' });

  // ── judging ─────────────────────────────────────────────────────────────────────────────────
  // The report is a list of [down, up] spans on the widget's clock, in ms from the moment it
  // mounted. Everything the verdict needs is in those numbers and the round the server already
  // holds; nothing the widget says about its own success is read.
  const judge = (round, raw, at, elapsed) => {
    const r = { spans: 0, held: 0, covered: 0, worst: 0, late: 0, at, lag: Math.round(elapsed - at), bad: '', sus: [] };
    let list = [];
    try { list = JSON.parse(String(raw)); } catch (e) { r.bad = 'parse'; return r; }
    if (!Array.isArray(list)) { r.bad = 'shape'; return r; }
    if (list.length > 64) { r.bad = 'count'; return r; }

    let prevEnd = -1;
    for (const span of list) {
      if (!Array.isArray(span) || span.length !== 2) { r.bad = 'shape'; return r; }
      const down = Number(span[0]), up = Number(span[1]);
      if (!Number.isInteger(down) || !Number.isInteger(up)) { r.bad = 'shape'; return r; }
      if (down < 0 || up > round.totalMs || up < down) { r.bad = 'range'; return r; }
      if (down < prevEnd) { r.bad = 'overlap'; return r; }   // the spans also order themselves
      prevEnd = up;
      r.spans++; r.held += up - down;
    }
    if (prevEnd > at) { r.bad = 'submit'; return r; }        // a key still down after the report went out
    if (clientJudged()) {
      // The widget judges: nothing on the server's clock refuses a prayer. Both bounds below become review flags.
      r.sus.push(...MG.lagFlags(r.lag, CFG.clockSlackMs, CFG.slowFlagMs));
    } else {
      // The widget's clock may sit behind the server's by the transport, never ahead of it, and a
      // round played out in slow motion and scaled back down is the one cheat the coverage check
      // alone would not see. Same two bounds labour.js uses.
      if (r.lag < -CFG.clockSlackMs) { r.bad = 'future'; return r; }
      if (r.lag > (round.begun ? CFG.lagGraceMs : CFG.legacyLagGraceMs)) { r.bad = 'late'; return r; }
    }

    const first = list.length ? Number(list[0][0]) : Infinity;
    if (first > round.startGraceMs) { r.late = first; r.bad = 'slow'; return r; }

    // Coverage, verse by verse: the worst gap decides, so one lapse cannot be averaged away by two
    // verses held perfectly. The first verse is counted from the first press (checked above to be within
    // startGraceMs): before 2026-09-29 a press 0.6 s in passed the start check and still failed here.
    round.verses.forEach((v, i) => {
      const from = i === 0 ? Math.max(v.startMs, first) : v.startMs;
      let inside = 0;
      for (const [down, up] of list) inside += Math.max(0, Math.min(up, v.endMs) - Math.max(down, from));
      const gap = (v.endMs - from) - inside;
      r.covered += inside;
      r.worst = Math.max(r.worst, gap);
    });
    if (r.worst > round.slackMs) r.bad = 'released';
    return r;
  };

  onUi('prayerCancel', (a, args) => {
    const round = sessions.get(a);
    // After the verdict the round is already gone: Rise only closes the window
    if (!round) return closeWidget(a, WIDGET_ID);
    if (String(args[0]) !== round.nonce) return;
    // A round never begun (no first press, dbo:prayerStart) is no failed prayer and rests nothing. Every touch of a shrine
    // that is not resting starts a round, and /offer wants that touch, so closing the panel to make an offering rested
    // the shrine for failRestMinutes before the prayer the offering was for (2026-10-01).
    if (!round.begun) return finish(a, round, false, 'You rise without praying. Kneel again when you are ready.', 'lose', false);
    // A new widget shows its own verdict the moment the verses end, so Rise can follow the report within milliseconds
    // and, the channel being unordered, arrive first. Past the verses, Rise is not standing up early: the panel closes,
    // the fail rest is written for now, and the report on its way is still judged, its verdict told in chat.
    if (clientJudged() && round.begun && nowMs() - round.startedAt >= round.totalMs - MG.floorAllowance(round.totalMs, CFG.clockSlackMs)) {
      log(`prayer abandon(rise) ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms, past the verses: waiting for the report`);
      finish(a, round, false, '', 'lose', true, 'none');
      closeWidget(a, WIDGET_ID);
      keepClosing(a, round, 'close');
      return;
    }
    log(`prayer abandon(cancel) ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms`);
    finish(a, round, false, 'You rise before the third verse. The shrine is silent.', 'lose');
    keepClosing(a, round, 'cancel');
  });
  // The relay's own close (Escape caught by the client, or F2 hiding the interface: args ['hidden']). It used to be
  // ignored and the round hung until a later touch (DESIGN.md section 13). F2 is not standing up: no rest, as in labour.
  onUi('close', (a, args, widgetId) => {
    if (widgetId !== WIDGET_ID) return;
    const round = sessions.get(a);
    if (!round) return;
    const hidden = Array.isArray(args) && args[0] === 'hidden';
    if (hidden && clientJudged()) {
      // Client-judged: F2 leaves the round live, so it can never run beside a new one. Touching the shrine or /pray draws
      // it again (reshow), and its report is judged as usual, the verdict told in chat while the panel is hidden. It used
      // to leave sessions with no rest while its report could still be paid, so touch, F2, touch, F2... stacked rounds
      // at one shrine and every one of them paid: mastery, a blessing roll and the fever cure (review F1, 2026-10-01).
      round.hidden = true;
      log(`prayer hidden ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms: the round stays live, no rest`);
      return;
    }
    // Escape before the first press is no failed prayer, as with Rise (ad7aff44): an offering wants the shrine touched,
    // and closing that round to type /offer must not rest the shrine before the prayer the offering is for
    if (!hidden && !round.begun) {
      log(`prayer abandon(close) ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms, before the first press: no rest`);
      return finish(a, round, false, 'You rise without praying. Kneel again when you are ready.', 'lose', false, 'say');
    }
    log(`prayer abandon(${hidden ? 'hidden' : 'close'}) ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms${hidden ? ', no rest' : ''}`);
    if (hidden) sessions.delete(a);
    else finish(a, round, false, 'You rise before the third verse. The shrine is silent.', 'lose', true, 'say');
    keepClosing(a, round, hidden ? 'hidden' : 'close');
  });
  // A logout ends a prayer with no rest: a crash must not cost the shrine (gamemode.js disconnect list)
  globalThis.__dboPrayerLeave = (a) => {
    const round = sessions.get(a);
    if (!round) return;
    sessions.delete(a);
    log(`prayer abandon(logout) ${display(a)} ${round.deityName} after ${Math.round(nowMs() - round.openedAt)} ms, no rest`);
  };
  // Rounds nobody reports are cleared on the minute scale, logged, so a lost round can be counted
  every('prayerSweep', 30000, () => {
    for (const a of [...sessions.keys()]) liveRound(a);
    for (const [n, c] of closing) if (nowMs() > limitOf(c.round)) closing.delete(n);
  });

  // The panel's first press: from here the round runs. Once only. Rollback: only while the panel may still wait for it
  // (waitSeconds on the server's clock). Client-judged: the widget keeps its own wait, and this only times the lag.
  onUi('prayerStart', (a, args) => {
    const round = sessions.get(a);
    if (!round || String(args[0]) !== round.nonce || round.begun) return;
    if (!clientJudged() && nowMs() - round.openedAt > CFG.waitSeconds * 1000) return;
    round.begun = true;
    round.startedAt = nowMs();
    const wait = MG.ms(args[1]);
    if (Number.isFinite(wait) && wait >= 0) round.waitMs = wait;
  });

  // The new widget's verdict, args[3] (minigames.js): win, why, worst, durMs, waitMs, blurs. Anything unreadable is an
  // old widget, judged from its spans.
  const claimOf = (raw) => {
    const c = MG.verdictOf(raw);
    if (!c || typeof c.win !== 'boolean') return null;
    return { win: c.win, why: String(c.why || '').replace(/[^a-z-]/gi, '').slice(0, 16), worst: MG.ms(c.worst), durMs: MG.ms(c.durMs), waitMs: MG.ms(c.waitMs), blurs: MG.ms(c.blurs) };
  };
  const ignored = MG.limiter(5000);
  // What the replay says when the spans are well formed: held, or the ordinary losses (slow to start, a lapse)
  const ORDINARY = new Set(['slow', 'released']);

  onUi('prayer', (a, args) => {
    const nonce = String(args[0]);
    let round = sessions.get(a);
    let closed = '';
    if (!round || nonce !== round.nonce) {
      const c = closing.get(nonce);
      if (c && c.a === a && nowMs() <= limitOf(c.round)) { round = c.round; closed = c.how; }
      else {
        if (spent.has(nonce)) log(`prayer replay ${display(a)}: ${nonce.slice(0, 40)} was already judged`);
        else if (ignored(a, nowMs())) log(`prayer ignored ${display(a)}: ${round ? 'another round is live' : 'no round'} for ${nonce.slice(0, 40)}`);
        return;
      }
    }
    closing.delete(nonce);
    const now = nowMs();
    const elapsed = now - round.startedAt;
    const sinceSent = now - round.openedAt;
    const cj = clientJudged();
    const at = Math.max(0, Math.floor(Number(args[2]) || 0));
    const v = judge(round, args[1], at, elapsed);
    const claim = cj ? claimOf(args[3]) : null;
    const replayHeld = !v.bad;
    let win = !v.bad;
    let near;
    let foreignRest = false;
    if (cj) {
      // Cleanup bound only: minutes past the verses
      if (now > limitOf(round)) { v.bad = 'expired'; win = false; }
      // Still at the shrine (not for a faith prayed anywhere): within nearMeters, plus what the report's own lag lets a
      // worshipper who rose after the verdict cover (MG.lagReach; the lag is the server's time since it sent the round
      // less the widget's wait and hold, or for an old widget the server's time since the first press less its clock),
      // or where they were when their close arrived (review LAT-1)
      if (!v.bad || ORDINARY.has(v.bad)) {
        if (round.refId !== ANYWHERE_REF && Number(CFG.nearMeters) > 0 && typeof distanceMeters === 'function') {
          near = distanceMeters(a, round.refId);
          if (closed && Number(round.closeNear) < near) near = Number(round.closeNear);
          const wait = claim && Number.isFinite(claim.waitMs) ? claim.waitMs : round.waitMs;
          const held = claim && Number.isFinite(claim.durMs) ? claim.durMs : at;
          const reportLag = Number.isFinite(wait) ? sinceSent - wait - held : elapsed - at;
          if (!(near <= Number(CFG.nearMeters) + MG.lagReach(reportLag))) { v.bad = 'away'; win = false; }
        }
      }
      if (claim && (!v.bad || ORDINARY.has(v.bad))) {
        if (claim.win !== replayHeld) v.sus.push('mismatch');
        if (!claim.win) { win = false; if (!v.bad) v.bad = claim.why && ORDINARY.has(claim.why) ? claim.why : 'released'; }
        else if (!replayHeld) {
          // A claimed hold its own spans do not bear out: a forged report, or the widget and this file out of step
          audit(`PRAYER-MISMATCH ${who(a)} ${round.deityName} widget=held replay=${v.bad} worst=${v.worst} seed=${round.seed.toString(16)}`);
          if (MG.replayRefuses(CFG)) v.bad = 'mismatch';
          else { v.bad = ''; win = true; }
        }
      }
      // Humanly possible: a held prayer took the whole of its verses, on the widget's own clock and on the server's,
      // counted from when it SENT the round (lag only lengthens that)
      const own = claim && Number.isFinite(claim.durMs) ? claim.durMs : at;
      if (win && (own < round.totalMs - MG.floorAllowance(round.totalMs, CFG.clockSlackMs) || MG.serverTooSoon(sinceSent, round.totalMs, CFG.clockSlackMs))) { v.bad = 'fast'; win = false; }
      // One paid prayer per shrine per rest: a rest at this shrine that this round did not write itself means another
      // round here was judged first, so this one pays nothing and leaves that rest as it is (review F1, 2026-10-01)
      const until = Number(restsOf(a)[round.refId.toString(16)]) || 0;
      if (until > Date.now() && until !== round.restUntil) {
        foreignRest = true;
        if (win) { v.bad = 'rested'; win = false; }
      }
    }
    // One line per prayer: the verdict, how long the key was actually down against the round, the
    // worst uncovered verse (0 is a prayer never broken), the report's own clock and its lag; then who judged, the
    // widget's claim and its own figures, the distance to the shrine and any review flags. lag= decides nothing when
    // the widget judges.
    const extra = cj ? ` sinceOpen=${Math.round(sinceSent)}${claim ? ` dur=${Number.isFinite(claim.durMs) ? claim.durMs : '-'} wait=${Number.isFinite(claim.waitMs) ? claim.waitMs : Number.isFinite(round.waitMs) ? round.waitMs : '-'} blurs=${Number.isFinite(claim.blurs) ? claim.blurs : '-'} agree=${claim.win === replayHeld ? 'yes' : 'no'}` : ''}` : '';
    log(`prayer ${v.bad ? 'refused(' + v.bad + ')' : 'held'} ${display(a)} ${round.deityName} spans=${v.spans} held=${v.held}/${round.totalMs} worst=${v.worst} at=${v.at} lag=${v.lag} ${round.begun ? `started=${round.startedAt - round.openedAt}` : 'legacy'} seed=${round.seed.toString(16)}`
      + MG.tail({ judge: !cj ? 'server' : claim ? 'client' : 'legacy', min: cj ? round.totalMs : undefined, near: near !== undefined ? near : undefined, claim: cj ? (claim ? (claim.win ? 'held' : `lose${claim.why ? ':' + claim.why : ''}`) : null) : undefined, sus: v.sus.concat(closed ? [`after-${closed}`] : []) })
      + extra);
    // A verdict that lands after the panel was closed is told in chat; one after Stand up re-draws the open panel
    const show = closed === 'close' || closed === 'hidden' || round.hidden ? 'say' : 'widget';

    if (!win) {
      return finish(a, round, false, v.bad === 'rested' ? 'This shrine has already heard you. It gives nothing more for now.' : 'The verses slip away from you. The shrine gives nothing.', 'lose', !foreignRest, show);
    }

    const d = deityById(round.deityId);
    if (!d) return finish(a, round, false, 'The shrine is silent.', 'lose', !foreignRest, show);

    // The Priest is credited by the mastery system, which already has `prayer` in its candidate map
    // bound to priest - so nothing server-side needed rebuilding for this.
    if (PRAY.priestActivityPoint !== false) {
      try { if (typeof globalThis.__alduinakMasteryEvent === 'function') globalThis.__alduinakMasteryEvent('prayer', a, { refrId: round.refId }); } catch (e) { /* no skill system */ }
    }

    const tier = tierOf(a, 'priest');
    const odds = PRAY.blessingChance || {};
    const byTier = Array.isArray(odds.priestByTier) ? odds.priestByTier : [];
    // The faiths prayed to anywhere answer more rarely and more briefly (blessingChanceMult, blessingHoursMult)
    const chance = (tier >= 0 && byTier.length
      ? Number(byTier[Math.min(tier, byTier.length - 1)]) || 0
      : Number(odds.everyone) || 0) * (d.blessingChanceMult !== undefined ? Number(d.blessingChanceMult) : 1);
    const hours = (() => {
      const list = PRAY.blessingDurationHoursByTier || [];
      const i = Math.min(Math.max(tier, 0), Math.max(0, list.length - 1));
      return Math.max(1, Math.round((Number(list[i]) || 8) * (d.blessingHoursMult !== undefined ? Number(d.blessingHoursMult) : 1)));
    })();

    // An offering to this god within the hour raises the odds, up to double, and is spent by the prayer
    const offering = offeringOf(a);
    const favour = offering && offering.deityId === d.id ? 1 + Math.min(offering.gold, OFFER.fullGold) / OFFER.fullGold : 1;
    if (offering) { try { mp.set(a, 'private.dboOffering', null); } catch (e) { /* not an actor */ } }
    let text = `You hold the three verses. ${d.name} takes note, and no more.`;
    if (Math.random() < chance * favour) {
      if (grantBlessing(a, d, hours)) {
        text = `${d.name} answers. The blessing rests on you for ${hours} hours.`;
        audit(`PRAYER ${who(a)} received the blessing of ${d.name} (${hours} h, priest tier ${tier + 1})`);
      } else {
        text = `${d.name} answers, and the answer does not reach you.`;
      }
    }
    finish(a, round, true, text, 'win', true, show);
    try { if (globalThis.__dboSuperPrayed) globalThis.__dboSuperPrayed(a, d.id, { atShrine: round.refId !== ANYWHERE_REF }); } catch (e) { /* no curses */ }
  });

  const daysLeft = (faith) => {
    const last = Number(faith && (faith.convertedAt || faith.at)) || 0;
    const ms = last + CONVERSION_DAYS * 86400000 - Date.now();
    return ms > 0 ? Math.ceil(ms / 86400000) : 0;
  };

  // ── the picker ──────────────────────────────────────────────────────────────────────────────
  // The brief: "a deity picker after the race menu" and "you can only change deity once a week
  // IRL, by a menu key". So the first choice is free and needs no shrine - a character who has just
  // finished the race menu is standing in the hub - and a later change is gated only by the
  // cooldown, not by a pilgrimage. `/deity <name>` keeps the older at-the-shrine rule for anyone
  // who prefers to type; the menu is the path the brief asked for.
  const PICKER_ID = 36;
  const pickerNonce = globalThis.__dboDeityNonce || (globalThis.__dboDeityNonce = new Map());
  const offered = globalThis.__dboDeityOffered || (globalThis.__dboDeityOffered = new Set());

  const pickerPayload = (a, notice, noticeKind) => {
    const faith = faithOf(a);
    const nonce = `${a.toString(16)}-${Date.now().toString(36)}-${Math.floor(Math.random() * 1e9).toString(36)}`;
    pickerNonce.set(a, nonce);
    const left = faith ? daysLeft(faith) : 0;
    return {
      type: 'deityPicker', id: PICKER_ID, nonce,
      current: faith ? faith.id : '',
      first: !faith,
      daysLeft: left,
      cooldownDays: CONVERSION_DAYS,
      canChoose: !faith || left === 0,
      notice: notice || '',
      noticeKind: noticeKind || '',
      choices: DEITIES.map((d) => ({
        id: d.id, name: d.name, kind: d.kind,
        sphere: d.sphere || '', boon: d.boon || '',
        reachable: Number(d.inBruma) > 0 || !!d.prayAnywhere,
        lawful: d.lawful !== false,
        aspectOf: d.aspectOf || '',
      })),
    };
  };
  const openPicker = (a, notice, noticeKind) => {
    const first = !offered.has(a);
    offered.add(a);
    const ok = openWidget(a, pickerPayload(a, notice, noticeKind), true);
    if (first) log(`deity menu ${ok ? 'opened for' : 'REFUSED for'} ${display(a)}${faithOf(a) ? '' : ' (no god yet)'}`);
    return ok;
  };
  globalThis.__dboDeityPicker = (a) => openPicker(a);

  // The god is the last step of character creation (Jake's to-do, skippable by Nat's call, 2026-09-24). The gamemode
  // decides who is at that step (in the hub, creation done) and moves them on once they choose or press Not yet.
  const CREATION_NOTICE = 'The last step before you leave the Realm. Choose now, or press Not yet and type /deity whenever you are ready.';
  const creationStep = globalThis.__dboDeityCreationStep || (globalThis.__dboDeityCreationStep = new Set());
  const atCreationStep = (a) => typeof globalThis.__dboAtCreationEnd === 'function' && globalThis.__dboAtCreationEnd(a);
  const openCreationStep = (a) => {
    if (faithOf(a)) return false;
    creationStep.add(a);
    if (openPicker(a, CREATION_NOTICE, '')) return true;
    creationStep.delete(a);
    return false;
  };
  globalThis.__dboDeityCreationOpen = openCreationStep;
  const endCreationStep = (a) => {
    if (!creationStep.delete(a)) return;
    try { if (typeof globalThis.__dboCreationEndDone === 'function') globalThis.__dboCreationEndDone(a); } catch (e) { log('creation step end failed', e.message); }
  };

  // A character out of the race menu with no god gets the picker; so does an older character who
  // never had one, which is every character alive today. Watching for it beats hooking creation:
  // private.creationPending is cleared in a TS system with no gamemode callback, and this covers
  // the returning player as well as the new one.
  const OFFER_AFTER_MS = 15000;
  const offerReadySince = globalThis.__dboDeityReadySince || (globalThis.__dboDeityReadySince = new Map());
  every('deityPickerOffer', 7000, () => {
    for (const a of (api.onlineActors ? api.onlineActors() : [])) {
      try {
        if (offered.has(a) || faithOf(a)) continue;
        if (mp.get(a, 'private.creationPending') === true) continue;
        if (mp.get(a, 'appearance') == null) continue;
        // Someone who left mid-step comes back in the hub: this is still their last creation step
        if (atCreationStep(a)) openCreationStep(a);
        // Only asked for menus take the keyboard: this offer opened the picker with focus at every login, and players
        // without a god could not move until they closed it or tabbed out (2026-09-27). A chat line instead.
        else {
          // The line waits until the player has been in the world a while, or it can arrive before their chat is up and
          // be lost (release review PRAY-1)
          const since = offerReadySince.get(a);
          if (!since) { offerReadySince.set(a, Date.now()); continue; }
          if (Date.now() - since < OFFER_AFTER_MS) continue;
          offered.add(a); personal(a, 'You follow no god yet. Type /deity to choose one.'); log(`deity menu offered in chat to ${display(a)} (no god yet)`);
        }
      } catch (e) { /* not an actor yet */ }
    }
  });
  // Someone who logs out, mid-pick or before the offer reached them, is offered it again next time (gamemode.js calls this
  // on every logout)
  // The blessing's cast goes with the session too: the client does not keep it, and the next login casts it again.
  globalThis.__dboDeityForget = (a) => { offered.delete(a); offerReadySince.delete(a); pickerNonce.delete(a); creationStep.delete(a); blessCasts.delete(a); regenOwed.delete(a); fallen.delete(a); };

  // Taking or changing a god. `atShrine` is the older chat path's extra rule and is not applied to
  // the menu, because the brief moved conversion onto a menu key rather than a pilgrimage.
  const takeDeity = (a, d, opts) => {
    const faith = faithOf(a);
    if (faith && faith.id === d.id) return { ok: false, text: `You already follow ${d.name}.` };
    if (faith) {
      const left = daysLeft(faith);
      if (left) {
        const mine = deityById(faith.id);
        return { ok: false, text: `${mine ? mine.name : 'Your god'} is not so easily left. You may turn again in ${left} day${left === 1 ? '' : 's'}.` };
      }
    }
    if (opts && opts.atShrine) {
      const here = lastShrine.get(a);
      if (!here || here.deityId !== d.id || Date.now() - here.at > 30000) {
        return { ok: false, text: `You must stand at a shrine of ${d.name} and touch it, then say this again.` };
      }
    }
    if (faith) clearBlessing(a, null, 'turned');
    setFaith(a, {
      id: d.id, name: d.name, kind: d.kind,
      at: faith ? Number(faith.at) || Date.now() : Date.now(),
      convertedAt: Date.now(),
    });
    audit(`DEITY ${who(a)} ${faith ? 'turned to' : 'took'} ${d.name}`);
    return {
      ok: true, converted: !!faith,
      text: faith
        ? `You turn to ${d.name}. The blessing you carried falls away.`
        : `You take ${d.name} as your own.`,
    };
  };

  onUi('deityChoose', (a, args) => {
    if (String(args[0]) !== pickerNonce.get(a)) return;
    const d = deityByName(String(args[1] || ''));
    if (!d) return openWidget(a, pickerPayload(a, 'No god by that name.', 'refused'), false);
    const r = takeDeity(a, d);
    openWidget(a, pickerPayload(a, r.text, r.ok ? 'taken' : 'refused'), false);
    if (r.ok) {
      endCreationStep(a);
      const where = d.prayAnywhere
        ? `${d.name} needs no shrine: kneel anywhere and say /pray.`
        : Number(d.inBruma) > 0
          ? `Find a shrine of ${d.name} and use it to pray.`
          : `${d.name} has no shrine you can reach yet, so there is nowhere to pray until Skyrim opens.`;
      personal(a, where);
    }
  });
  onUi('deityClose', (a) => { pickerNonce.delete(a); closeWidget(a, PICKER_ID); endCreationStep(a); });

  // ── staff: set a character's god aside so they choose again (Nate 2026-09-30) ──────────────────────────────────────
  // Lead GM and above, like every staff override on a player's state (the property override, review A3-1; gamemode.js
  // LEAD_ONLY holds 'deity reset' for the command, and the panel's event checks the same here). It clears what belongs
  // to the god: the faith with its conversion clock, a blessing still running (its spell taken back), an offering
  // waiting, the shrine rests, a prayer in flight. It leaves curses, gold and everything else. There is no crime record
  // for worship to keep (the law's only trace is the faith's one-time warning); the old faith goes into
  // private.dboDeityHistory, and the audit line names who, whom and what.
  const onlineNow = (t) => (api.onlineActors ? api.onlineActors() : []).includes(t >>> 0);
  const resetDeity = (t, by) => {
    let faith = null, blessing = null, offering = null, rests = {};
    try {
      faith = faithOf(t); blessing = blessingOf(t); rests = restsOf(t);
      const o = mp.get(t, 'private.dboOffering'); offering = o && typeof o === 'object' ? o : null;
    } catch (e) { return { ok: false, text: `That character's record cannot be reached right now (${e.message}).` }; }
    const inFlight = sessions.has(t >>> 0);
    if (!faith && !blessing && !offering && !Object.keys(rests).length && !inFlight) return { ok: false, text: `${display(t)} follows no god; nothing to reset.` };
    const cleared = [];
    try {
      if (faith) {
        let hist = []; try { hist = mp.get(t, 'private.dboDeityHistory'); } catch (e) { hist = []; }
        const d = deityById(faith.id);
        const name = faith.name || (d && d.name) || faith.id;
        mp.set(t, 'private.dboDeityHistory', (Array.isArray(hist) ? hist : []).concat([{ id: faith.id, name, from: Number(faith.at) || 0, to: Date.now(), resetBy: by }]).slice(-20));
        // Raw writes, not setFaith / clearBlessing: those swallow a failed write, and a reset must not audit as cleared
        // what was not (Worker D's review)
        mp.set(t, 'private.dboDeity', null);
        cleared.push(`${name}, with its conversion clock`);
      }
      if (blessing) {
        const bd = deityById(blessing.deity);
        if (blessing.spell && blessing.via !== 'cast') castSpell(t, Number(blessing.spell) >>> 0, false);
        mp.set(t, 'private.dboBlessing', null);
        blessCasts.delete(t >>> 0);
        regenOwed.delete(t >>> 0);
        // A cast blessing's effect ends on the client of a worshipper who is online; an offline one's went with the session
        if (blessing.spell && blessing.via === 'cast' && onlineNow(t)) dispelOnSelf(t >>> 0, Number(blessing.spell) >>> 0, 'reset');
        cleared.push(`the blessing of ${bd ? bd.name : blessing.deity}`);
      }
      if (offering) { mp.set(t, 'private.dboOffering', null); cleared.push(`an offering of ${Number(offering.gold) || 0} gold`); }
      if (Object.keys(rests).length) { mp.set(t, 'private.prayedShrines', {}); cleared.push('the shrine rests'); }
    } catch (e) {
      audit(`DEITY ${by} reset of ${who(t)} FAILED part-way (${e.message}); cleared before it: ${cleared.join('; ') || 'nothing'}`);
      return { ok: false, text: `The reset of ${display(t)} failed part-way (${e.message}). Cleared before it: ${cleared.join('; ') || 'nothing'}.` };
    }
    if (inFlight) { sessions.delete(t >>> 0); try { closeWidget(t, WIDGET_ID); } catch (e) { /* offline */ } cleared.push('a prayer in progress'); }
    lastShrine.delete(t >>> 0); offered.delete(t >>> 0); offerReadySince.delete(t >>> 0); pickerNonce.delete(t >>> 0);
    const online = onlineNow(t);
    if (online) {
      try { closeWidget(t, PICKER_ID); } catch (e) { /* not open */ }
      personal(t, 'The staff have set your faith aside. You may choose a god again: type /deity, or kneel at a shrine.');
    }
    audit(`DEITY ${by} reset ${who(t)}: ${cleared.join('; ')}`);
    log(`prayer: ${by} reset the god of ${display(t)} (${cleared.join('; ')})${online ? '' : ', offline'}`);
    return { ok: true, text: `${display(t)}: cleared ${cleared.join('; ')}.${online ? ' They were told.' : ' They are offline and will be offered the choice when they return.'}` };
  };
  // Who a staff reset is aimed at: the panel's live actor, else a name or #TAG (offline characters included)
  const resetTarget = (q) => {
    if (typeof findAnyByName !== 'function') return { t: 0, why: 'the character lookup is not loaded' };
    const t = findAnyByName(String(q || '').trim());
    if (t < 0) return { t: 0, why: `${-t} characters are called "${q}". Use their #TAG.` };
    if (!t) return { t: 0, why: `No character matches "${q}".` };
    return { t: t >>> 0 };
  };
  const staffReset = (a, q, reply) => {
    if (typeof isLeadStaff !== 'function' || !isLeadStaff(a)) {
      audit(`DEITY ${who(a)} was refused a deity reset of "${String(q).slice(0, 60)}" (Lead GM and above)`);
      return reply(false, 'That is for a Lead GM and above.');
    }
    if (!String(q || '').trim()) return reply(false, 'Usage: /deity reset <character name or #TAG>');
    const found = resetTarget(q);
    if (!found.t) return reply(false, found.why);
    const r = resetDeity(found.t, who(a));
    return reply(r.ok, r.text);
  };
  // An offline row's character: the name, narrowed by the row's profile when two characters share it (the panel has no
  // #TAG to offer, Worker D's review)
  const byNameAndProfile = (name, profile) => {
    if (!(profile > 0)) return 0;
    let ids = []; try { ids = mp.findFormsByPropertyValue('private.indexed.nameKey', String(name).trim().toLowerCase()) || []; } catch (e) { return 0; }
    const mine = ids.map((x) => Number(x) >>> 0).filter((x) => { try { return Number(mp.get(x, 'profileId')) === profile; } catch (e) { return false; } });
    return mine.length === 1 ? mine[0] : 0;
  };
  // The admin panel's player tab (front extraTabs DeityReset): [live actor hex or '', character name, profile id]. Answered
  // the way AdminSystem answers the panel's own actions, so the result shows in the panel.
  onUi('deityReset', (a, args) => {
    const hex = String((args || [])[0] || '').trim();
    const name = String((args || [])[1] || '').trim();
    const profile = Number((args || [])[2]) || 0;
    const reply = (ok, text) => { try { sendPacket(a, { customPacketType: 'adminActionResult', ok: !!ok, text }); } catch (e) { personal(a, text); } };
    if (/^[0-9a-f]{1,8}$/i.test(hex)) {
      const t = parseInt(hex, 16) >>> 0;
      let isCharacter = false; try { isCharacter = !!mp.get(t, 'private.indexed.tagKey'); } catch (e) { isCharacter = false; }
      if (isCharacter) {
        if (typeof isLeadStaff !== 'function' || !isLeadStaff(a)) return staffReset(a, name || hex, reply);
        const r = resetDeity(t, who(a));
        return reply(r.ok, r.text);
      }
    }
    const own = name ? byNameAndProfile(name, profile) : 0;
    if (own && typeof isLeadStaff === 'function' && isLeadStaff(a)) { const r = resetDeity(own, who(a)); return reply(r.ok, r.text); }
    return staffReset(a, name, reply);
  });

  // ── /deity ──────────────────────────────────────────────────────────────────────────────────
  // The chat path, kept for anyone who would rather type than click. Bare `/deity` opens the menu.
  registerChatCommand('deity', (a, argStr) => {
    const faith = faithOf(a);
    const arg = String(argStr || '').trim();
    // Staff: /deity reset <character> (Lead GM and above; gamemode.js refuses a GM before this runs)
    if (/^reset(\s|$)/i.test(arg)) return staffReset(a, arg.replace(/^reset\s*/i, ''), (ok, text) => personal(a, text));
    if (!arg) {
      // Bare /deity is the menu key the brief asked for, until there is a real one.
      if (openPicker(a)) return;
      const mine = faith ? deityById(faith.id) : null;
      personal(a, mine
        ? `You follow ${mine.name} - ${mine.boon || 'no boon recorded'}${daysLeft(faith) ? ` You may turn to another god in ${daysLeft(faith)} day(s).` : ' You may turn to another god.'}`
        : 'You hold no god.');
      const list = (kind) => DEITIES.filter((d) => d.kind === kind)
        .map((d) => d.name + (Number(d.inBruma) > 0 || d.prayAnywhere ? '' : '*')).join(', ');
      personal(a, `Divines: ${list('divine')}`);
      personal(a, `Daedra: ${list('daedra')}`);
      personal(a, `Other faiths (pray anywhere with /pray): ${list('faith')}`);
      personal(a, '* no shrine you can reach yet.');
      return;
    }
    const d = deityByName(arg);
    if (!d) return personal(a, `No god by that name. Say /deity on its own for the list.`);
    // Naming a god you do not follow, away from its shrine, reads as a question rather than a vow.
    if (!faith || faith.id !== d.id) {
      const here = lastShrine.get(a);
      if (!here || here.deityId !== d.id || Date.now() - here.at > 30000) {
        if (d.sphere) personal(a, `${d.name}. ${d.sphere}`);
        if (d.boon) personal(a, `Boon: ${d.boon}${Number(d.inBruma) > 0 || d.prayAnywhere ? '' : ' (no shrine you can reach yet)'}`);
      }
    }
    // The chat path keeps the pilgrimage: naming a god here means saying it at their shrine. The
    // menu does not, per the brief. A character with no god yet is not asked to walk anywhere.
    const r = takeDeity(a, d, { atShrine: !!faith && !d.prayAnywhere });
    personal(a, r.text);
  }, { help: 'open the deity menu; /deity <name> at that god\'s shrine to turn by hand; staff: /deity reset <player>' });

  // A blessing id that does not resolve is silent: the prayer succeeds, the roll lands and the
  // worshipper is told the god "gives no sign". Count them at boot so a mistyped form id shows up
  // in the log rather than in somebody's play session.
  // How each resolved blessing will be given (see the blessings block): cast on the worshipper, or learned (an Ability, a
  // Power, or a record the server could not read, which keeps AddSpell)
  const blessingCheck = (() => {
    const out = { ok: 0, server: 0, broken: [], cast: 0, learned: 0, unread: [] };
    for (const d of DEITIES) {
      if (d.blessingSource === 'server') { out.server++; continue; }
      const id = blessingIdOf(d);
      if (!id) { out.broken.push(d.name); continue; }
      out.ok++;
      const info = spellInfo(id);
      if (!info) out.unread.push(d.name); else if (info.cast) out.cast++; else out.learned++;
    }
    return out;
  })();
  if (blessingCheck.broken.length) log(`prayer: ${blessingCheck.broken.length} blessing(s) do not resolve: ${blessingCheck.broken.join(', ')}`);

  const reachable = DEITIES.filter((d) => Number(d.inBruma) > 0 || d.prayAnywhere).length;
  log(`prayer ${CFG.enabled ? 'on' : 'off'}: ${DEITIES.length} deities, ${shrineIndex().size} shrine ids, ${reachable} reachable under the region lock; ${VERSES} verses of ${VERSE_MS} ms, ${SLACK_MS} ms slack, ${Math.round(SHRINE_COOLDOWN_MS / 60000)} min per shrine, conversion every ${CONVERSION_DAYS} day(s); blessings ${blessingCheck.ok} resolved (${blessingCheck.cast} cast on the worshipper, ${blessingCheck.learned} learned${blessingCheck.unread.length ? `, ${blessingCheck.unread.length} unreadable and learned: ${blessingCheck.unread.join(', ')}` : ''}), ${blessingCheck.server} server-side, ${blessingCheck.broken.length} broken`);
  // Which blessings the regeneration tick holds, read as it reads them (the release check looks for this line)
  const regenHeld = DEITIES.map((d) => {
    const list = (blessingIdOf(d) ? spellRegen(blessingIdOf(d)) : []).concat(deityRegen(d));
    return list.length ? `${d.id} ${list.map((e) => `${e.av} +${+e.mag.toFixed(2)}`).join(' ')}` : '';
  }).filter(Boolean);
  log(`prayer: regeneration held by the server ${REGEN.enabled !== false ? `every ${REGEN_TICK_MS / 1000} s` : '(off)'}, regenerationMultiplier ${REGEN_MULT}: ${regenHeld.join(', ') || 'none'}`);
};
