// Shrines, deities and prayer, loaded by gamemode.js like labour.js and dungeons.js.
// A shrine belongs to a deity; a character belongs to one deity at a time and may only pray at
// their own. Praying is a mini-game: the server issues three verses and the worshipper holds the
// prayer key through all three. A completed prayer credits the Priest skill and rolls, rarely, for
// the shrine's blessing.
//
// The round is the server's, exactly as in labour.js and the reading game (SERVER_AUTHORITY.md
// migration 7). The server rolls the verses and their windows and sends them; the widget renders
// them and reports WHEN the key was down, never whether the prayer held. The server replays the
// windows against those spans and decides for itself, so editing the widget changes what the
// worshipper sees and not what the gods give.
//
//   Browser -> client -> server: sendMessage('dbo:prayer', nonce, JSON.stringify(spans), atMs)
//   Escape / stand up:           sendMessage('dbo:prayerCancel', nonce)
//
// Data: skills.json `deities` (the choices, their shrine BASE ids and blessing spells) and `praying`
// (odds, durations, cooldown, the verse count). Shrine ids are base objects, never references: one
// deity has many statues. Which of them a player can actually reach is measured, not assumed -
// server\shrine-placements.json, regenerated by `py ck-mcp\shrines.py`.
'use strict';

module.exports = (api) => {
  const { mp, log, personal, audit, display, who, cfg, openWidget, closeWidget, onUi, registerChatCommand, skills, every } = api;

  const WIDGET_ID = 35;
  const CFG = Object.assign({
    enabled: true,
    // How long the whole prayer runs, and how far the report's clock may drift from the server's.
    // Same reasoning as labour.js: the packet out, the browser mount, the report back.
    lagGraceMs: 2500,
    clockSlackMs: 50,
    // Uncovered milliseconds a single verse forgives. A prayer is a hold, not a rhythm test, so
    // this is generous - it exists to forgive the gap between two key repeats, not a lapse.
    holdSlackMs: 500,
    // A hand must be on the key from the start; dawdling past this is not a prayer.
    startGraceMs: 1500,
    failRestMinutes: 5,
  }, cfg.prayer || {});

  const PRAY = Object.assign({}, skills.praying || {});
  const DEITIES = (skills.deities || {}).choices || [];
  const CONVERSION_DAYS = Math.max(0, Number((skills.deities || {}).conversionCooldownDays) || 7);
  const VERSES = Math.max(1, Math.round(Number(PRAY.verses) || 3));
  const VERSE_MS = Math.max(1000, Math.round((Number(PRAY.verseSeconds) || 6) * 1000));
  const SLACK_MS = Math.max(0, Math.round(Number(PRAY.holdSlackMs ?? CFG.holdSlackMs)));
  const SHRINE_COOLDOWN_MS = Math.max(0, Math.round((Number(PRAY.cooldownMinutesPerShrine) || 60) * 60000));

  // Rounds outlive a gamemode reload, or every save would strand a prayer in flight
  const sessions = globalThis.__dboPrayerRounds || (globalThis.__dboPrayerRounds = new Map()); // actorId -> round
  const spent = globalThis.__dboPrayerSpent || (globalThis.__dboPrayerSpent = new Map());      // nonce -> when judged
  const lastShrine = globalThis.__dboPrayerLastShrine || (globalThis.__dboPrayerLastShrine = new Map()); // actorId -> { deityId, at }
  const denied = new Map();

  const nowMs = () => performance.now();   // the round clock is monotonic; Date.now() can be stepped
  const idOf = (desc) => { try { return mp.getIdFromDesc(String(desc)) >>> 0; } catch (e) { return 0; } };
  const baseIdOf = (targetId) => { try { return idOf(mp.get(targetId, 'baseDesc')); } catch (e) { return 0; } };
  const baseRecord = (baseId) => { try { return mp.lookupEspmRecordById(baseId); } catch (e) { return null; } };
  const deny = (a, text) => {
    if (Date.now() - (denied.get(a) || 0) > 1500) { denied.set(a, Date.now()); personal(a, text); }
    return true;
  };

  const masteryOf = (a) => { try { const r = mp.get(a, 'private.mastery'); return r && typeof r === 'object' ? r : null; } catch (e) { return null; } };
  // -1 when the character does not hold the skill at all, otherwise the rank as a 0 based tier
  const tierOf = (a, skillId) => {
    const r = masteryOf(a);
    if (!r || !Array.isArray(r.order) || !r.order.includes(skillId)) return -1;
    const p = r.skills && r.skills[skillId];
    return p ? Math.max(0, Number(p.rank) || 0) : 0;
  };

  // ── the shrine index ────────────────────────────────────────────────────────────────────────
  // A shrine in skills.json may be named either way round, and both are deliberate: most deities
  // name the base ACTI, so every statue of that god counts, while the Daedric activators placed on
  // 2026-09-14 name single REFRs on purpose (CHECKLIST: "Meridia uses the vanilla Kilkreath
  // activator 4e4d6"), so one statue counts and its neighbours do not. A form id is one or the
  // other, never both, so indexing every id under both keys costs nothing and cannot collide: a
  // base id will never equal a reference the player touched, and a reference id will never equal
  // the base behind one.
  let SHRINES = null;
  const shrineIndex = () => {
    if (SHRINES) return SHRINES;
    SHRINES = new Map();
    let bad = 0;
    for (const d of DEITIES) {
      for (const s of d.shrines || []) {
        const id = idOf(s);
        if (!id) { bad++; log(`prayer: ${d.name} shrine ${s} does not resolve`); continue; }
        if (SHRINES.has(id)) { log(`prayer: shrine ${s} is claimed by both ${SHRINES.get(id).name} and ${d.name}; ${SHRINES.get(id).name} keeps it`); continue; }
        SHRINES.set(id, d);
      }
    }
    log(`prayer: ${SHRINES.size} shrine id(s) across ${DEITIES.length} deities${bad ? `, ${bad} unresolved` : ''}`);
    return SHRINES;
  };
  // The reference the player touched wins over the base behind it, so a deity that claims one
  // statue is not overruled by a deity that claims every statue of that model.
  const shrineAt = (targetId, baseId) => shrineIndex().get(targetId) || (baseId ? shrineIndex().get(baseId) : null);

  const deityByName = (s) => {
    const q = String(s || '').trim().toLowerCase().replace(/[^a-z]/g, '');
    if (!q) return null;
    return DEITIES.find((d) => d.id === q || d.name.toLowerCase().replace(/[^a-z]/g, '') === q) || null;
  };
  const deityById = (id) => DEITIES.find((d) => d.id === id) || null;
  // Auri-El is not a second god, he is Akatosh under the Aldmeri name, and skills.json says so with
  // `aspectOf`. Two ids are the same faith if either is an aspect of the other, so a worshipper of
  // one may kneel at the other's shrine - which is the only way a Snow-Elf-faithed character gets to
  // pray at all, Auri-El's one shrine being in the Forgotten Vale.
  const sameFaith = (a, b) => {
    if (!a || !b) return false;
    if (a.id === b.id) return true;
    return a.aspectOf === b.id || b.aspectOf === a.id || (!!a.aspectOf && a.aspectOf === b.aspectOf);
  };

  // ── what a character worships ───────────────────────────────────────────────────────────────
  const faithOf = (a) => { try { const r = mp.get(a, 'private.dboDeity'); return r && typeof r === 'object' && r.id ? r : null; } catch (e) { return null; } };
  const setFaith = (a, v) => { try { mp.set(a, 'private.dboDeity', v); } catch (e) { log('prayer: faith save failed', e.message); } };
  const restsOf = (a) => { try { const r = mp.get(a, 'private.prayedShrines'); return r && typeof r === 'object' ? r : {}; } catch (e) { return {}; } };
  const saveRests = (a, rests) => {
    for (const k of Object.keys(rests)) if (Number(rests[k]) < Date.now()) delete rests[k];
    try { mp.set(a, 'private.prayedShrines', rests); } catch (e) { log('prayer: rest save failed', e.message); }
  };

  // ── blessings ───────────────────────────────────────────────────────────────────────────────
  // AddSpell/RemoveSpell are Actor methods and the worshipper is a player, so the call lands
  // (the memory note `papyrus-calls-only-reach-player-actors`: unregistered methods on a
  // server-spawned NPC log and return None, but a player actor is fine).
  const castSpell = (a, spellId, add) => {
    if (!spellId) return false;
    try {
      const self = { type: 'form', desc: mp.getDescFromId(a) };
      const spell = { type: 'espm', desc: mp.getDescFromId(spellId) };
      mp.callPapyrusFunction('method', 'Actor', add ? 'AddSpell' : 'RemoveSpell', self, add ? [spell, false] : [spell]);
      return true;
    } catch (e) { log(`prayer: could not ${add ? 'grant' : 'revoke'} ${spellId.toString(16)}: ${e.message}`); return false; }
  };
  const blessingIdOf = (d) => {
    const s = String(d && d.blessing || '');
    return /^[0-9a-f]+:/i.test(s) ? idOf(s) : 0;     // "<author: ...>" placeholders resolve to 0
  };
  const blessingOf = (a) => { try { const b = mp.get(a, 'private.dboBlessing'); return b && typeof b === 'object' && b.until ? b : null; } catch (e) { return null; } };
  const clearBlessing = (a, why) => {
    const b = blessingOf(a);
    if (!b) return;
    if (b.spell) castSpell(a, Number(b.spell) >>> 0, false);
    try { mp.set(a, 'private.dboBlessing', null); } catch (e) { /* gone with the character */ }
    if (why) personal(a, why);
  };
  // Sheogorath has no blessing of his own and should not have one. The Madgod gives what he feels
  // like, so his worshipper is handed another god's blessing at random - a different one each time.
  // This is the only boon in the list that is more lore-accurate as code than as a record, and it is
  // the only one that needed no Creation Kit work at all. skills.json marks him `capricious: true`.
  const capriceOf = (d) => {
    const pool = DEITIES.filter((x) => x.id !== d.id && (blessingIdOf(x) || x.hungerHalf));
    return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
  };

  const grantBlessing = (a, d, hours) => {
    if (d.capricious) {
      const other = capriceOf(d);
      if (!other) { personal(a, `${d.name} laughs, and gives you nothing. He may have meant to.`); return false; }
      const got = grantBlessing(a, other, hours);
      if (got) personal(a, `${d.name} rummages, and hands you the blessing of ${other.name}. He seems delighted.`);
      return got;
    }
    const spell = blessingIdOf(d);
    // A boon does not have to be a spell. Sanguine's is a change to the appetite meter and has no
    // record at all, so "no spell" is only a failure when the deity has nothing server-side either.
    const serverSide = !!d.hungerHalf;
    clearBlessing(a, null);
    if (!spell && !serverSide) {
      // Every Prince still waiting on its SPEL lands here. The prayer succeeded and counted; there
      // is simply nothing to hand over yet.
      personal(a, `${d.name} hears you, and gives no sign. (No blessing exists for ${d.name} yet.)`);
      log(`prayer: ${display(a)} earned a blessing from ${d.name}, which has no spell record`);
      return false;
    }
    if (spell && !castSpell(a, spell, true)) return false;
    const until = Date.now() + Math.max(1, hours) * 3600000;
    try { mp.set(a, 'private.dboBlessing', { deity: d.id, spell, until }); } catch (e) { /* not fatal */ }
    return true;
  };

  // Sanguine's boon is not a spell and could not be one: the Prince of indulgence belongs on the
  // appetite meter, and appetite is the gamemode's (private.needs), not the engine's. The needs tick
  // multiplies its hunger step by this, so a blessed worshipper feasts and does not pay for it.
  // Persuasion, which he had before, does nothing at all on a server with no NPCs to persuade.
  globalThis.__dboPrayerHungerMult = (a) => {
    try {
      const b = blessingOf(a);
      if (!b || Number(b.until) <= Date.now()) return 1;
      const d = deityById(b.deity);
      return d && d.hungerHalf ? 0.5 : 1;
    } catch (e) { return 1; }
  };

  // A blessing is worn, not held: nothing else expires it, so the module does.
  every('prayerBlessings', 60000, () => {
    for (const a of (api.onlineActors ? api.onlineActors() : [])) {
      const b = blessingOf(a);
      if (b && Number(b.until) <= Date.now()) {
        const d = deityById(b.deity);
        clearBlessing(a, `The blessing of ${d ? d.name : 'your god'} fades.`);
      }
    }
  });

  // ── the verses ──────────────────────────────────────────────────────────────────────────────
  // Three lines, the middle one drawn from the deity's own if it has any. Nothing here is judged;
  // the text only gives the worshipper something to hold the key through.
  const COMMON = [
    'Hear me, for I have walked far to stand here',
    'I bring no gold, only the hours of my hands',
    'Let the road ahead be no kinder than I have earned',
    'What was given I have not squandered',
    'I ask nothing that another must go without',
    'Keep my name where you can find it again',
  ];
  const OWN = {
    akatosh: ['Time turns, and I turn with it', 'The dragon does not hurry and neither shall I'],
    arkay: ['The dead are counted and none are lost', 'I will meet my hour without argument'],
    dibella: ['Let me see the world as it deserves to be seen', 'Beauty is not owed to me, but I will look for it'],
    julianos: ['What I do not know, let me learn honestly', 'Wisdom is slow and I am willing'],
    kynareth: ['The wind is older than the road', 'I take from the land only what grows back'],
    mara: ['Let me be the one who stays', 'Mercy costs nothing and I have little else'],
    stendarr: ['Strength without mercy is only weight', 'Stand between the weak and the world'],
    talos: ['A man became a god and did not forget', 'The Empire forgets, the North remembers'],
    zenithar: ['An honest trade leaves both hands full', 'Work first, and the coin will follow'],
    auriel: ['The snow remembers the ones who kept faith', 'Light bends but does not break'],
    malacath: ['The scorned do not beg', 'Broken and kept, that is the bargain'],
    nocturnal: ['What the dark holds it does not give back', 'Luck is a debt and I will pay it'],
    azura: ['Dusk and dawn are the same door', 'Show me the shape of what comes'],
    boethiah: ['Take by strength what deceit could not hold', 'The teacher is the one still standing'],
    mephala: ['Every thread pulls another', 'What is said in the dark is still said'],
    clavicusvile: ['Name the price and I will hear the rest', 'A bargain is a promise with teeth'],
    hermaeusmora: ['What is known cannot be unknown again', 'I come to be read as much as to read'],
    hircine: ['Let the chase be long and the ending quick', 'There is no hunter who is not also game'],
    mehrunes: ['What stands has stood long enough', 'Tear it down and see what was beneath'],
    meridia: ['The dead should stay where they were put', 'Light does not forgive, it only shines'],
    molagbal: ['Everything that lives belongs to something', 'Kneel early and it is over sooner'],
    namira: ['Praise what the others turn their faces from', 'In the dark nothing is ugly'],
    peryite: ['Everything rots, and in its proper order', 'Even the least thing is given its task'],
    sanguine: ['One more, and then one more after that', 'Nothing was ever regretted before morning'],
    sheogorath: ['I asked a question and the answer was a fish', 'Cheese for everyone, and none for me'],
    vaermina: ['Take the dream and leave me the waking', 'I remember a thing that never happened'],
  };
  const verseFor = (d, i, rand) => {
    const own = OWN[d.id] || [];
    if (i === 1 && own.length) return own[Math.floor(rand() * own.length)];
    return COMMON[Math.floor(rand() * COMMON.length)];
  };

  const rngOf = (seed) => {
    let s = seed >>> 0;
    return () => {
      s = (s + 0x6d2b79f5) >>> 0;
      let t = Math.imul(s ^ (s >>> 15), s | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  };

  const roundFor = (a, d, refId, shrineName) => {
    const seed = (Math.floor(Math.random() * 0xffffffff) >>> 0);
    const rand = rngOf(seed);
    const verses = [];
    for (let i = 0; i < VERSES; i++) {
      verses.push({ text: verseFor(d, i, rand), startMs: i * VERSE_MS, endMs: (i + 1) * VERSE_MS });
    }
    return {
      nonce: `${a.toString(16)}-${Date.now().toString(36)}-${Math.floor(Math.random() * 1e9).toString(36)}`,
      deityId: d.id, deityName: d.name, kind: d.kind, refId, shrineName, seed, verses,
      totalMs: VERSES * VERSE_MS, slackMs: SLACK_MS, startGraceMs: CFG.startGraceMs,
      startedAt: 0,
    };
  };

  // Everything the widget needs to draw the prayer, and nothing it could use to judge it
  const packetFor = (round, result, resultKind) => {
    const w = {
      type: 'prayer', id: WIDGET_ID, nonce: round.nonce,
      deity: round.deityName, kind: round.kind, shrine: round.shrineName,
      verses: round.verses, totalMs: round.totalMs,
    };
    if (result) { w.result = result; w.resultKind = resultKind; }
    return w;
  };

  const startRound = (a, round) => {
    sessions.set(a, round);
    round.startedAt = nowMs();
    if (!openWidget(a, packetFor(round), true)) sessions.delete(a);
    return true;
  };

  const liveRound = (a) => {
    const r = sessions.get(a);
    if (!r) return null;
    if (nowMs() - r.startedAt <= r.totalMs + CFG.lagGraceMs) return r;
    sessions.delete(a);
    return null;
  };

  const finish = (a, round, win, text, kind, rest) => {
    if (rest !== false) {
      const rests = restsOf(a);
      rests[round.refId.toString(16)] = Date.now() + (win ? SHRINE_COOLDOWN_MS : CFG.failRestMinutes * 60000);
      saveRests(a, rests);
    }
    openWidget(a, packetFor(round, text, kind), false);
    sessions.delete(a);
    spent.set(round.nonce, Date.now());
    for (const [n, t] of spent) if (Date.now() - t > 600000) spent.delete(n);
  };

  // ── the activate hook ───────────────────────────────────────────────────────────────────────
  // Called from the gamemode's activate chain; true means the activation was ours. A target that is
  // not a shrine returns false and the chain carries on - see the memory note
  // `gamemode-activate-chain-runs-before-systems`: a refusal that returns true stops every gate
  // below it, which is how labour.js once made its own skill impossible to open.
  globalThis.__dboPrayerActivate = (targetId, casterId) => {
    if (!CFG.enabled || targetId >= 0xff000000) return false;
    const baseId = baseIdOf(targetId);
    const d = shrineAt(targetId, baseId);
    if (!d) return false;

    // From here on the target IS a shrine: the vanilla blessing must not fire whatever we answer.
    lastShrine.set(casterId, { deityId: d.id, at: Date.now() });
    if (liveRound(casterId)) return true;

    const faith = faithOf(casterId);
    if (!faith) {
      return deny(casterId, `This is a shrine of ${d.name}. You hold no god yet - say "/deity ${d.name}" here to take ${d.name} as your own.`);
    }
    const mine = deityById(faith.id);
    if (PRAY.onlyOwnDeity !== false && !sameFaith(mine, d)) {
      return deny(casterId, `${d.name} has no ear for a follower of ${mine ? mine.name : 'another god'}. Find your own shrine, or say "/deity ${d.name}" here to turn.`);
    }
    const until = Number(restsOf(casterId)[targetId.toString(16)]) || 0;
    if (until > Date.now()) {
      const mins = Math.ceil((until - Date.now()) / 60000);
      return deny(casterId, `You have prayed here recently. This shrine will hear you again in ${mins} minute${mins === 1 ? '' : 's'}.`);
    }
    // Bruma is Imperial. The White-Gold Concordat outlawed Talos, and Daedra worship has always been
    // proscribed - Beyond Skyrim has already renamed the Great Chapel of Talos to the Cathedral of
    // St Martin for exactly this reason. Said once per character, and nothing follows from it: no
    // guard reads `lawful`, deliberately. Whether the law has teeth is a faction decision.
    if (d.lawful === false && !faith.warnedUnlawful) {
      faith.warnedUnlawful = true;
      setFaith(casterId, faith);
      personal(casterId, d.kind === 'divine'
        ? 'You kneel to Talos in an Imperial county. The Concordat calls that a crime, and the Thalmor keep a Justiciar in Bruma. Nobody stops you.'
        : `You kneel to a Prince in an Imperial county. ${d.name} is proscribed here, and the shrine is hidden for a reason. Nobody stops you.`);
    }
    const rec = baseId ? baseRecord(baseId) : null;
    const shrineName = (rec && rec.record && rec.record.name) || `Shrine of ${d.name}`;
    return startRound(casterId, roundFor(casterId, d, targetId, shrineName));
  };

  // ── judging ─────────────────────────────────────────────────────────────────────────────────
  // The report is a list of [down, up] spans on the widget's clock, in ms from the moment it
  // mounted. Everything the verdict needs is in those numbers and the round the server already
  // holds; nothing the widget says about its own success is read.
  const judge = (round, raw, at, elapsed) => {
    const r = { spans: 0, held: 0, covered: 0, worst: 0, late: 0, at, lag: Math.round(elapsed - at), bad: '' };
    let list = [];
    try { list = JSON.parse(String(raw)); } catch (e) { r.bad = 'parse'; return r; }
    if (!Array.isArray(list)) { r.bad = 'shape'; return r; }
    if (list.length > 64) { r.bad = 'count'; return r; }

    let prevEnd = -1;
    for (const span of list) {
      if (!Array.isArray(span) || span.length !== 2) { r.bad = 'shape'; return r; }
      const down = Number(span[0]), up = Number(span[1]);
      if (!Number.isInteger(down) || !Number.isInteger(up)) { r.bad = 'shape'; return r; }
      if (down < 0 || up > round.totalMs || up < down) { r.bad = 'range'; return r; }
      if (down < prevEnd) { r.bad = 'overlap'; return r; }   // the spans also order themselves
      prevEnd = up;
      r.spans++; r.held += up - down;
    }
    if (prevEnd > at) { r.bad = 'submit'; return r; }        // a key still down after the report went out
    // The widget's clock may sit behind the server's by the transport, never ahead of it, and a
    // round played out in slow motion and scaled back down is the one cheat the coverage check
    // alone would not see. Same two bounds labour.js uses.
    if (r.lag < -CFG.clockSlackMs) { r.bad = 'future'; return r; }
    if (r.lag > CFG.lagGraceMs) { r.bad = 'late'; return r; }

    const first = list.length ? Number(list[0][0]) : Infinity;
    if (first > round.startGraceMs) { r.late = first; r.bad = 'slow'; return r; }

    // Coverage, verse by verse: the worst gap decides, so one lapse cannot be averaged away by two
    // verses held perfectly.
    for (const v of round.verses) {
      let inside = 0;
      for (const [down, up] of list) inside += Math.max(0, Math.min(up, v.endMs) - Math.max(down, v.startMs));
      const gap = (v.endMs - v.startMs) - inside;
      r.covered += inside;
      r.worst = Math.max(r.worst, gap);
    }
    if (r.worst > round.slackMs) r.bad = 'released';
    return r;
  };

  onUi('prayerCancel', (a, args) => {
    const round = sessions.get(a);
    if (!round || String(args[0]) !== round.nonce) return;
    finish(a, round, false, 'You rise before the third verse. The shrine is silent.', 'lose');
  });

  onUi('prayer', (a, args) => {
    const round = sessions.get(a);
    if (!round || String(args[0]) !== round.nonce) {
      if (spent.has(String(args[0]))) log(`prayer replay ${display(a)}: ${String(args[0]).slice(0, 40)} was already judged`);
      return;
    }
    const elapsed = nowMs() - round.startedAt;
    const v = judge(round, args[1], Math.max(0, Math.floor(Number(args[2]) || 0)), elapsed);
    const win = !v.bad;
    // One line per prayer: the verdict, how long the key was actually down against the round, the
    // worst uncovered verse (0 is a prayer never broken), the report's own clock and its lag.
    log(`prayer ${v.bad ? 'refused(' + v.bad + ')' : 'held'} ${display(a)} ${round.deityName} spans=${v.spans} held=${v.held}/${round.totalMs} worst=${v.worst} at=${v.at} lag=${v.lag} seed=${round.seed.toString(16)}`);

    if (!win) {
      return finish(a, round, false, 'The verses slip away from you. The shrine gives nothing.', 'lose');
    }

    const d = deityById(round.deityId);
    if (!d) return finish(a, round, false, 'The shrine is silent.', 'lose');

    // The Priest is credited by the mastery system, which already has `prayer` in its candidate map
    // bound to priest - so nothing server-side needed rebuilding for this.
    if (PRAY.priestActivityPoint !== false) {
      try { if (typeof globalThis.__alduinakMasteryEvent === 'function') globalThis.__alduinakMasteryEvent('prayer', a, { refrId: round.refId }); } catch (e) { /* no skill system */ }
    }

    const tier = tierOf(a, 'priest');
    const odds = PRAY.blessingChance || {};
    const byTier = Array.isArray(odds.priestByTier) ? odds.priestByTier : [];
    const chance = tier >= 0 && byTier.length
      ? Number(byTier[Math.min(tier, byTier.length - 1)]) || 0
      : Number(odds.everyone) || 0;
    const hours = (() => {
      const list = PRAY.blessingDurationHoursByTier || [];
      const i = Math.min(Math.max(tier, 0), Math.max(0, list.length - 1));
      return Math.max(1, Number(list[i]) || 8);
    })();

    let text = `You hold the three verses. ${d.name} takes note, and no more.`;
    if (Math.random() < chance) {
      if (grantBlessing(a, d, hours)) {
        text = `${d.name} answers. The blessing rests on you for ${hours} hours.`;
        audit(`PRAYER ${who(a)} received the blessing of ${d.name} (${hours} h, priest tier ${tier + 1})`);
      } else {
        text = `${d.name} answers, and the answer does not reach you.`;
      }
    }
    finish(a, round, true, text, 'win');
  });

  // ── /deity ──────────────────────────────────────────────────────────────────────────────────
  // The brief puts conversion on a menu key. That menu is front work and is not built; this is the
  // reachable stopgap, and it keeps the same rule: you turn at the new god's shrine, not anywhere.
  const daysLeft = (faith) => {
    const last = Number(faith && (faith.convertedAt || faith.at)) || 0;
    const ms = last + CONVERSION_DAYS * 86400000 - Date.now();
    return ms > 0 ? Math.ceil(ms / 86400000) : 0;
  };
  registerChatCommand('deity', (a, argStr) => {
    const faith = faithOf(a);
    const arg = String(argStr || '').trim();
    if (!arg) {
      const mine = faith ? deityById(faith.id) : null;
      personal(a, mine
        ? `You follow ${mine.name} - ${mine.boon || 'no boon recorded'}${daysLeft(faith) ? ` You may turn to another god in ${daysLeft(faith)} day(s).` : ' You may turn to another god.'}`
        : 'You hold no god. Stand at a shrine and say /deity <name>.');
      const list = (kind) => DEITIES.filter((d) => (d.kind === 'divine') === (kind === 'divine'))
        .map((d) => d.name + (Number(d.inBruma) > 0 ? '' : '*')).join(', ');
      personal(a, `Divines: ${list('divine')}`);
      personal(a, `Daedra: ${list('daedra')}`);
      personal(a, '* no shrine you can reach yet. Say /deity <name> to hear what a god asks and gives.');
      return;
    }
    const d = deityByName(arg);
    if (!d) return personal(a, `No god by that name. Say /deity on its own for the list.`);
    // Naming a god you do not follow, away from its shrine, reads as a question rather than a vow.
    if (!faith || faith.id !== d.id) {
      const here = lastShrine.get(a);
      if (!here || here.deityId !== d.id || Date.now() - here.at > 30000) {
        if (d.sphere) personal(a, `${d.name}. ${d.sphere}`);
        if (d.boon) personal(a, `Boon: ${d.boon}${Number(d.inBruma) > 0 ? '' : ' (no shrine you can reach yet)'}`);
      }
    }
    if (faith && faith.id === d.id) return personal(a, `You already follow ${d.name}.`);

    const here = lastShrine.get(a);
    if (!here || here.deityId !== d.id || Date.now() - here.at > 30000) {
      return personal(a, `You must stand at a shrine of ${d.name} and touch it, then say this again.`);
    }
    if (faith) {
      const left = daysLeft(faith);
      if (left) {
        const mine = deityById(faith.id);
        return personal(a, `${mine ? mine.name : 'Your god'} is not so easily left. You may turn again in ${left} day(s).`);
      }
      clearBlessing(a, 'The blessing you carried falls away.');
    }
    setFaith(a, { id: d.id, name: d.name, kind: d.kind, at: faith ? Number(faith.at) || Date.now() : Date.now(), convertedAt: Date.now() });
    personal(a, faith ? `You turn to ${d.name}.` : `You take ${d.name} as your own.`);
    audit(`DEITY ${who(a)} ${faith ? 'turned to' : 'took'} ${d.name}`);
  }, { help: 'your god; /deity <name> at that god\'s shrine to take or change it' });

  // A blessing id that does not resolve is silent: the prayer succeeds, the roll lands and the
  // worshipper is told the god "gives no sign". Count them at boot so a mistyped form id shows up
  // in the log rather than in somebody's play session.
  const blessingCheck = (() => {
    const out = { ok: 0, server: 0, broken: [] };
    for (const d of DEITIES) {
      if (d.blessingSource === 'server') { out.server++; continue; }
      if (blessingIdOf(d)) out.ok++; else out.broken.push(d.name);
    }
    return out;
  })();
  if (blessingCheck.broken.length) log(`prayer: ${blessingCheck.broken.length} blessing(s) do not resolve: ${blessingCheck.broken.join(', ')}`);

  const reachable = DEITIES.filter((d) => Number(d.inBruma) > 0).length;
  log(`prayer ${CFG.enabled ? 'on' : 'off'}: ${DEITIES.length} deities, ${shrineIndex().size} shrine ids, ${reachable} reachable under the region lock; ${VERSES} verses of ${VERSE_MS} ms, ${SLACK_MS} ms slack, ${Math.round(SHRINE_COOLDOWN_MS / 60000)} min per shrine, conversion every ${CONVERSION_DAYS} day(s); blessings ${blessingCheck.ok} resolved, ${blessingCheck.server} server-side, ${blessingCheck.broken.length} broken`);
};
