#!/usr/bin/env python3
"""Every race in the load order whose behaviour graph is not the humanoid master graph (DefaultMale/DefaultFemale.hkx).

SkyrimPlatform writes a relayed spell's caster variables at the humanoid graph's fixed indexes, so the client sends none
to a copy of these races (fork skymp5-client/src/sync/nonHumanoidRaceList.ts, written by this script). The last plugin
that carries a race decides its graph. Read-only; uses ck-mcp/esplib.py.
  python3 tools/races/non_humanoid_races.py <loadorder.txt> <data dir> <out .ts>
"""
import os, sys
sys.path.insert(0, os.path.expanduser('~/dragonbreak/ck-mcp'))
from esplib import Plugin, subrecords, edid_of

HUMANOID = {'actors\\character\\defaultmale.hkx', 'actors\\character\\defaultfemale.hkx'}


def graphs(data):
    """The behaviour graph paths: the MODL pair after the NAM3 marker."""
    out, after = [], False
    for sig, val in subrecords(data):
        if sig == b'NAM3':
            after = True
        elif after and sig == b'MODL':
            out.append(val.rstrip(b'\x00').decode('cp1252', 'replace').lower())
    return out


def main(loadorder, data_dir, out_path):
    names = [l.strip() for l in open(loadorder, encoding='utf-8-sig') if l.strip() and not l.startswith('#')]
    races = {}   # (origin plugin, local id) -> (edid, graphs)
    for name in names:
        p = Plugin(os.path.join(data_dir, name))
        with open(p.path, 'rb') as fh:
            for sig, fid, flags, off, size, ctx in p.index:
                if sig != 'RACE':
                    continue
                src, loc = p.modindex_source(fid)
                if src is None:
                    continue
                d = p.data_at(fh, off, size, flags)
                g = graphs(d)
                if g:
                    races[(src, loc)] = (edid_of(d) or '?', g)
    origin = {n.lower(): n for n in names}
    rows = sorted((origin.get(src, src), loc, edid, g) for (src, loc), (edid, g) in races.items()
                  if not all(x in HUMANOID for x in g))
    lines = [
        '// Generated by the server repo\'s tools/races/non_humanoid_races.py from the load order; do not edit by hand.',
        f'// {len(rows)} of {len(races)} races run a behaviour graph other than the humanoid master graph: [plugin, local id, editor id]',
        'export const NON_HUMANOID_RACES: ReadonlyArray<readonly [string, number, string]> = [',
    ]
    lines += [f'  [{name!r}, 0x{loc:06x}, {edid!r}],'.replace("'", '"') for name, loc, edid, g in rows]
    lines.append('];')
    open(out_path, 'w').write('\n'.join(lines) + '\n')
    print(f'{len(rows)} non-humanoid of {len(races)} races -> {out_path}')


if __name__ == '__main__':
    main(*sys.argv[1:4])
