'use strict'
// A Crash Logger SSE crash log in the shape launcher 2.1.36 sends it with Report a Problem (report.js condenseCrashLog:
// its first line, whole sections, '[N more line(s) cut]' marks), with the line formats of CrashLoggerSSE's
// CrashHandler.cpp, Analysis.cpp and Introspection.cpp. What it read from memory holds names, chat, a /pm, an email, a
// mention, a JWT and a bot token. Every secret is assembled here at run time, so none is written out whole in the repo.

const b64url = s => Buffer.from(s, 'utf8').toString('base64url')

// A LiveKit-style voice token: header, claims and signature. Built from parts so the source never holds a JWT.
const jwt = [b64url('{"alg":"HS256","typ":"JWT"}'),
             b64url('{"exp":1790000000,"sub":"fake-player-0001","video":{"room":"fake-room","roomJoin":true}}'),
             b64url('not-a-real-signature-just-test-bytes')].join('.')
// Shaped like a Discord bot token for S9 but starting with Z (real ones start M, N or O), and built from parts
const botToken = ['ZmFrZS1ub3QtYS1yZWFsLWJvdA', 'XyZaBc', 'fakeFakeFakeFakeFakeFake0123456789'].join('.')

// Values that must never reach Discord, with the label a failed assertion prints
const SECRETS = {
  playerName: 'Jake Dragonsworn',
  otherPlayer: 'Brelyna Otherplayer',
  remoteNpc: 'Ulfric Remotename',
  unquotedName: 'Kodlak Fourthplayer',
  nestedName: 'Sorine Thirdplayer',
  chat: 'meet me at the inn',
  pm: 'the key is under the mat',
  email: 'arvel.private@example.com',
  mention: '123456789012345678',
  jwtHeader: jwt.split('.')[0],
  jwtClaims: jwt.split('.')[1],
  jwtSignature: jwt.split('.')[2],
  botToken: botToken.split('.')[0],
  botTokenTail: botToken.split('.')[2],
  letterLine: 'second line Sorine wrote',
  fakeSection: 'a section faked inside a string',
  account: 'Arvel',
  commandLine: 'secret-launch-argument',
  cppMessage: 'Unexpected token in chat payload',
}

function crashLog({ moduleLines = 6 } = {}) {
  const lines = [
    '[crash-2026-10-01-14-22-07.log, 214 KB, written 2 min before this report, from Documents]',
    'CRASH TIME: 2026-10-01 15:22:07',
    'Skyrim SSE v1.6.1170',
    'CrashLoggerSSE v1-20-0-0 Aug 23 2026 21:48:52',
    '',
    'Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF6D2A1B2C3 SkyrimSE.exe+06B2C3\tmov rax, [rcx+0x10]',
    'Exception Flags: 0x00000000 (Continuable)',
    'Number of Parameters: 2',
    'Exception Thread ID: 10432',
    'Access Violation: Tried to read memory at 0x000000000010',
    '',
    'ACCESS VIOLATION ANALYSIS:',
    '\tInstruction: mov rax, [rcx+0x10]',
    '\tBase Register: RCX = 0x0000000000000000 (null)',
    '\tComputed Address: 0x0000000000000010',
    '',
    'POSSIBLE RELEVANT OBJECTS (5):',
    `\tRBX: (PlayerCharacter*) "${SECRETS.playerName}" [0x00000014] (Skyrim.esm)`,
    `\tRSI: (Character*) "${SECRETS.otherPlayer}" [0xFF000D2E] (DragonBreak.esp)`,
    `\tRSP+48: (TESNPC*) "${SECRETS.remoteNpc}" [0xFF000A11]`,
    '\tRSP+60: (BSScript::Internal::CodeTasklet*) [ (FF000D2E)].dbo_ChatScript.OnChat() - "dbo_ChatScript.psc" Line 42',
    '\tRSP+70: (TESNPC*)',
    `\t\tName: "${SECRETS.nestedName}"`,
    `\t\tFull Name: ${SECRETS.unquotedName}`,
    '\t\tFormID: 0xFF000D2F',
    '\t\tFile: "DragonBreak.esp"',
    '',
    'PROCESS INFO:',
    '\tProcess ID: 4120',
    `\tWorking Directory: C:\\Users\\${SECRETS.account}\\Games\\Skyrim Special Edition`,
    `\tCommand Line: "C:\\Games\\Skyrim Special Edition\\SkyrimSE.exe" ${SECRETS.commandLine}`,
    '\tProcess Uptime: 01:12:44 (4364000ms)',
    '',
    'THREAD CONTEXT (HEURISTIC):',
    '\tThread Priority: 0',
    '\tLikely Role: Main thread',
    '',
    'SYSTEM SPECS:',
    '\tOS: Microsoft Windows 11 Pro v10.0.26200',
    '\tCPU: AuthenticAMD AMD Ryzen 7 5800X3D 8-Core Processor',
    '\tGPU #1: Nvidia AD104 [GeForce RTX 4070]',
    '\tPHYSICAL MEMORY: 14.20 GB/31.92 GB',
    '',
    'PROBABLE CALL STACK:',
    '\t[ 0] 0x7FF6D2A1B2C3      SkyrimSE.exe+06B2C3 -> 19354+0x23\tmov rax, [rcx+0x10]',
    '\t[ 1] 0x7FF6D2C4D5E6      SkyrimSE.exe+28D5E6 -> 50179+0x116\tcall [rax+0x08]',
    '\t[ 2] 0x7FFA1B2C3D4E SkyrimPlatformImpl.dll+0123D4E',
    '\t[ 3] 0x7FFA1B2C4F00 SkyrimPlatformImpl.dll+0124F00',
    '\t[57 more line(s) cut]',
    '',
    'REGISTERS:',
    '\tRAX 0x0                (size_t) [0]',
    '\tRCX 0x1D3A5B0C2D0      (PlayerCharacter*)',
    '\t\tFlags: 0x0282040C',
    `\t\tName: "${SECRETS.playerName}"`,
    '\t\tFormID: 0x00000014',
    '\t\tFormType: ActorCharacter (62)',
    `\t\tFull Name: "${SECRETS.playerName}"`,
    '\t\tFile: "Skyrim.esm"',
    `\tRDX 0x1D3A5B0C400      (char*) "[PM] ${SECRETS.otherPlayer}: ${SECRETS.chat}"`,
    `\tRBX 0x1D3A5B0C500      (char*) "/pm Ulfric ${SECRETS.pm}"`,
    '\tRSP 0x2E1F7FF5C0       (void*)',
    `\tRBP 0x1D3A5B0C600      (char*) "my email is ${SECRETS.email}"`,
    '\tRSI 0x7FF6D2A1B2C3     (void* -> SkyrimSE.exe+06B2C3\tmov rax, [rcx+0x10])',
    `\tRDI 0x1D3A5B0C680      (char*) "voice ${jwt}"`,
    '\tR8  0x14               (size_t) [20]',
    '',
    'STACK:',
    `\t[RSP+0  ] 0x1D3A5B0C700      (char*) "hey <@${SECRETS.mention}> look"`,
    `\t[RSP+8  ] 0x1D3A5B0C800      (char*) "wss://voice.example/rtc?access_token=${jwt}"`,
    `\t[RSP+10 ] 0x1D3A5B0C900      (char*) "Bot ${botToken}"`,
    '\t[RSP+18 ] 0x1D3A5B0CA00      (char*) "first line of a letter',
    SECRETS.letterLine,
    'MODULES:',
    `\t${SECRETS.fakeSection}"`,
    '\t[RSP+20 ] 0x1D3A5B0CB00      (TESNPC*)',
    `\t\tName: "${SECRETS.unquotedName}"`,
    '\t[RSP+28 ] 0x0                (size_t) [0]',
    '\t[370 more line(s) cut]',
    '',
    'MODULES:',
    '\tSkyrimSE.exe                  0x7FF6D2A00000',
    '\tSkyrimPlatformImpl.dll        0x7FFA1B200000',
    `\tMpClientPlugin.dll            0x7FFA1C000000 C:\\Users\\${SECRETS.account}\\AppData\\Local\\DragonBreak\\skyrim\\Data\\SKSE\\Plugins`,
  ]
  for (let i = 0; i < moduleLines; i++) lines.push(`\tmodule${String(i).padStart(4, '0')}.dll${' '.repeat(17)}0x7FF8${(0x10000000 + i * 0x10000).toString(16).toUpperCase()}`)
  lines.push(
    '',
    'SKSE PLUGINS:',
    '\tCommunityShaders.dll v1.9.1',
    '\tCrashLoggerSSE.dll v1.20.0',
    '\tSkyrimPlatform.dll v2.9.0',
    '',
    'PLUGINS:',
    '\tLight: 1\tRegular: 3\tTotal: 4',
    '\t[00]     Skyrim.esm',
    '\t[01]     Update.esm',
    '\t[02]     DragonBreak.esp',
    '\t[FE:000] ccBGSSSE001-Fish.esm',
  )
  return lines.join('\r\n')
}

module.exports = { crashLog, SECRETS, jwt, botToken }
