#!/usr/bin/env python3
"""One-way puzzle triggers in dungeons (Nate, 9 Oct: the Echo Cave barrier "won't come back"). A vanilla
defaultDisableSelfOnActivate activator disables itself when its activate parent (a pull chain, a lever) fires it, and
whatever names it as enable parent (a barrier, a gate) goes with it. Single player resets the cell; this server never
does, so ruinbuttons.js re-enables them when the dungeon's lease ends. Writes server/disable-triggers.json.

    python3 tools/spawns/disable_triggers.py [--data /opt/skyrim-data] [--order <loadorder.txt>] [--replace "<plugin>=<path>"]

Kept: a REFR in a cell of dungeons.json or expeditions.json whose base is an ACTI with defaultDisableSelfOnActivate in
its editor id, and whose winning record is neither Initially Disabled (0x800: staff and plugin curation, e.g. the 209
puzzle blockers disabled on purpose) nor deleted. Its activate parents (XAPR) are the chains players pull.
"""
import argparse
import json
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import owned_spawns as O  # noqa: E402
import esplib  # noqa: E402

SERVER = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
TRIGGER = re.compile(r'DisableSelfOnActivate', re.I)
DISABLED, DELETED = 0x800, 0x20


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='/opt/skyrim-data')
    ap.add_argument('--order', default=os.path.expanduser('~nate/dragonbreak/fork/deploy/skyrim-data/loadorder.txt'))
    ap.add_argument('--replace', action='append', default=[])
    ap.add_argument('--out', default=os.path.join(SERVER, 'disable-triggers.json'))
    a = ap.parse_args()
    replace = {n.strip().lower(): p.strip() for n, _, p in (r.partition('=') for r in a.replace)}
    lo = O.LoadOrder(a.data, a.order, replace)
    dungeons = {}
    for f, key in (('dungeons.json', 'dungeons'), ('expeditions.json', 'expeditions')):
        for d in json.load(open(os.path.join(SERVER, f), encoding='utf-8'))[key]:
            for c in d.get('cells', []):
                h, _, plugin = c['desc'].partition(':')
                dungeons[(plugin.lower(), int(h, 16))] = d['id']
    bases = {}
    for p in lo.plugins:
        for t, fid, fl, off, sz, ctx in p.index:
            if t == 'ACTI':
                k = lo.source(p, fid)
                e = dict(esplib.subrecords(p.data_at(p.fh, off, sz, fl))).get(b'EDID', b'').rstrip(b'\0').decode('latin1')
                if k and TRIGGER.search(e):
                    bases[k] = e
    out, skipped = [], []
    for k, (p, off, sz, fl, ctx) in sorted(lo.refs_in(set(dungeons)).items()):
        s = esplib.subrecords(p.data_at(p.fh, off, sz, fl))
        s = list(s)
        d = dict(s)
        if len(d.get(b'NAME', b'')) < 4:
            continue
        base = lo.ref(p, d[b'NAME'])
        if base not in bases:
            continue
        cell = lo.source(p, ctx[1])
        if fl & (DISABLED | DELETED):
            skipped.append(lo.desc(k))
            continue
        chains = [lo.desc(lo.ref(p, v[:4])) for sig, v in s if sig == b'XAPR' and len(v) >= 4]
        out.append({'ref': lo.desc(k), 'base': bases[base], 'dungeon': dungeons[cell], 'cell': lo.desc(cell), 'chains': chains})
    result = {
        '_comment': 'Generated by tools/spawns/disable_triggers.py: defaultDisableSelfOnActivate triggers in dungeon and '
                    'expedition cells (their chains in "chains"), re-enabled by ruinbuttons.js when the lease ends. Plugin-'
                    'disabled ones are left out on purpose.',
        'triggers': out, 'skippedPluginDisabled': skipped,
    }
    with open(a.out, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=1)
        f.write('\n')
    print(f'disable triggers: {len(out)} in {len({t["dungeon"] for t in out})} dungeon(s), {len(skipped)} plugin-disabled left out -> {a.out}')


if __name__ == '__main__':
    main()
