"""Writes ayleid-loot.json: the Ayleid weapons, armour, clothing and jewellery an expedition ruin's big chests and boss
chest can hold (dungeons.js, config dungeons.ayleidLoot; Nate, 2026-09-28: "ayleid weapons and armor found in the ayleid
ruins"). Candidates are admin-items.json's Ayleid entries; every one is read from the plugin itself (type, editor id,
value, enchanted or not), so a name never decides anything. Staff templates and quest rewards are left out.

  python3 tools/ayleid_loot.py [plugin dir, default /opt/skyrim-data]   (from server/)
"""
import json, re, struct, sys, zlib

DATA = sys.argv[1] if len(sys.argv) > 1 else '/opt/skyrim-data'
CATS = ('Weapons', 'Enchanted Weapons', 'Armor', 'Clothing', 'Jewelry')
SKIP = re.compile(r'Template|Reward')      # staff templates (value 5) and the Frostcrag quest dagger

# Tiers by editor id: Ayleid jewellery runs Ayleid01 (Minor) .. 04 (Eminent), the shock weapons Shock01..03
def tier(edid):
    if re.search(r'Ayleid04$', edid) or edid == 'BSKArmorAyleidLichHelmet': return 'rarest'
    if re.search(r'Ayleid03$|Shock03$|ChainLightning$', edid) or edid == 'IWAyleidGreatsword': return 'rare'
    if re.search(r'Ayleid0[12]$|Shock0[12]$|^BSKAyleidStaff', edid): return 'uncommon'
    if re.match(r'^CYRAyleid(Bow|Dagger|Sword|Mage)|^BSKAyleid(Ring|Amulet)$', edid): return 'common'
    return None

def group(rtype, slots):
    if rtype == 'WEAP': return 'weapon'
    return 'jewelry' if slots & (0x20 | 0x40) else 'apparel'

def masters(b):
    size = struct.unpack_from('<I', b, 4)[0]; p = 24; n = 0
    while p < 24 + size:
        n += b[p:p+4] == b'MAST'; p += 6 + struct.unpack_from('<H', b, p + 4)[0]
    return n

def records(b, want):
    p = 0; out = {}
    while p < len(b):
        size = struct.unpack_from('<I', b, p + 4)[0]
        if b[p:p+4] == b'GRUP': p += 24; continue
        flags, fid = struct.unpack_from('<II', b, p + 8)
        if fid in want:
            d = b[p+24:p+24+size]
            if flags & 0x40000: d = zlib.decompress(d[4:])
            subs = {}; q = 0
            while q < len(d):
                n = struct.unpack_from('<H', d, q + 4)[0]; subs.setdefault(d[q:q+4].decode(), d[q+6:q+6+n]); q += 6 + n
            out[fid] = (b[p:p+4].decode(), flags, subs)
        p += 24 + size
    return out

catalog = json.load(open('admin-items.json'))
cands = [(desc, name) for c in catalog['categories'] if c['id'] in CATS for desc, name, _ in c['items'] if re.search('ayleid', name, re.I)]
by_plugin = {}
for desc, name in cands:
    local, plugin = desc.split(':', 1); by_plugin.setdefault(plugin, []).append((int(local, 16), desc, name))
items, left_out = [], []
for plugin, lst in sorted(by_plugin.items()):
    b = open(f'{DATA}/{plugin}', 'rb').read(); own = masters(b)
    got = records(b, {(own << 24) | l for l, _, _ in lst})
    for local, desc, name in lst:
        rec = got.get((own << 24) | local)
        if not rec: left_out.append((desc, 'no record')); continue
        rtype, flags, s = rec
        edid = s.get('EDID', b'').rstrip(b'\0').decode('latin1')
        if rtype not in ('WEAP', 'ARMO'): left_out.append((desc, rtype)); continue
        if rtype == 'ARMO' and flags & 0x4: left_out.append((desc, 'non-playable')); continue
        if SKIP.search(edid): left_out.append((desc, edid)); continue
        t = tier(edid)
        if not t: left_out.append((desc, 'no tier: ' + edid)); continue
        slots = struct.unpack_from('<I', s['BOD2'], 0)[0] if 'BOD2' in s else 0
        items.append({'id': desc, 'name': edid, 'label': name, 'type': rtype, 'group': group(rtype, slots),
                      'value': struct.unpack_from('<I', s['DATA'], 0)[0], 'enchanted': 'EITM' in s, 'tier': t})
items.sort(key=lambda i: (['common', 'uncommon', 'rare', 'rarest'].index(i['tier']), i['group'], i['name']))
json.dump({'_comment': 'Generated by tools/ayleid_loot.py from the plugins themselves; read by dungeons.js (config dungeons.ayleidLoot).',
           'items': items}, open('ayleid-loot.json', 'w'), indent=1)
open('ayleid-loot.json', 'a').write('\n')
from collections import Counter
print(len(items), 'items', dict(Counter((i['tier'], i['group']) for i in items)))
for d, why in left_out: print('left out', d, why)
