#!/usr/bin/env node
// Writes racedefaultheads.json (read by appearance.js at load): each race's default Face head part, male and female,
// and the race form ids that wear it. appearance.js uses it to undo RaceMenu putting the Nord head on a non-Nord
// character when the editor is reopened on an existing one (Jake's audit, 7 Oct: 9 of 10 non-Nord re-edits since 4 Oct).
//
//   node tools/racedefaultheads.js [<fork>/skymp5-front/src/features/charCreator/data/headparts.json] [out.json]
//
// The heads come from headparts.json "raceDefaults" (the fork's character creator catalogue, read out of Skyrim.esm).
// The race form ids are not in that file: they are below, from the fork's charCreator/data/races.js (the playable races
// and their child races) and the gamemode's racial.js / supernatural.js VAMPIRE_RACES (each playable race's vampire
// variant, which wears the same heads). All are Skyrim.esm records, load index 0, so the form id is the load-order id.
// A race in raceDefaults with no id here (ElderRace) still counts its heads as some race's default; a character of a race
// with no entry is never guarded.
'use strict';
const fs = require('fs');
const path = require('path');

const SRC = process.argv[2] || path.join(process.env.FORK || '/opt/alduinak', 'skymp5-front/src/features/charCreator/data/headparts.json');
const OUT = process.argv[3] || path.resolve(__dirname, '..', 'racedefaultheads.json');

const RACE_IDS = {
  ArgonianRace: [0x13740, 0x8883a],
  BretonRace: [0x13741, 0x8883c],
  DarkElfRace: [0x13742, 0x8883d],
  HighElfRace: [0x13743, 0x88840],
  ImperialRace: [0x13744, 0x88844],
  KhajiitRace: [0x13745, 0x88845],
  NordRace: [0x13746, 0x88794],
  OrcRace: [0x13747, 0xa82b9],
  RedguardRace: [0x13748, 0x88846],
  WoodElfRace: [0x13749, 0x88884],
  DremoraRace: [0x131f0],
  NordRaceChild: [0x2c65b],
  ImperialRaceChild: [0x2c659],
  RedguardRaceChild: [0x2c658],
  BretonRaceChild: [0x2c65c],
};

const hex = (n) => (Number(n) >>> 0).toString(16);
const src = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const defaults = src && src.raceDefaults;
if (!defaults || typeof defaults !== 'object') { console.error(`${SRC}: no raceDefaults`); process.exit(2); }

const races = {};
for (const edid of Object.keys(defaults).sort()) {
  const d = defaults[edid] || {};
  const male = Number(d.male && d.male.head) >>> 0;
  const female = Number(d.female && d.female.head) >>> 0;
  if (!male && !female) continue;
  races[edid] = { ids: (RACE_IDS[edid] || []).map(hex), male: male ? hex(male) : null, female: female ? hex(female) : null };
}
for (const edid of Object.keys(RACE_IDS)) if (!races[edid]) console.error(`warning: ${edid} has an id here but no default heads in ${SRC}`);

const out = {
  _comment: 'Generated by tools/racedefaultheads.js from the fork\'s skymp5-front/src/features/charCreator/data/headparts.json (raceDefaults): '
    + 'each race\'s default Face head part (hex form ids, Skyrim.esm) and the race form ids that wear it (the race and its vampire variant). '
    + 'Read by appearance.js at load. Do not edit by hand: rerun the tool.',
  races,
};
// One race to a line, so a regenerated file diffs by race
const body = Object.keys(races).map((edid) => `  ${JSON.stringify(edid)}: ${JSON.stringify(races[edid])}`).join(',\n');
fs.writeFileSync(OUT, `{\n "_comment": ${JSON.stringify(out._comment)},\n "races": {\n${body}\n }\n}\n`);
JSON.parse(fs.readFileSync(OUT, 'utf8'));
console.log(`${OUT}: ${Object.keys(races).length} races, ${Object.values(races).reduce((n, r) => n + r.ids.length, 0)} race ids`);
