// DOM KeyboardEvent.code -> [DirectInput scan code, the key's name], for the menu keys F3, Settings, General rebinds.
// Generated from the SkyrimPlatform typings' DxScanCode (node_modules/@skyrim-platform/skyrim-platform/index.d.ts).
export const DOM_TO_DX: Record<string, [number, string]> = {
  Escape: [1, "Escape"],
  Minus: [12, "-"],
  Equal: [13, "="],
  Backspace: [14, "Backspace"],
  Tab: [15, "Tab"],
  BracketLeft: [26, "["],
  BracketRight: [27, "]"],
  Enter: [28, "Enter"],
  ControlLeft: [29, "Left Ctrl"],
  Semicolon: [39, ";"],
  Quote: [40, "'"],
  Backquote: [41, "~"],
  ShiftLeft: [42, "Left Shift"],
  Backslash: [43, "\\"],
  Comma: [51, ","],
  Period: [52, "."],
  Slash: [53, "/"],
  ShiftRight: [54, "Right Shift"],
  NumpadMultiply: [55, "Num *"],
  AltLeft: [56, "Left Alt"],
  Space: [57, "Space"],
  CapsLock: [58, "Caps Lock"],
  NumLock: [69, "Num Lock"],
  ScrollLock: [70, "Scroll Lock"],
  NumpadSubtract: [74, "Num -"],
  NumpadAdd: [78, "Num +"],
  NumpadDecimal: [83, "Num ."],
  NumpadEnter: [156, "Num Enter"],
  ControlRight: [157, "Right Ctrl"],
  NumpadDivide: [181, "Num /"],
  AltRight: [184, "Right Alt"],
  Pause: [197, "Pause"],
  Home: [199, "Home"],
  ArrowUp: [200, "Up"],
  PageUp: [201, "Page Up"],
  ArrowLeft: [203, "Left"],
  ArrowRight: [205, "Right"],
  End: [207, "End"],
  ArrowDown: [208, "Down"],
  PageDown: [209, "Page Down"],
  Insert: [210, "Insert"],
  Delete: [211, "Delete"],
  KeyA: [30, "A"],
  KeyB: [48, "B"],
  KeyC: [46, "C"],
  KeyD: [32, "D"],
  KeyE: [18, "E"],
  KeyF: [33, "F"],
  KeyG: [34, "G"],
  KeyH: [35, "H"],
  KeyI: [23, "I"],
  KeyJ: [36, "J"],
  KeyK: [37, "K"],
  KeyL: [38, "L"],
  KeyM: [50, "M"],
  KeyN: [49, "N"],
  KeyO: [24, "O"],
  KeyP: [25, "P"],
  KeyQ: [16, "Q"],
  KeyR: [19, "R"],
  KeyS: [31, "S"],
  KeyT: [20, "T"],
  KeyU: [22, "U"],
  KeyV: [47, "V"],
  KeyW: [17, "W"],
  KeyX: [45, "X"],
  KeyY: [21, "Y"],
  KeyZ: [44, "Z"],
  Digit0: [11, "0"],
  Numpad0: [82, "Num 0"],
  Digit1: [2, "1"],
  Numpad1: [79, "Num 1"],
  Digit2: [3, "2"],
  Numpad2: [80, "Num 2"],
  Digit3: [4, "3"],
  Numpad3: [81, "Num 3"],
  Digit4: [5, "4"],
  Numpad4: [75, "Num 4"],
  Digit5: [6, "5"],
  Numpad5: [76, "Num 5"],
  Digit6: [7, "6"],
  Numpad6: [77, "Num 6"],
  Digit7: [8, "7"],
  Numpad7: [71, "Num 7"],
  Digit8: [9, "8"],
  Numpad8: [72, "Num 8"],
  Digit9: [10, "9"],
  Numpad9: [73, "Num 9"],
  F1: [59, "F1"],
  F2: [60, "F2"],
  F3: [61, "F3"],
  F4: [62, "F4"],
  F5: [63, "F5"],
  F6: [64, "F6"],
  F7: [65, "F7"],
  F8: [66, "F8"],
  F9: [67, "F9"],
  F10: [68, "F10"],
  F11: [87, "F11"],
  F12: [88, "F12"],
};

const DX_NAME: Record<number, string> = {};
for (const k of Object.keys(DOM_TO_DX)) { const [code, name] = DOM_TO_DX[k]; if (!(code in DX_NAME)) DX_NAME[code] = name; }
// Mouse buttons (DxScanCode 256 + the DirectInput button), which the launcher can set as the talk key
Object.assign(DX_NAME, { 256: 'Left Mouse', 257: 'Right Mouse', 258: 'Middle Mouse', 259: 'Mouse 4', 260: 'Mouse 5', 261: 'Mouse 6', 262: 'Mouse 7', 263: 'Mouse 8' });

// The name of a scan code ('' for none)
export const keyName = (code: number): string => (code > 0 ? DX_NAME[code] || `Key ${code}` : '');
