#!/usr/bin/env python3
"""Every Sea Salt Deposit placed in the load order, for labour.js's salt glow (GroundedPasta, 30 Sep: "Finally found
salt, they are very small, very hard to see").

    python3 tools/labour/salt_deposits.py [--replace "<load-order name>=<path>" ...] [--check]

A deposit is a reference whose base editor id contains "SeaSalt", the same test labour.js's nodeOf makes. The winning
override counts; deleted and initially-disabled references are left out. Writes salt-deposits.json beside labour.js
(descs, world or cell, position). --check writes nothing and exits 1 when the file would change. Read only otherwise.
"""
import argparse, json, os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SERVER = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.environ.get('ESPLIB_DIR', os.path.expanduser('~nate/dragonbreak/ck-mcp')))
import esplib  # noqa: E402

DELETED, DISABLED = 0x20, 0x800


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='/opt/skyrim-data')
    ap.add_argument('--order', default=os.path.expanduser('~nate/dragonbreak/fork/deploy/skyrim-data/loadorder.txt'))
    ap.add_argument('--replace', action='append', default=[])
    ap.add_argument('--out', default=os.path.join(SERVER, 'salt-deposits.json'))
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    replace = {k.strip().lower(): v for k, v in (r.split('=', 1) for r in a.replace)}
    names = [l.strip().lstrip('*') for l in open(a.order, encoding='utf-8-sig') if l.strip() and not l.startswith('#')]
    plugins, proper = [], {}
    for n in names:
        path = replace.get(n.lower()) or os.path.join(a.data, n)
        if os.path.exists(path):
            p = esplib.Plugin(path)
            p.fh = open(path, 'rb')
            p.key = n.lower()
            plugins.append(p)
            proper[n.lower()] = n

    def src(p, fid):
        s, loc = p.modindex_source(fid)
        return (s.lower(), loc & 0xFFFFFF) if s else None

    def desc(k):
        return '%x:%s' % (k[1], proper.get(k[0], k[0]))

    # the bases: winning ACTI/FURN/STAT/MSTT whose editor id carries SeaSalt
    bases = set()
    for p in plugins:
        for t, fid, fl, off, sz, ctx in p.index:
            if t in ('ACTI', 'FURN', 'MSTT', 'STAT'):
                k = src(p, fid)
                e = esplib.edid_of(p.data_at(p.fh, off, sz, fl)) or ''
                if k and 'seasalt' in e.lower() and not fl & DELETED:
                    bases.add(k)
                elif k:
                    bases.discard(k)
    # the references, the last override winning; only plugins that can see a base need reading
    owners = {b[0] for b in bases}
    refs = {}
    for p in plugins:
        if p.key not in owners and not owners & {m.lower() for m in p.masters}:
            continue
        for t, fid, fl, off, sz, ctx in p.index:
            if t != 'REFR':
                continue
            k = src(p, fid)
            d = dict(esplib.subrecords(p.data_at(p.fh, off, sz, fl)))
            base = src(p, struct.unpack('<I', d[b'NAME'][:4])[0]) if b'NAME' in d else None
            if base not in bases or fl & (DELETED | DISABLED) or b'DATA' not in d:
                refs.pop(k, None)
                continue
            w, c, g = ctx
            where = src(p, w) if w else src(p, c)
            refs[k] = {'ref': desc(k), 'where': desc(where) if where else None,
                       'pos': [round(x) for x in struct.unpack('<3f', d[b'DATA'][:12])]}
    out = {'_comment': 'Generated by tools/labour/salt_deposits.py: every Sea Salt Deposit placed in the load order '
                       '(base editor id carries SeaSalt, as labour.js nodeOf). Read by labour.js for the salt glow.',
           'deposits': sorted(refs.values(), key=lambda r: (r['where'] or '', r['ref']))}
    text = json.dumps(out, indent=1) + '\n'
    old = open(a.out).read() if os.path.exists(a.out) else ''
    by = {}
    for r in out['deposits']:
        by[r['where']] = by.get(r['where'], 0) + 1
    print(f"{len(out['deposits'])} deposits on {len(bases)} base(s): " + ', '.join(f'{v} in {k}' for k, v in sorted(by.items(), key=lambda x: -x[1])))
    if text == old:
        print('salt-deposits.json is current')
        return 0
    if a.check:
        print('salt-deposits.json would change')
        return 1
    open(a.out, 'w').write(text)
    print(f'wrote {a.out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
