"""The F7 Place tab's catalog: every NPC and every placeable world object in the load order.

Writes server/admin-placeables.json in the admin-items.json shape, {categories: [{id, label, kind, items: [[desc, name, plugin]]}]},
with kind "npc" or "object". Runs on the PC or on the dev server:

    py ck-mcp\\admin_placeables.py                       (PC: the dev Data folder and plugins.server.txt)
    python3 ck-mcp/admin_placeables.py --server          (CT 115: /opt/skyrim-data and fork/deploy/skyrim-data/loadorder.txt)

Names come from FULL: plain text in a normal plugin, the .STRINGS tables in a localized one. The dev server has no vanilla
BSAs, so there a localized name falls back to the editor id made readable; the PC run gives the real names.
"""
import collections, json, os, re, struct, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "ck-mcp"))  # tracked copy in server/tooling
import core, esplib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE)) if os.path.basename(HERE) == "tooling" else os.path.dirname(HERE)
if "--server" in sys.argv:
    DATA = "/opt/skyrim-data"
    ORDER = os.path.join(ROOT, "fork", "deploy", "skyrim-data", "loadorder.txt")
else:
    DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
    ORDER = r"E:\DragonBreak Online Dev files\server\plugins.server.txt"
OUT = os.path.join(ROOT, "server", "admin-placeables.json")

lo = core.LoadOrder(DATA, ORDER)
try:
    from bsastrings import Strings
    STRINGS = Strings(DATA)
except Exception as e:  # no vanilla BSAs here: localized names fall back to editor ids
    print("no .STRINGS tables (%s); localized names use editor ids" % e)
    STRINGS = None
LOCALIZED = 0x80

def desc(canon): src, loc = canon.rsplit(":", 1); return "%x:%s" % (int(loc, 16), src)
def full(p, sub):
    v = sub.get(b"FULL", b"")
    if not v: return ""
    if p.hflags & LOCALIZED:
        if STRINGS is None or len(bytes(v)) != 4: return ""
        return (STRINGS.text(p.name, struct.unpack("<I", bytes(v))[0]) or "").strip()
    return bytes(v).rstrip(b"\0").decode("cp1252", "replace").strip()
def humanize(e):
    e = re.sub(r"^(DLC0?[12]|CYR|BSK|BS|CC[A-Z]{3}SSE\d+_?)", "", e or "")
    e = re.sub(r"([a-z])([A-Z])", r"\1 \2", e)
    e = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", e)
    return e.replace("_", " ").strip() or "Unknown"
BAD = re.compile(r"dummy|test|delete|unused|zzz|removed|^fx|marker$|^xmarker|^com|debug|temp$", re.I)
STATION = re.compile(r"forge|anvil|workbench|tanning|smelter|alchemy|enchant|cooking|cookpot|spit|grindstone|loom|oven|churn|sharpening|armortable|craft", re.I)

TYPES = ("NPC_", "FURN", "CONT", "ACTI", "STAT", "MSTT", "LIGH", "FLOR", "TREE")
recs = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, TYPES):
        c = lo.canon(p, fid)
        if fl & 0x20: recs.pop(c, None); continue  # deleted by a later plugin
        sub = lo.subrecords(p, off, sz, fl)
        e = esplib.edid_of(lo.body(p, off, sz, fl)) or ""
        name = full(p, sub) or (recs.get(c, {}).get("name") if recs.get(c, {}).get("named") else "")
        recs[c] = {"t": t, "edid": e, "name": name or humanize(e), "named": bool(name),
                   "model": b"MODL" in sub, "src": c.rsplit(":", 1)[0]}

def category(r):
    t = r["t"]
    if t == "NPC_": return "NPCs"
    if t == "FURN": return "Crafting Stations" if STATION.search(r["edid"]) else "Furniture"
    if t == "ACTI" and re.search(r"^Mine|OreVein|Geode|Salt", r["edid"], re.I): return "Ore Veins"
    return {"CONT": "Containers", "ACTI": "Activators", "STAT": "Statics", "MSTT": "Moveable Statics",
            "LIGH": "Lights", "FLOR": "Flora", "TREE": "Trees", "FURN": "Furniture"}[t]

ORDERED = ["NPCs", "Crafting Stations", "Furniture", "Containers", "Ore Veins", "Activators", "Lights", "Flora", "Trees",
           "Moveable Statics", "Statics"]
cats = collections.OrderedDict((k, []) for k in ORDERED)
for c, r in recs.items():
    if not r["edid"] or BAD.search(r["edid"]): continue
    if r["t"] != "NPC_" and not r["model"]: continue  # nothing to see once placed
    cats[category(r)].append([desc(c), r["name"], r["src"]])

out = {"_comment": "Generated by ck-mcp/admin_placeables.py; read by the F7 Place tab (placement.js). Do not edit by hand.",
       "categories": [{"id": k, "label": k, "kind": "npc" if k == "NPCs" else "object",
                       "items": sorted(v, key=lambda x: (x[1].lower(), x[0]))} for k, v in cats.items() if v]}
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
print(OUT, os.path.getsize(OUT), "bytes;", ", ".join("%s %d" % (c["id"], len(c["items"])) for c in out["categories"]))
