"""Which of Blade or Blunt each character fought with, for moving One-Handed / Two-Handed progress (masterySystem.ts).

Reads every "equipment <name> #TAG: ... worn=[...]" line in the game server log, classifies each worn weapon by its WEAP
DNAM animation type in the load order, and writes server/melee-migration.json: { byTag: { TAG: "blade" | "blunt" },
counts: { TAG: [blade, blunt] } }. A character with no melee weapon in the log is left out; the migration then falls back
to their last saved outfit, and to Blade. Run on the dev server:

    sudo python3 server/tooling/melee_migration.py /var/log/skymp-server.log
"""
import collections, json, os, re, struct, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "ck-mcp"))
import core, esplib

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LOG = sys.argv[1] if len(sys.argv) > 1 else "/var/log/skymp-server.log"
lo = core.LoadOrder("/opt/skyrim-data", os.path.join(ROOT, "fork", "deploy", "skyrim-data", "loadorder.txt"))
BLADE, BLUNT = {1, 2, 5}, {3, 4, 6}  # Sword, Dagger, Greatsword | WarAxe, Mace, Battleaxe/Warhammer
TOOLS = re.compile(r"pick.?axe|^axe01$|woodcut|hatchet", re.I)
side_of = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("WEAP",)):
        body = lo.body(p, off, sz, fl)
        e = esplib.edid_of(body) or ""
        dnam = dict((s, bytes(v)) for s, v in esplib.subrecords(body)).get(b"DNAM", b"")
        # A pickaxe and a woodcutter's axe are war axes to the engine, but they are tools, not a fighting style
        if e and dnam and not TOOLS.search(e):
            side_of[e] = "blade" if dnam[0] in BLADE else "blunt" if dnam[0] in BLUNT else None

LINE = re.compile(r"equipment .*?#([A-Z0-9]{4}): .*?worn=\[([^\]]*)\]")
counts = collections.defaultdict(lambda: [0, 0])
with open(LOG, encoding="utf-8", errors="replace") as f:
    for line in f:
        m = LINE.search(line)
        if not m: continue
        for edid in (x.strip() for x in m.group(2).split(",")):
            s = side_of.get(edid)
            if s: counts[m.group(1)][0 if s == "blade" else 1] += 1
by_tag = {tag: ("blunt" if c[1] > c[0] else "blade") for tag, c in counts.items()}
out = os.path.join(ROOT, "server", "melee-migration.json")
with open(out, "w") as f:
    json.dump({"_comment": "Generated by server/tooling/melee_migration.py from the game server log; read once by masterySystem.ts when it moves One-Handed/Two-Handed to Blade/Blunt.",
               "byTag": by_tag, "counts": {t: c for t, c in counts.items()}}, f, indent=1, sort_keys=True)
print(out, len(by_tag), "characters:", collections.Counter(by_tag.values()))
