"""Builds the admin panel catalogs from the whole load order:
  server\\admin-items.json      every playable item of every plugin, by category, with the plugin it comes from
  server\\admin-locations.json  every map marker, grouped into Skyrim, Cyrodiil, Morrowind, Hammerfell and Other
Names come from FULL: plain text in a normal plugin, and through the .STRINGS tables (bsastrings.py) in a
localized one, which is every vanilla file. Editor ids are only a last resort now."""
import sys, json, struct, re, collections
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib
from bsastrings import Strings
DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
lo = core.LoadOrder(DATA, r"E:\DragonBreak Online Dev files\server\plugins.server.txt")
STRINGS = Strings(DATA)
LOCALIZED = 0x80
unresolved = collections.Counter()
def edid(p, off, sz, fl): return esplib.edid_of(lo.body(p, off, sz, fl)) or ""
def desc(canon): src, loc = canon.rsplit(":", 1); return "%x:%s" % (int(loc, 16), src)
def full(p, sub):
    v = sub.get(b"FULL", b"")
    if not v: return ""
    if p.hflags & LOCALIZED:
        if len(bytes(v)) != 4: return ""
        text = STRINGS.text(p.name, struct.unpack("<I", bytes(v))[0])
        if not text: unresolved[p.name] += 1
        return (text or "").strip()
    return bytes(v).rstrip(b"\0").decode("cp1252", "replace").strip()
def humanize(e):
    e = re.sub(r"^(DLC0?[12]|CYR|BSK|BS|CC[A-Z]{3}SSE\d+_?)", "", e or "")
    e = re.sub(r"Location$", "", e)
    e = re.sub(r"([a-z])([A-Z])", r"\1 \2", e)
    e = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", e)
    return e.replace("_", " ").strip() or "Unknown"
BAD = re.compile(r"dummy|test|unarmed|skin|naked|^fx|nopickup|npconly|_npc|npc_|delete|unused|zzz|removed", re.I)

# ---------------------------------------------------------------- items
TYPES = ("WEAP", "ARMO", "AMMO", "ALCH", "INGR", "MISC", "BOOK", "SLGM", "KEYM", "SCRL")
items, origin = {}, {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, TYPES):
        c = lo.canon(p, fid)
        origin.setdefault(c, c.rsplit(":", 1)[0])
        if fl & 0x20: items.pop(c, None); continue
        sub = lo.subrecords(p, off, sz, fl)
        e = edid(p, off, sz, fl)
        name = full(p, sub) or (items.get(c, {}).get("name") if items.get(c, {}).get("named") else "")
        rec = {"t": t, "edid": e, "name": name or humanize(e), "named": bool(name), "nonPlayable": bool(fl & 0x4), "sub": {}}
        if t == "ARMO":
            bod = sub.get(b"BOD2", b"") or sub.get(b"BODT", b"")
            if len(bod) >= 8:
                biped = struct.unpack("<I", bod[:4])[0]
                atype = struct.unpack("<I", bod[4:8])[0] if len(sub.get(b"BOD2", b"")) >= 8 else (struct.unpack("<I", bod[8:12])[0] if len(bod) >= 12 else 2)
                rec["sub"] = {"biped": biped, "atype": atype}
            rec["ench"] = b"EITM" in sub
            rec["template"] = b"TNAM" in sub
        elif t == "WEAP":
            rec["ench"] = b"EITM" in sub
            rec["template"] = b"CNAM" in sub
        elif t == "ALCH":
            enit = sub.get(b"ENIT", b"")
            rec["food"] = len(enit) >= 8 and bool(struct.unpack("<I", enit[4:8])[0] & 0x2)
        elif t == "BOOK":
            data = sub.get(b"DATA", b"")
            rec["tome"] = len(data) >= 1 and bool(data[0] & 0x04)
        items[c] = rec

def category(r):
    t = r["t"]
    if t == "WEAP": return "Enchanted Weapons" if r.get("ench") else "Weapons"
    if t == "ARMO":
        s = r.get("sub") or {}
        if s.get("biped", 0) & (0x20 | 0x40): return "Jewelry"
        if s.get("atype") == 2: return "Clothing"
        return "Enchanted Armor" if r.get("ench") else "Armor"
    return {"AMMO": "Arrows", "ALCH": "Food" if r.get("food") else "Potions", "INGR": "Ingredients", "MISC": "Misc",
            "BOOK": "Spell Tomes" if r.get("tome") else "Books", "SLGM": "Soul Gems", "KEYM": "Keys", "SCRL": "Scrolls"}[t]

cats = collections.OrderedDict((k, []) for k in ["Weapons", "Enchanted Weapons", "Armor", "Enchanted Armor", "Clothing", "Jewelry", "Arrows",
                                                 "Potions", "Food", "Ingredients", "Soul Gems", "Spell Tomes", "Scrolls", "Books", "Keys", "Misc"])
for c, r in items.items():
    if r["nonPlayable"] or BAD.search(r["edid"]) or not r["edid"]: continue
    if r["t"] == "ARMO" and not (r.get("sub") or {}).get("biped"): continue  # no body slot: not wearable
    cats[category(r)].append([desc(c), r["name"], origin[c]])
for k in cats: cats[k].sort(key=lambda x: (x[1].lower(), x[2]))
out = {"_comment": "Generated by ck-mcp/admin_catalog.py: [desc, name, plugin] per playable item.",
       "categories": [{"id": k, "label": k, "items": v} for k, v in cats.items() if v]}
json.dump(out, open(r"E:\DragonBreak Online Dev files\server\admin-items.json", "w"), separators=(",", ":"))
print("items", {k: len(v) for k, v in cats.items()})
print("plugins", len({x[2] for v in cats.values() for x in v}))

# ---------------------------------------------------------------- locations
worlds = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("WRLD",)):
        c = lo.canon(p, fid)
        worlds[c] = {"edid": edid(p, off, sz, fl) or worlds.get(c, {}).get("edid", ""), "origin": c.rsplit(":", 1)[0]}
def region(wc):
    w = worlds.get(wc, {"edid": "", "origin": wc.rsplit(":", 1)[0]})
    e, o = w["edid"], w["origin"].lower()
    if re.search(r"blackreach|sovngarde|soulcairn|forgottenvale|apocrypha|test|arena|warehouse|dim|void|hub|qasmoke|aetherium|deepfolk|throat", e, re.I): return "Other"
    if o.startswith("bsheartland") or o.startswith("bsassets"): return "Cyrodiil"
    if "baan malur" in o or "solstheim" in e.lower() or o == "dragonborn.esm": return "Morrowind"
    if o.startswith("sentinel") or o.startswith("gray fox cowl"): return "Hammerfell"
    if o in ("skyrim.esm", "update.esm", "dawnguard.esm", "hearthfires.esm") or "jk" in o or "great cit" in o or "cotn" in o or "whiterun" in o or "windhelm" in o or "riften" in o: return "Skyrim"
    return "Other"

lctn = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("LCTN",)):
        c = lo.canon(p, fid); sub = lo.subrecords(p, off, sz, fl)
        lctn[c] = full(p, sub) or lctn.get(c) or humanize(edid(p, off, sz, fl))
cell_loc = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("CELL",)):
        sub = lo.subrecords(p, off, sz, fl); x = sub.get(b"XLCN", b"")
        if len(x) >= 4: cell_loc[lo.canon(p, fid)] = lo.canon(p, struct.unpack("<I", x[:4])[0])

MAP_MARKER = "Skyrim.esm:000010"
markers = {}
door_link = {}   # load door -> (world, cell, destination door, arrival pos, arrival rot deg)
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        w, c, g = ctx
        key = lo.canon(p, fid)
        if not fl & 0x20:
            x = lo.subrecords(p, off, sz, fl).get(b"XTEL", b"")
            if len(x) >= 28:
                v = struct.unpack("<6f", x[4:28])
                door_link[key] = (lo.canon(p, w) if w else None, lo.canon(p, c) if c else None, lo.canon(p, struct.unpack("<I", x[:4])[0]), list(v[:3]), v[5] * 57.2958)
        if not w: continue
        if fl & 0x20 or fl & 0x800: markers.pop(key, None); continue
        f = lo.ref_fields(p, off, sz, fl)
        if f["base"] != MAP_MARKER or not f["pos"]: continue
        sub = lo.subrecords(p, off, sz, fl)
        name = full(p, sub)
        if not name and c and cell_loc.get(lo.canon(p, c)): name = lctn.get(cell_loc[lo.canon(p, c)], "")
        wc = lo.canon(p, w)
        markers[key] = {"name": name, "world": wc, "pos": f["pos"], "rot": f["rot"] or [0, 0, 0]}

rows = []
# Worlds without map markers (Sentinel, Journey to Baan Malur...): one point per named location that has an outside door,
# standing where that door's inside partner drops you back outside
have = {(m["world"], (m["name"] or "").lower()) for m in markers.values()}
marker_count = collections.Counter(m["world"] for m in markers.values())
for door, (w, c, dest, apos, arot) in door_link.items():
    if not w or marker_count[w] >= 5: continue
    back = door_link.get(dest)
    if not back or back[0] or not back[1]: continue  # the partner must be an interior door leading back out
    loc = cell_loc.get(c) if c else None
    loc = loc or cell_loc.get(back[1])
    name = lctn.get(loc, "") if loc else ""
    if not name or (w, name.lower()) in have: continue
    have.add((w, name.lower()))
    markers["door:" + door] = {"name": name, "world": w, "pos": back[3], "rot": [0, 0, back[4] / 57.2958]}
seen = collections.Counter()
for k, m in markers.items():
    wname = humanize(worlds.get(m["world"], {}).get("edid", "")) or "World"
    name = m["name"] or "%s %d,%d" % (wname, round(m["pos"][0] / 4096), round(m["pos"][1] / 4096))
    rows.append({"name": name, "region": region(m["world"]), "world": desc(m["world"]), "worldName": wname,
                 "pos": [m["pos"][0], m["pos"][1], m["pos"][2] + 64], "rot": [0, 0, m["rot"][2] * 57.2958]})
for r in rows: seen[(r["region"], r["name"])] += 1
for r in rows:
    if seen[(r["region"], r["name"])] > 1: r["name"] = "%s (%s)" % (r["name"], r["worldName"])
names = collections.Counter(r["name"] for r in rows)
for r in rows:
    if names[r["name"]] > 1: r["name"] = "%s %d,%d" % (r["name"], round(r["pos"][0] / 4096), round(r["pos"][1] / 4096))
rows.sort(key=lambda r: (r["region"], r["name"].lower()))
json.dump({"_comment": "Generated by ck-mcp/admin_catalog.py: every map marker, +64 z, rot in degrees.", "locations": rows},
          open(r"E:\DragonBreak Online Dev files\server\admin-locations.json", "w"), indent=0)
print("locations", len(rows), dict(collections.Counter(r["region"] for r in rows)))
coord = [r for r in rows if re.match(r"^%s -?\d+,-?\d+$" % re.escape(r["worldName"]), r["name"])]
print("still named after coordinates:", len(coord), [r["name"] for r in coord[:10]])
if unresolved: print("FULL string ids that no .STRINGS table had:", dict(unresolved.most_common(10)))
print("worlds by region", dict(collections.Counter((region(w), v["edid"]) for w, v in worlds.items() if any(m["world"] == w for m in markers.values()))))
