"""Builds server\\admin-powers.json for the admin panel's Powers tab:
  spells: every spell a spell tome teaches (BOOK with the teaches-spell flag), with its editor id
  shouts: every SHOU with its three words of power (WOOP), with editor ids
Plugin FULL names are localized string ids, so names come from editor ids."""
import sys, json, struct
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib
lo = core.LoadOrder(r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data", r"E:\DragonBreak Online Dev files\server\plugins.server.txt")
def edid(p, off, sz, fl): return esplib.edid_of(lo.body(p, off, sz, fl)) or ""
def desc(canon): src, loc = canon.rsplit(":", 1); return "%x:%s" % (int(loc, 16), src)
SKIP = ("test", "dummy", "cut", "unused", "delete", "qa", "debug")

spel, book, shou, woop = {}, {}, {}, {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("SPEL", "BOOK", "SHOU", "WOOP")):
        c = lo.canon(p, fid)
        if fl & 0x20:
            for d in (spel, book, shou, woop): d.pop(c, None)
            continue
        e = edid(p, off, sz, fl)
        sub = lo.subrecords(p, off, sz, fl)
        if t == "SPEL":
            spit = sub.get(b"SPIT", b"")
            stype = struct.unpack("<I", spit[8:12])[0] if len(spit) >= 12 else -1
            spel[c] = {"edid": e, "type": stype}
        elif t == "BOOK":
            data = sub.get(b"DATA", b"")
            if len(data) >= 8:
                flags = data[0]
                if flags & 0x04:
                    book[c] = {"edid": e, "spell": lo.canon(p, struct.unpack("<I", data[4:8])[0])}
        elif t == "SHOU":
            words = []
            for s, v in esplib.subrecords(lo.body(p, off, sz, fl)):
                if s == b"SNAM" and len(v) >= 4:
                    w = struct.unpack("<I", bytes(v[:4]))[0]
                    if w: words.append(lo.canon(p, w))
            shou[c] = {"edid": e, "words": words}
        else:
            woop[c] = e

spells = {}
for b in book.values():
    s = spel.get(b["spell"])
    if not s or s["type"] != 0: continue  # type 0 = castable spell
    if any(x in s["edid"].lower() for x in SKIP): continue
    spells[b["spell"]] = s["edid"]
shouts = []
for c, s in shou.items():
    if not s["words"] or any(x in s["edid"].lower() for x in SKIP): continue
    shouts.append({"shout": desc(c), "name": s["edid"], "words": [desc(w) for w in s["words"] if w in woop]})
out = {"_comment": "Generated by ck-mcp/admin_powers.py for the admin panel Powers tab. Names are editor ids.",
       "spells": sorted(([desc(c), n] for c, n in spells.items()), key=lambda x: x[1]),
       "shouts": sorted(shouts, key=lambda x: x["name"]),
       "werewolf": "92c48:Skyrim.esm", "vampirelord": "283b:Dawnguard.esm"}
json.dump(out, open(r"E:\DragonBreak Online Dev files\server\admin-powers.json", "w"), indent=1)
print("spells", len(out["spells"]), "shouts", len(out["shouts"]), "words", sum(len(s["words"]) for s in shouts))
