"""Beds and inns, for the Well Rested system in server/rest.js.

A bed is a FURN whose editor id names a bed or bedroll. The engine's own test is the sleep marker in the
furniture's NIF (BSFurnitureMarkerNode), which no plugin record carries, so the editor id is the best record
signal: on 2026-09-23 it matched 166 of the 667 FURN in Skyrim/Update/BSAssets/BSHeartland, and those share
no keyword the other furniture lacks (RaceToScale is on 70 non-beds, FurnitureBedRoll only on bedrolls).
Child beds are left out: an adult cannot lie in one.

An inn is an interior CELL whose editor id ends a word with Inn or Tavern ("BrumaJerallViewInn",
"RiverwoodSleepingGiantInn"), not "Inner". Every inn cell found is listed with how many bed REFRs it holds,
so a cell that is really a bathhouse or a cellar shows up as zero beds.

Output: server/beds.json, ids in the server's desc form ("<hex>:<plugin>", like doors.json).

usage: py ck-mcp/beds.py
"""
import sys, json, re, struct, collections
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib

DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
PLUGINS = r"E:\DragonBreak Online Dev files\server\plugins.server.txt"
OUT = r"E:\DragonBreak Online Dev files\server\beds.json"

BED = re.compile(r"bed", re.I)
NOT_BED = re.compile(r"child|bedside|bedroom|flowerbed|riverbed|seabed|bedrock|lakebed", re.I)
INN = re.compile(r"(Inn|Tavern)(?![a-z])")
# Inns whose cell editor id does not say so. The Restful Watchman's door reads "Bruma Restful Watchman Inn"
# (doors.json) but its cell is CYRBrumaTheRestfulWatchman.
EXTRA_INNS = {"BSHeartland.esm:063121"}

lo = core.LoadOrder(DATA, PLUGINS)


def desc(canonical):
    src, loc = canonical.rsplit(":", 1)
    return "%x:%s" % (int(loc, 16), src)


# ---- bed base objects (the winning editor id decides) ----------------------------------------
edids = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("FURN",)):
        edids[lo.canon(p, fid)] = esplib.edid_of(lo.body(p, off, sz, fl)) or ""
beds = {c: e for c, e in edids.items() if BED.search(e) and not NOT_BED.search(e)}

# ---- inn cells --------------------------------------------------------------------------------
cells = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("CELL",)):
        subs = lo.subrecords(p, off, sz, fl)
        e = esplib.edid_of(lo.body(p, off, sz, fl)) or ""
        data = subs.get(b"DATA", b"")
        interior = bool(data and data[0] & 0x01)
        if interior and (INN.search(e) or lo.canon(p, fid) in EXTRA_INNS):
            cells[lo.canon(p, fid)] = e

# ---- bed REFRs inside each inn cell -------------------------------------------------------------
per_cell = collections.Counter()
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        w, c, g = ctx
        if not c:
            continue
        cell = lo.canon(p, c)
        if cell not in cells:
            continue
        nm = lo.subrecords(p, off, sz, fl).get(b"NAME")
        if nm and lo.canon(p, struct.unpack("<I", nm[:4])[0]) in beds:
            per_cell[cell] += 1

out = {
    "_comment": "Generated by ck-mcp/beds.py. beds: FURN base objects an adult sleeps in (editor id names a bed or "
                "bedroll, child beds excluded). inns: interior cells whose editor id ends in Inn or Tavern, with the "
                "bed REFRs each holds. Read by server/rest.js.",
    "beds": {desc(c): e for c, e in sorted(beds.items())},
    "inns": {desc(c): {"editorId": e, "beds": per_cell.get(c, 0)} for c, e in sorted(cells.items(), key=lambda x: x[1])},
}
with open(OUT, "w", encoding="utf-8") as fh:
    json.dump(out, fh, indent=1)
print("beds: %d base objects; inns: %d cells, %d with beds" % (len(beds), len(cells), sum(1 for c in cells if per_cell.get(c))))
for c, e in sorted(cells.items(), key=lambda x: x[1]):
    print("  %-45s %-32s beds=%d" % (e, c, per_cell.get(c, 0)))
