"""What every shrine blessing in this load order actually does.

The deity work needs the real effect of each Altar<Deity>Spell, not a memory of it: the magic effect
behind it, its archetype, the actor value it moves, and the magnitude and duration on the spell's own
effect entry. It also lists which Daedric Princes have no altar spell at all, which is the set that
needs authoring.

usage: py ck-mcp\blessings.py
"""
import sys, struct, json, collections
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib

DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
PLUGINS = r"E:\DragonBreak Online Dev files\server\plugins.server.txt"
OUT = r"E:\DragonBreak Online Dev files\server\blessing-effects.json"

lo = core.LoadOrder(DATA, PLUGINS)

# The MGEF *editor id* is what this script reports, and nothing derived from the DATA block.
# A first version decoded an archetype and an actor value out of DATA at guessed offsets and printed
# "ValueModifier / AggressionAV" for all eighteen blessings, which is plainly wrong - AggressionAV is
# index 0, so the read was landing on padding. Rather than guess the SSE MGEF layout, this reports
# the editor id (FortifyMagickaRateFFSelf, FortifySneakFFSelf, ...), which names the effect exactly
# and unambiguously, plus the magnitude and duration from the spell's own effect entry, which are at
# known offsets in EFIT. If the archetype is ever needed, read it in the Creation Kit or xEdit.

# ---- index every MGEF and SPEL we might need ---------------------------------------------------
mgef = {}
spel = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("MGEF", "SPEL")):
        c = lo.canon(p, fid)
        sub = lo.subrecords(p, off, sz, fl)
        e = esplib.edid_of(lo.body(p, off, sz, fl)) or ""
        if t == "MGEF":
            mgef[c] = {"edid": e or mgef.get(c, {}).get("edid", ""), "sub": sub, "from": p.name}
        else:
            spel[c] = {"edid": e or spel.get(c, {}).get("edid", ""), "sub": sub,
                       "body": lo.body(p, off, sz, fl), "from": p.name, "plugin": p, "off": off,
                       "size": sz, "flags": fl}

def mgef_detail(cid):
    m = mgef.get(cid)
    if not m:
        return {"id": cid, "edid": "(not found)"}
    return {"id": cid, "edid": m["edid"], "from": m["from"]}

# A spell's effects: EFID/EFIT pairs in order.
def effects_of(rec):
    out, efid = [], None
    for tag, raw in esplib.iter_subrecords(rec["body"]) if hasattr(esplib, "iter_subrecords") else []:
        pass
    # esplib.subrecords collapses duplicates, so walk the body by hand for the repeated EFID/EFIT
    body, i = rec["body"], 0
    while i + 6 <= len(body):
        tag = body[i:i + 4]
        ln = struct.unpack_from("<H", body, i + 4)[0]
        raw = body[i + 6:i + 6 + ln]
        if tag == b"EFID" and len(raw) >= 4:
            efid = lo.canon(rec["plugin"], struct.unpack("<I", raw[:4])[0])
        elif tag == b"EFIT" and len(raw) >= 12:
            mag, area, dur = struct.unpack("<fII", raw[:12])
            out.append({"mgef": mgef_detail(efid) if efid else None,
                        "magnitude": round(mag, 3), "area": area, "duration": dur})
            efid = None
        i += 6 + ln
    return out

# ---- the shrine blessings ----------------------------------------------------------------------
wanted = {}
for c, r in spel.items():
    e = r["edid"]
    if e.startswith("Altar") or e.startswith("DLC1Altar") or e.startswith("DLC2Altar"):
        wanted[c] = r

report = {"_comment": "Generated by ck-mcp\\blessings.py. What each shrine blessing in this load order "
                      "actually does - measured, not remembered.", "blessings": {}}
print("%d Altar*Spell records\n" % len(wanted))
for c in sorted(wanted, key=lambda k: wanted[k]["edid"]):
    r = wanted[c]
    spit = r["sub"].get(b"SPIT", b"")
    stype = struct.unpack_from("<I", spit, 8)[0] if len(spit) >= 12 else None
    eff = effects_of(r)
    report["blessings"][r["edid"]] = {"id": c, "from": r["from"], "spellType": stype, "effects": eff}
    print("%-28s %-38s type=%s" % (r["edid"], c, stype))
    for x in eff:
        m = x["mgef"] or {}
        print("    %-36s mag=%-7g dur=%-6d %s" % (m.get("edid", "?"), x["magnitude"], x["duration"],
                                                  m.get("id", "")))
    print()

with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
    json.dump(report, fh, indent=2)
    fh.write("\n")
print("wrote", OUT)
