"""Writes server\\notice-board-spots.json: every enabled notice board placed in the load order.

BountyBoardSystem seeds these at boot so the N hotkey, /board and pigeons find a board before anyone
has clicked it since the restart, and so boards that cannot be activated (static meshes) work at all.
Interior boards need a zone, since zones.json only places exteriors; CELL_ZONES supplies it.

Run from the working root:  py ck-mcp\\board_spots.py
"""
import sys, json, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import core

ROOT = r"E:\DragonBreak Online Dev files"
lo = core.LoadOrder(ROOT + r"\Skyrim Special Edition - dev\Data", ROOT + r"\server\plugins.server.txt")

# Board bases: the activators BountyBoardSystem hooks, and the containers and statics that look like boards
BASES = {
    "DragonBreak.esp:000006": "Noticeboard",
    "notice board.esp:003E10": "manny_up_NoticeBoardActivator",
    "DragonBreak Harvest.esp:000900": "RP_NoticeBoard",
    "DragonBreak Harvest.esp:000901": "RP_NoticeBoardCandle",
    "DragonBreak Harvest.esp:000902": "RP_NoticeBoardWall",
    "Gray Fox Cowl.esm:0360BA": "manny_GF_Cont_AlikrNoticeBoard",
    "DragonBreak.esp:014CC9": "BountyBoard",
    "DragonBreak.esp:000A68": "BountyBoardSnow",
    "DragonBreak.esp:002080": "BountyBoardSnowDUPLICATE001",
    "DragonBreak.esp:002A51": "BountyBoardDUPLICATE001",
    "OCW_Obscure's_CollegeofWinterhold.esp:5DC577": "OBS_NobleBulletinBoardExt_01",
    "OCW_Obscure's_CollegeofWinterhold.esp:753567": "OBS_NobleBulletinBoardInt_01",
}
# Interior cell -> zones.json id
CELL_ZONES = {
    "Skyrim.esm:01527C": "whiterun",                                   # FortGreymoor01
    "Skyrim.esm:0CAB92": "winterhold",                                 # WinterholdCollegeArchMageQuarters
    "OCW_Obscure's_CollegeofWinterhold.esp:16D0C5": "winterhold",      # WinterholdCollegeHallofDiligence
}

def desc(canonical):
    plugin, local = canonical.rsplit(":", 1)
    return "%x:%s" % (int(local, 16), plugin)

refs = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        f = lo.ref_fields(p, off, sz, fl)
        if f["base"] not in BASES:
            continue
        w, c, g = ctx
        # Later plugins override earlier ones; the last definition wins, as in game
        refs[lo.canon(p, fid)] = (f, w and lo.canon(p, w), c and lo.canon(p, c), lo.flag_names(fl))

spots, skipped = [], []
for ref, (f, world, cell, flags) in sorted(refs.items()):
    name = BASES[f["base"]]
    if any(x in str(flags).lower() for x in ("disabled", "deleted")) or not f["pos"]:
        skipped.append((ref, name, "disabled"))
        continue
    spot = {"ref": desc(ref), "base": name, "where": desc(world or cell), "pos": [round(v, 1) for v in f["pos"]]}
    if not world:
        zone = CELL_ZONES.get(cell)
        if not zone:
            skipped.append((ref, name, "interior with no zone: " + str(cell)))
            continue
        spot["zone"] = zone
    spots.append(spot)

out = {"_comment": "Generated by ck-mcp/board_spots.py. Every enabled notice board; BountyBoardSystem seeds these at boot. "
                   "'zone' is set only for interiors, exteriors resolve through zones.json.",
       "spots": spots}
with open(ROOT + r"\server\notice-board-spots.json", "w", encoding="utf-8") as fh:
    json.dump(out, fh, indent=1)
print(len(spots), "spots written")
for s in skipped:
    print("skipped", *s)
