"""Builds server\\doors.json: every load door in the load order -> a readable name for where it leads.
Names come from editor ids (the ESM FULL strings are localized ids): the destination cell's location
(XLCN) when it has one, otherwise the destination cell, otherwise the worldspace."""
import sys, json, struct, re
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib
lo = core.LoadOrder(r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data", r"E:\DragonBreak Online Dev files\server\plugins.server.txt")
def edid(p, off, sz, fl): return esplib.edid_of(lo.body(p, off, sz, fl)) or ""
def desc(canon): src, loc = canon.rsplit(":", 1); return "%x:%s" % (int(loc, 16), src)
FIXED = {"BYOHHouse1": "Lakeview Manor", "BYOHHouse2": "Windstad Manor", "BYOHHouse3": "Heljarchen Hall", "Tamriel": "Skyrim", "DLC2SolstheimWorld": "Solstheim"}
def humanize(e):
    e = e or ''
    for k, v in FIXED.items():
        if e.startswith(k): return v
    prev = None
    while prev != e:  # strip stacked suffixes like ...2LocationInterior and mod prefixes like mannyGFL / SSewers
        prev = e
        e = re.sub(r'(Location|Exterior|Interior|Zone|World|Origin|DUPLICATE|Duplicate|\d+)$', '', e)
        e = re.sub(r'^(DLC1|DLC2|DLC01|DLC02|CYR|BSK|BS|dun|Dun|manny[A-Z]*|SSewers|S(?=[A-Z][a-z]))', '', e)
    e = re.sub(r'([a-z])([A-Z])', r'\1 \2', e)
    e = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', e)
    e = e.replace('_', ' ')
    return re.sub(r'\s+', ' ', e).strip()
cells, locs, worlds, loc_parent = {}, {}, {}, {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("CELL", "LCTN", "WRLD")):
        c = lo.canon(p, fid); e = edid(p, off, sz, fl)
        if t == "CELL":
            sub = lo.subrecords(p, off, sz, fl); x = sub.get(b"XLCN", b"")
            prev = cells.get(c, {})
            cells[c] = {"edid": e or prev.get("edid", ""), "loc": lo.canon(p, struct.unpack("<I", x[:4])[0]) if len(x) >= 4 else prev.get("loc")}
        elif t == "LCTN":
            sub = lo.subrecords(p, off, sz, fl); pn = sub.get(b"PNAM", b"")
            locs[c] = e; loc_parent[c] = lo.canon(p, struct.unpack("<I", pn[:4])[0]) if len(pn) >= 4 else None
        else: worlds[c] = e
door_target, ref_cell = {}, {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        w, c, g = ctx
        key = lo.canon(p, fid)
        # The winning version decides: a ref deleted by a later plugin (the server skips it) is gone, and an
        # override without XTEL is no load door any more (DragonBreak Online Edits and the city mods do both)
        if fl & esplib.DEL:
            door_target.pop(key, None); ref_cell.pop(key, None)
            continue
        if c: ref_cell[key] = (lo.canon(p, c), lo.canon(p, w) if w else None)
        sub = lo.subrecords(p, off, sz, fl); x = sub.get(b"XTEL", b"")
        if len(x) >= 4: door_target[key] = lo.canon(p, struct.unpack("<I", x[:4])[0])
        else: door_target.pop(key, None)
out = {}
for door, target in door_target.items():
    cw = ref_cell.get(target)
    if not cw: continue
    cell, world = cw
    info = cells.get(cell, {})
    name = humanize(locs.get(info.get("loc"), ""))
    if not name and world:
        # Outdoors with no location of its own: the hold the door's own building belongs to
        src = ref_cell.get(door)
        src_loc = cells.get(src[0], {}).get("loc") if src else None
        parent = loc_parent.get(src_loc) if src_loc else None
        name = humanize(locs.get(parent, "")) if parent else ""
        if not name: name = humanize(worlds.get(world, ""))
    if not name: name = humanize(info.get("edid", ""))
    if name: out[desc(door)] = name
# an output path argument writes elsewhere, for a dry run to diff against the live file
json.dump({"_comment": "Generated by ck-mcp/doors.py: load door -> readable destination name (from editor ids).", "doors": out}, open(sys.argv[1] if len(sys.argv) > 1 else r"E:\DragonBreak Online Dev files\server\doors.json", "w"), indent=0)
print("doors", len(out)); print(list(out.items())[:12])
