"""Every jail and prison in the load order, for server/jail.js.

Two signals:
  1. interior cells whose editor id says Jail or Prison (every town jail but four, DragonBreak's own prisons,
     Baan Malur's and Fort Tulis's);
  2. the town and castle jails whose cells are named otherwise, by editor id (EXTRA below).
Not a signal, measured 2026-09-23: a FACT's JAIL subrecord is the release marker outside the jail (Bruma's stands in
the castle Great Hall), and jail-door models are used in banks, shops, sewers and bandit forts alike.
Cells that are dungeon-lease interiors (server/dungeons.json) are left out: a jail forbids /unstuck, and a dungeon
must not. Each cell is listed with its cell doors (non-load DOORs), and a cell with none is reported but kept.

Output: server/jail-cells.json, cells in the server's desc form ("<hex>:<plugin>").

usage: py ck-mcp/jails.py
"""
import sys, json, re, struct, collections
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib

DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
PLUGINS = r"E:\DragonBreak Online Dev files\server\plugins.server.txt"
DUNGEONS = r"E:\DragonBreak Online Dev files\server\dungeons.json"
CONFIG = r"E:\DragonBreak Online Dev files\server\gamemode-config.json"
OUT = r"E:\DragonBreak Online Dev files\server\jail-cells.json"

NAMED = re.compile(r"jail|prison", re.I)
# Jails whose cell is not named one: Bruma's and Kvatch's castle dungeons, Markarth's Cidhna Mine, Whiterun's cells
# under Dragonsreach (8 WRJailDoor01)
EXTRA = {"CYRBrumaCastleDungeon", "CYRKvatchCastleDungeon", "CidhnaMine01", "WhiterunDragonsreachBasement"}

lo = core.LoadOrder(DATA, PLUGINS)


def desc(canonical):
    src, loc = canonical.rsplit(":", 1)
    return "%x:%s" % (int(loc, 16), src)


def norm(d):
    h, p = d.split(":", 1)
    return "%x:%s" % (int(h, 16), p.lower())


# ---- dungeon-lease interiors, never jails -------------------------------------------------------
lease = set()
# The same dungeons dungeons.js drops: its built-in exclusion plus gamemode-config dungeons.exclude
excluded = {"CYRLakesideRetreatLocation"}
try:
    excluded |= set(json.load(open(CONFIG, encoding="utf-8")).get("dungeons", {}).get("exclude", []))
except Exception as e:
    print("gamemode-config.json unreadable, only the built-in dungeon exclusion applies:", e)
try:
    for d in json.load(open(DUNGEONS, encoding="utf-8")).get("dungeons", []):
        if d.get("id") in excluded:
            continue
        for c in d.get("cells", []):
            lease.add(norm(c["desc"]))
except Exception as e:
    print("dungeons.json unreadable, no lease cells excluded:", e)

# ---- interior cells and their editor ids (winning record) ------------------------------------------
cells = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("CELL",)):
        s = lo.subrecords(p, off, sz, fl)
        data = s.get(b"DATA", b"")
        if data and data[0] & 0x01:
            cells[lo.canon(p, fid)] = esplib.edid_of(lo.body(p, off, sz, fl)) or ""

# ---- one pass over every REFR: the doors in each interior ----------------------------------------------
doors = set()
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("DOOR",)):
        doors.add(lo.canon(p, fid))
cell_doors = collections.defaultdict(lambda: [0, 0])  # cell -> [plain doors, load doors]
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        w, c, g = ctx
        if not c:
            continue
        cell = lo.canon(p, c)
        if cell not in cells:
            continue
        s = lo.subrecords(p, off, sz, fl)
        nm = s.get(b"NAME")
        if nm and lo.canon(p, struct.unpack("<I", nm[:4])[0]) in doors:
            cell_doors[cell][1 if b"XTEL" in s else 0] += 1

found = {}  # cell -> why
for cell, e in cells.items():
    if NAMED.search(e):
        found.setdefault(cell, []).append("named")
    elif e in EXTRA:
        found.setdefault(cell, []).append("known jail")

kept, dropped = {}, {}
for cell, why in found.items():
    (dropped if norm(desc(cell)) in lease else kept)[cell] = why

out = {
    "_comment": "Generated by ck-mcp/jails.py: interior cells named Jail/Prison plus the town and castle jails named otherwise, "
                "minus dungeon-lease interiors. Read by server/jail.js with gamemode-config jail.cells and jails.json.",
    "cells": [desc(c) for c in sorted(kept, key=lambda c: cells[c])],
    "detail": {desc(c): {"editorId": cells[c], "why": sorted(set(kept[c])), "cellDoors": cell_doors[c][0], "loadDoors": cell_doors[c][1]}
               for c in sorted(kept, key=lambda c: cells[c])},
    "skippedAsDungeons": {desc(c): cells[c] for c in sorted(dropped, key=lambda c: cells[c])},
}
with open(OUT, "w", encoding="utf-8") as fh:
    json.dump(out, fh, indent=1)
print("jails: %d cells, %d skipped as dungeon leases" % (len(kept), len(dropped)))
for c in sorted(kept, key=lambda c: cells[c]):
    print("  %-42s %-30s cell doors %2d  %s" % (cells[c], desc(c), cell_doors[c][0], "; ".join(sorted(set(kept[c])))[:90]))
for c in sorted(dropped, key=lambda c: cells[c]):
    print("  SKIPPED (dungeon lease) %s %s" % (cells[c], desc(c)))
