"""Builds server\\readables.json: spell tomes (by school and rank) and scrolls from the load order,
for the Scholar reading rewards. Rank comes from the taught spell's minimum skill level
(SPIT: 0-24 Novice, 25-49 Apprentice, 50-74 Adept, 75-99 Expert, 100 Master)."""
import sys, json, struct
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib
lo = core.LoadOrder(r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data", r"E:\DragonBreak Online Dev files\server\plugins.server.txt")
VANILLA = {"Skyrim.esm", "Dawnguard.esm", "HearthFires.esm", "Dragonborn.esm"}
AVI = {18: "Alteration", 19: "Conjuration", 20: "Destruction", 21: "Illusion", 22: "Restoration"}
spells = {}
def edid(p, off, sz, fl):
    return esplib.edid_of(lo.body(p, off, sz, fl)) or ""
# spells: canonical -> (name, school, minLevel) from the winning override
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ('SPEL',)):
        sub = lo.subrecords(p, off, sz, fl)
        spit = sub.get(b'SPIT', b'')
        if len(spit) < 36: continue
        cost, flags, stype, charge, cast, delivery, castdur, rng, perk = struct.unpack('<IIIfIIfII', spit[:36])
        # school/level are on the first effect's MGEF; resolve after the pass
        efid = sub.get(b'EFID', b'')
        first = struct.unpack('<I', efid[:4])[0] if len(efid) >= 4 else 0
        spells[lo.canon(p, fid)] = {"edid": edid(p, off, sz, fl), "type": stype, "mgef": lo.canon(p, first) if first else None, "perk": lo.canon(p, perk) if perk else None, "from": p.name}
mgefs = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ('MGEF',)):
        sub = lo.subrecords(p, off, sz, fl)
        d = sub.get(b'DATA', b'')
        if len(d) < 152: continue
        # DATA: flags(4) baseCost(4) relatedID(4) skill(4) resist(4) unk(4) castingLight(4) taperWeight(4) hitShader(4) enchantShader(4) minSkill(4) ...
        vals = struct.unpack('<IfIiIIIfIIII', d[:48])
        mgefs[lo.canon(p, fid)] = {"skill": vals[3], "minSkill": vals[10]}
perks = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ('PERK',)):
        perks[lo.canon(p, fid)] = edid(p, off, sz, fl)
RANK_WORDS = ["Novice", "Apprentice", "Adept", "Expert", "Master"]
def rank(level, perk_edid=""):
    for i, w in enumerate(RANK_WORDS):
        if w.lower() in perk_edid.lower(): return i  # e.g. DestructionAdept50, NoviceRestoration
    return 0 if level < 25 else 1 if level < 50 else 2 if level < 75 else 3 if level < 100 else 4
tomes, scrolls = [], []
seen_spells = set()
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ('BOOK', 'SCRL')):
        sub = lo.subrecords(p, off, sz, fl)
        name = sub.get(b'FULL', b'').rstrip(b'\0').decode('cp1252', 'replace')
        cid = lo.canon(p, fid)
        if lo.winner(cid) != p.name: continue
        src = cid.rsplit(':', 1)[0]
        if src not in VANILLA: continue  # keep the tables to vanilla + DLC so every client has them
        if t == 'BOOK':
            d = sub.get(b'DATA', b'')
            if len(d) < 16: continue
            bflags, btype, teaches, value, weight = struct.unpack('<BBxxIIf', d[:16])
            if not (bflags & 0x4): continue  # 0x4 = teaches spell
            sp = spells.get(lo.canon(p, teaches))
            if not sp: continue
            mg = mgefs.get(sp["mgef"]) if sp["mgef"] else None
            if not mg or mg["skill"] not in AVI: continue
            if sp["type"] != 0: continue  # 0 = spell
            key = lo.canon(p, teaches)
            if key in seen_spells: continue
            seen_spells.add(key)
            tomes.append({"id": cid, "name": edid(p, off, sz, fl), "school": AVI[mg["skill"]], "rank": rank(mg["minSkill"], perks.get(sp["perk"], "")), "spell": sp["edid"], "value": value})
        else:
            v = sub.get(b'DATA', b'')
            value = struct.unpack('<I', v[:4])[0] if len(v) >= 4 else 0
            e = edid(p, off, sz, fl)
            if 'test' in e.lower() or not e: continue
            scrolls.append({"id": cid, "name": e, "value": value})
tomes.sort(key=lambda x: (x["school"], x["rank"], x["name"]))
scrolls.sort(key=lambda x: x["name"])
out = {"_comment": "Generated by ck-mcp\\readables.py from the load order (vanilla + DLC only). Spell tomes by school and rank 0-4 (Novice..Master); scrolls. Used by the Scholar reading rewards in gamemode.js.",
       "tomes": tomes, "scrolls": scrolls}
json.dump(out, open(r"E:\DragonBreak Online Dev files\server\readables.json", "w"), indent=1)
from collections import Counter
print("tomes", len(tomes), Counter((t["school"], t["rank"]) for t in tomes))
print("scrolls", len(scrolls))
