"""Where every shrine in skills.json actually stands.

The deity work needs one number that no design document had: for each shrine base object, how many
REFRs place it, in which worldspace or interior cell, and at what position. Prayer is only reachable
if at least one placement sits inside the playtest's allowedWorlds.

usage: py ck-mcp\shrines.py
"""
import sys, json, struct, collections
sys.path.insert(0, r"E:\DragonBreak Online Dev files\ck-mcp")
import core, esplib

# Every record type a reference can place. TACT - a talking activator - was missing from this list
# on 2026-09-20 and hid the Clavicus Vile shrine twice: it reported as an unresolved "?" base while
# sitting in plain sight among the other shrines. An activator is not always an ACTI.
BASE_SIGS = ("ACTI", "TACT", "STAT", "FURN", "MSTT", "LIGH", "TREE", "FLOR", "CONT", "DOOR",
             "MISC", "SCOL", "ADDN", "NPC_", "LVLI")

DATA = r"E:\DragonBreak Online Dev files\Skyrim Special Edition - dev\Data"
PLUGINS = r"E:\DragonBreak Online Dev files\server\plugins.server.txt"
SKILLS = r"E:\DragonBreak Online Dev files\server\skills.json"

lo = core.LoadOrder(DATA, PLUGINS)


def canon_of(s):
    """skills.json writes '<local hex>:<plugin>'; core wants 'plugin:LOCALHEX' upper-cased."""
    local, plugin = s.split(":", 1)
    return "%s:%06X" % (plugin, int(local, 16))


sk = json.load(open(SKILLS, encoding="utf-8"))
wanted = {}                                    # canonical base id -> [deity names]
for ch in sk["deities"]["choices"]:
    for s in ch.get("shrines", []):
        try:
            wanted.setdefault(canon_of(s), []).append(ch["name"])
        except Exception as e:
            print("unparsable shrine id %r on %s: %s" % (s, ch["id"], e))
for name, s in (sk.get("praying", {}).get("shrines") or {}).items():
    ids = s if isinstance(s, list) else [s]
    for one in ids:
        wanted.setdefault(canon_of(one), []).append("praying:" + name)

# the Cyrodiil wayshrines, whether or not they are in skills.json yet
for i, name in enumerate(["Akatosh", "Arkay", "Dibella", "Julianos", "Kynareth",
                          "Mara", "Stendarr", "Talos", "Zenithar"]):
    wanted.setdefault("BSHeartland.esm:%06X" % (0x061B52 + i), []).append("CYR:" + name)

# ---- what each base actually is -------------------------------------------------------------
info = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, BASE_SIGS):
        c = lo.canon(p, fid)
        if c in wanted:
            info.setdefault(c, {"type": t, "edid": esplib.edid_of(lo.body(p, off, sz, fl)) or "", "from": p.name})

# ---- cells and worlds, to name a placement --------------------------------------------------
names = {}
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("WRLD", "CELL")):
        c = lo.canon(p, fid)
        e = esplib.edid_of(lo.body(p, off, sz, fl)) or ""
        if e:
            names[c] = e

# ---- every placement ------------------------------------------------------------------------
places = collections.defaultdict(list)
for p in lo.plugins:
    for ri, t, fid, fl, off, sz, ctx in lo.records(p, ("REFR",)):
        sub = lo.subrecords(p, off, sz, fl)
        nm = sub.get(b"NAME", b"")
        if len(nm) < 4:
            continue
        base = lo.canon(p, struct.unpack("<I", nm[:4])[0])
        if base not in wanted:
            continue
        w, cl, g = ctx
        data = sub.get(b"DATA", b"")
        pos = struct.unpack("<3f", data[:12]) if len(data) >= 12 else (0.0, 0.0, 0.0)
        disabled = b"XESP" in sub or (fl & 0x800) != 0          # initially disabled / deleted
        places[base].append({
            "refr": lo.canon(p, fid),
            "world": lo.canon(p, w) if w else None,
            "cell": lo.canon(p, cl) if cl else None,
            "pos": [round(v, 1) for v in pos],
            "from": p.name,
            "off": bool(disabled),
        })

ALLOWED = {"BSHeartland.esm:0A764B", "BSHeartland.esm:06ADE1",
           "BSHeartland.esm:07F126", "BSHeartland.esm:0B95A6"}

OUT = r"E:\DragonBreak Online Dev files\server\shrine-placements.json"
dump = {"_comment": "Generated by ck-mcp\\shrines.py. Where every shrine base named in skills.json "
                    "actually stands. 'inPlaytest' counts placements inside gamemode-config playtest "
                    "allowedWorlds or an interior cell from BSHeartland/BSAssets - a deity with 0 there "
                    "cannot be prayed to while the Bruma region lock is on.",
        "measured": "2026-09-20", "bases": {}}

print("=" * 96)
for base in sorted(wanted, key=lambda b: wanted[b][0]):
    i = info.get(base)
    pl = places.get(base, [])
    reach = [q for q in pl if q["world"] in ALLOWED or (q["cell"] and q["cell"].split(":")[0].lower()
             in ("bsheartland.esm", "bsassets.esm"))]
    # Narrower still: the Bruma county content a playtester will really walk through - the open
    # Cyrodiil worldspace, or an interior whose editor id names Bruma. Kvatch is in the plugin but
    # is not part of the released county, so a shrine only in Kvatch is not a reachable shrine.
    bruma = [q for q in reach if q["world"] in ALLOWED
             or "bruma" in names.get(q["cell"] or "", "").lower()]
    head = "%-28s %-34s %s" % ("/".join(sorted(set(wanted[base]))), base,
                               (i["edid"] + " [" + i["type"] + "]") if i else "BASE NOT FOUND")
    print(head)
    print("    placements: %d   in the playtest region: %d   in Bruma county: %d" % (len(pl), len(reach), len(bruma)))
    for q in reach[:10]:
        where = names.get(q["world"] or q["cell"] or "", q["world"] or q["cell"] or "?")
        print("      %-22s %-30s %-28s %s%s" % (q["refr"], where, q["pos"], q["from"],
                                                "  (initially off)" if q["off"] else ""))
    if len(reach) > 10:
        print("      ... and %d more in region" % (len(reach) - 10))
    print("-" * 96)
    dump["bases"][base] = {
        "names": sorted(set(wanted[base])),
        "editorId": i["edid"] if i else None,
        "type": i["type"] if i else None,
        "isBaseObject": bool(i),
        "placements": len(pl),
        "inPlaytest": len(reach),
        "inBruma": len(bruma),
        "sample": [{"refr": q["refr"], "where": names.get(q["world"] or q["cell"] or "", ""),
                    "pos": q["pos"]} for q in (bruma or reach or pl)[:6]],
    }

with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
    json.dump(dump, fh, indent=2)
    fh.write("\n")
print("wrote", OUT)
